### PR TITLE
apparently on VPNs it's common for the gateway for a route to be outs…

### PR DESCRIPTION
**Pull request by arvidn**
…ide of the netmask of the network it's a router for. fix that in get_gateway

### CODE REVIEW

**Comment by skuizy** [comment]
Alright, thanks for the fix, I didn't mean to hijack the other thread !

I'll wait for the next build to try it.

**Comment by arvidn** [comment]
I released 1.2.4 which includes this fix

**Comment by skuizy** [comment]
It looks like I don't have the good repo setup as it doesn't appear when I run apt update

**Comment by arvidn** [comment]
I’m not the maintainer of the apt package

**Comment by skuizy** [comment]
Well I've just updated my libtorrent to the latest 1.2.4 from launchpad and it still doesn't work.
```
20:58:41.491 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_added_alert: my_torrent added
20:58:51.313 [INFO    ][deluge.core.torrentmanager          :672 ] Torrent my_torrent from user "localclient" loaded
20:59:48.203 [DEBUG   ][deluge.core.alertmanager            :130 ] state_changed_alert: my_torrent: state changed to: downloading
20:59:48.204 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_checked_alert: my_torrent checked
21:00:06.689 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_resumed_alert: my_torrent resumed
21:00:06.689 [DEBUG   ][deluge.core.alertmanager            :130 ] tracker_announce_alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.37:64270] sending announce (started)
21:00:11.462 [DEBUG   ][deluge.core.alertmanager            :130 ] tracker_error_alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.37:64270] No route to host "" (1)
```

But my user can connect to the tracker correctly :
```
[~]$ sudo -u vpn curl -l "https://elite-tracker.net/announce.php\?passkey\=my_passkey"
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml"  dir="ltr" lang="en" id="tsse_html">
<head>



<title>Une erreur s&#039;est produite! | Elite-Tracker</title>

<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<meta name="viewport" content="width=device-width" />
<meta name="MobileOptimized" content="width" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

<meta name="description" content="Hight Speed Tracker - Le meilleur du torrent sur Elite-Tracker
Xbox360 Psp Wii Ps3 The best of the game" />

<link rel="stylesheet" href="https://elite-tracker.net/style.php?theme=ET&amp;style=style.css&amp;v=3a" type="text/css" media="screen" />
<link rel="stylesheet" href="https://elite-tracker.net/scripts/colorbox/colorbox.css" type="text/css" media="screen" />
<link rel="stylesheet" href="https://elite-tracker.net/scripts/jquery-ui-1.10.4.custom/css/flick/jquery-ui-1.10.4.custom.min.css" type="text/css" media="screen" />

<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="https://elite-tracker.net/rss.php" />
<link rel="alternate" type="text/xml" title="RSS .92" href="https://elite-tracker.net/rss.php" />

<link rel="shortcut icon" href="https://elite-tracker.net/favicon.ico" type="image/x-icon" />

<script type="text/javascript">
        //<![CDATA[
        var baseurl="https://elite-tracker.net";
        var dimagedir="https://elite-tracker.net/images/";
        var themedir="https://elite-tracker.net/include/templates/ET/";
        var charset="UTF-8";
        var userid="0";
        var securitytoken = "";
        var lang_resized = "Cette image a été redimensionnée. Cliquez sur l'image pour la voir dans sa taille d'origine. Taille d'origine: ";
        if (window.top !== window.self) {document.write = "";window.top.location = window.self.location; setTimeout(function(){document.body.innerHTML='';},1);window.self.onload=function(evt){document.body.innerHTML='';};}
        //]]>
</script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/jquery-1.11.2.min.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/jquery.lazyload.mini.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/colorbox/jquery.colorbox-min.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/bookmarkscroll.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/main.js?uv=3a&v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/menu.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/collapse.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/tooltip.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js?v=7.5"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/overlib.js"></script>
<script type="text/javascript" src="https://elite-tracker.net/scripts/ajaxtabs/ajaxtabs.js"></script>
<script type="text/javascript" src="https://elite-tracker.net/include/templates/ET/script/HautDePage.js?v=7.5"></script>
<script type="text/javascript">
        //<![CDATA[
        jQuery(document).ready(function()
        {
                if ( !navigator.userAgent.match( /ipad/i ) )
                {
                        jQuery("#lazyload img").lazyload({placeholder : themedir+"images/loading.gif", effect:"fadeIn"});
                }
                jQuery("a#ts_show_preview").colorbox({photo: true, title: function()
                {
                        var url = jQuery(this).attr('href');
                        return '<a href="'+url+'" target="_blank"><font color="white">Ouvrir dans une nouvelle fenêtre</font></a>';
                }});
        });
        //]]>
</script>

<script type="text/javascript">
        //<![CDATA[
        var l_uncheckall="Tout décocher";
        var l_checkall="Tout cocher";
        var l_logout="Êtes-vous sûr de vouloir vous déconnecter?";
        var l_ajaxerror="Il y a un problème avec la requête. Contactez l'administrateur SVP.";
        var l_ajaxerror2="Impossible de créer une instance XMLHTTP.";
        var l_updateerror = "Il y a eu une erreur pendant la mise à jour.\n\nMessage ERREUR:\n-----------------------------------\n";
        var l_pleasewait="Patientez ...";
        var l_ff="Netscape 6 ou Mozilla est nécessaire !";
        var l_newreply = "Répondre au message";
        //]]>
</script>

<script type="text/javascript">
        //<![CDATA[
        var iv = "no";
        function showLoginBox(boxname)
        {
                if (iv == "reCAPTCHA" || iv == "AdsCaptcha")
                {
                        window.location="login.php?";
                }
                else
                {
                        if (TSGetID(boxname).style.display == "none")
                        {
                                ts_show(boxname);
                                TSGetID("usernameloginphp").focus();
                        }
                        else
                        {
                                ts_hide(boxname);
                        }
                }
        }

        jQuery(document).on("click", "#closebar", function(e)
        {
                jQuery("#topbar").hide();
        });

        jQuery(document).ready(function()
        {
                var $topbar = jQuery("#topbar");

                $topbar.show();

                jQuery(window).scroll(function()
                {
                        $topbar.stop().animate({"marginTop": (jQuery(window).scrollTop() + 3) + "px"}, "slow" );
                });
        });
        //]]>
</script>
</head>
<body class="yui-skin-sam">
<div id="topbar" class="subheader">
        <img src="https://elite-tracker.net/images/close.gif" border="0" alt="" class="middle pointer" id="closebar" style="vertical-align: middle;" />
        Vous n'êtes pas enregistré, SVP veuillez vous <a href="https://elite-tracker.net/signup.php?"><u>ENREGISTRER</u></a> ou vous<a href="https://elite-tracker.net/login.php?"><u>connecter</u></a> pour avoir accès
        <div id="loginbox" style="display: none; padding-top: 5px;">
                <form method="post" action="https://elite-tracker.net/takelogin.php">
                <table style="width: 99%; border:0" width="99%" cellpadding="2" cellspacing="0">
                        <tr><td class="none" align="right">Pseudo:</td><td class="none"><input type="text" name="username" id="usernameloginphp" class="inputUsername" value="" /></td></tr>
                        <tr><td class="none" align="right">Mot de passe:</td><td class="none"><input type="password" name="password" class="inputPassword" value="" /></td></tr>


                        <tr><td class="none"></td><td class="none"><input type="submit" value="Connexion" style="vertical-align: middle;" /> <input type="reset" value="RESET" style="vertical-align: middle;" /></td></tr>
                </table>
                </form>
        </div>
</div>

<div class="content">
        <div id="top">
                <div class="top_text">

                        Récupérer votre mot de passe: <a href="https://elite-tracker.net/recover.php">via Email</a> | <a href="https://elite-tracker.net/recoverhint.php">via Question</a> | <a href="https://elite-tracker.net/login.php">LOGIN</a>

                </div>
                <div class="padding" align="center"></div>
</div>
<div id="header">

</div>
<div id="subheader">
<div id="menu">
        <!-- START TSSE MENU -->
        <ul class="TSSEMenu TSSEMenum">
                <li class="TSSEMenui"><a class="TSSEMenui" href="https://elite-tracker.net/">Accueil</a></li>
                                                                                                                                                                                        </ul>
<!-- END TSSE MENU --></div>
</div>
<div id="main">
        <div class="left_side">

        <script type="text/javascript">
                function ts_show_tag(id, status)
                {
                        if (TSGetID(id)){if (status == true || status == false){TSGetID(id).style.display = (status == true)?"none":"";}
                        else{TSGetID(id).style.display = (TSGetID(id).style.display == "")?"none":"";}}
                }
        </script>
        <div class="notification-border-e" id="notification_5e5ec991078992b19dbcfa477ed69bf2" align="center">
                <table class="notification-th-e" border="0" cellpadding="2" cellspacing="0">
                        <tbody>
                                <tr>
                                        <td align="left" width="100%" class="none">
                                        &nbsp;<span class="notification-title-e">Une erreur s'est produite!</span>
                                        </td>
                                        <td class="none"><img src="https://elite-tracker.net/include/templates/ET/images/notification_close.gif" alt="" onclick="ts_show_tag('notification_5e5ec991078992b19dbcfa477ed69bf2', true);" class="hand" border="0" height="13" width="13" /></td>
                                </tr>
                        </tbody>
                </table>
                <div class="notification-body">
                        <b>"404 - Url non trouvée." </b><br />
        La page que vous cherchez n'existe pas ou a été déplacée.<br />
        Vérifiez le lien (URL),
         il se peut aussi que celle-ci soit déplacée, mettre à jour vos favoris.
                </div>
        </div>
        <br />
        <br />
        </div>
        </div>
                <div id="footer">
                        <div class="padding">
                                Powered by <font color="white"><strong><a href="http://templateshares.net" target="_blank">TS Special Edition v.7.5</a></strong></font>  © 2020 <font color="white"><a href="https://elite-tracker.net" target="_self"><strong>Elite-Tracker</strong></a></font>
                                [Executed in <b> 0.0141 </b>seconds]
                        </div>

                </div>
        </div>


<!-- TS Save User Stats Code -->
        <script type="text/javascript">
        <!--
                function TSwriteCookie()
                {
                        var today = new Date();
                        var the_date = new Date("December 31, 2023");
                        var the_cookie_date = the_date.toGMTString();
                        var the_cookie = "users_resolution="+ screen.width +"x"+ screen.height;
                        var the_cookie = the_cookie + ";expires=" + the_cookie_date;
                        document.cookie=the_cookie;
                }
                TSwriteCookie();
        //-->
        </script>
        <img src="https://elite-tracker.net/staffcp/save_stats.php?rand=1581281130" alt="" title="" width="1" height="1" border="0" />
<!-- TS Save User Stats Code -->


        <div style="height: 25px; width: 100%; position: fixed; background-color:#E6E6E6; color:#FFFFFF;  background-image:url(https://elite-tracker.net/include/templates/ET/images/thead.png); z-index: 11000; border-top: 1px solid #333333; left:0; right: 0; bottom: 0; ">
        <img  id="start_button" style="position: absolute; left: 5px; bottom: 3px; cursor:pointer" src="/include/templates/ET/images/avatar_skin.png" width="37" height="35" alt="image-skin" />
                <form action="/browse.php" method="post"  name="search" style="margin: 2px 0 0 50px; float: left ">
                        <div>
                                <input name="do" value="search" type="hidden"/><input name="search_type" value="t_name" type="hidden" />
                                <input name="category" value="0" type="hidden" /><strong>Rechercher</strong>
                                <input name="keywords" size="20" type="text" />
                                <input name="go" type="submit" value="GO !" style="15px; font-size: 10px;" />
                        </div>
                </form>
                <div style="float: right">
                        <form method="post" action="/usercp.php?act=edit_theme_language&amp;do=save_theme_language" style="margin: 2px 20px 0 20px;">
                                <input type="hidden" name="act" value="edit_theme_language" />
                                <input type="hidden" name="do" value="save_theme_language" />
                                THEME
                                <select onchange="this.form.submit()" name="stylesheet" id="specialboxs">
                                <option value="" style="padding: 0 5px 0 5px; font-weight: bold" selected="selected">Choisir un theme</option>
                                <option value="Halloween">Halloween</option>
                                <option value="xbox360">xbox360</option>
                                <option value="PS3">PS3</option>
                                <option value="default">default</option>
                                <option value="Noel">Noel</option>
                                <option value="Elitebook">Elitebook</option>
                                </select>
                        </form>
                </div>
        </div>





</body>
</html>
```

Looking quickly at the code, I find quite odd that you only use eth0 interface... Am I missing something ? My openvpn connection is using tun0 interface :
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.107  netmask 255.255.255.0  broadcast 192.168.0.255
        inet6 fe80::c7:b333:3404:1ebf  prefixlen 64  scopeid 0x20<link>
        inet6 fe80::1a7c:ca11:e5c4:5c9e  prefixlen 64  scopeid 0x20<link>
        ether 00:1e:06:32:73:c3  txqueuelen 1000  (Ethernet)
        RX packets 139533  bytes 56893896 (56.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 144927  bytes 149257993 (149.2 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 622357  bytes 466910350 (466.9 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 622357  bytes 466910350 (466.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 10.0.0.81  netmask 255.255.255.255  destination 10.0.0.82
        inet6 fe80::572f:7006:e9a7:9e87  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 100  (UNSPEC)
        RX packets 71  bytes 47887 (47.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 91  bytes 10215 (10.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

**Comment by arvidn** [comment]
what's odd there is that `10.0.0.37` doesn't seem to be one of your IP addresses. did you run `ifconfig` as your `vpn` user there?

I take it you didn't change which interface/IP you listen on, right? so it should be `0.0.0.0:0,[::]:0`.

**Comment by skuizy** [comment]
I'm sorry, I  didn't picked up the right logs.

I thought IFaceWatch had already updated the config.

Anyway, I re-ran checks this morning and results are the same :
```
08:23:00.121 [DEBUG   ][deluge.core.alertmanager            :130 ] add_torrent_alert: added torrent: my_torrent
08:23:00.121 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_added_alert: my_torrent added
08:23:00.124 [INFO    ][deluge.core.torrentmanager          :672 ] Torrent my_torrent from user "localclient" added
08:23:00.422 [DEBUG   ][deluge.core.alertmanager            :130 ] state_changed_alert: my_torrent: state changed to: downloading
08:23:00.423 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_checked_alert: my_torrent checked
08:24:56.231 [DEBUG   ][deluge.core.alertmanager            :130 ] save_resume_data_alert: my_torrent resume data generated
08:37:28.227 [DEBUG   ][deluge.core.alertmanager            :130 ] add_torrent_alert: added torrent: my_torrent
08:37:28.227 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_added_alert: my_torrent added
08:37:43.805 [INFO    ][deluge.core.torrentmanager          :672 ] Torrent my_torrent from user "localclient" loaded
08:38:32.779 [DEBUG   ][deluge.core.alertmanager            :130 ] state_changed_alert: my_torrent: state changed to: downloading
08:38:32.780 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_checked_alert: my_torrent checked
08:38:56.611 [DEBUG   ][deluge.core.alertmanager            :130 ] torrent_resumed_alert: my_torrent resumed
08:38:56.612 [DEBUG   ][deluge.core.alertmanager            :130 ] tracker_announce_alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.81:64270] sending announce (started)
08:39:01.297 [DEBUG   ][deluge.core.alertmanager            :130 ] tracker_error_alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.81:64270] Invalid argument "" (1)
08:39:09.809 [DEBUG   ][deluge.core.torrentmanager          :1393] Tracker Error Alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.81:64270] Invalid argument "" (1) [Invalid argument]
08:39:11.143 [DEBUG   ][deluge.core.alertmanager            :130 ] tracker_announce_alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.81:64270] sending announce (started)
08:39:12.216 [DEBUG   ][deluge.core.alertmanager            :130 ] tracker_error_alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.81:64270] No route to host "" (2)
08:39:14.905 [DEBUG   ][deluge.core.torrentmanager          :1393] Tracker Error Alert: my_torrent (https://elite-tracker.net/announce.php?passkey=my_passkey)[10.0.0.81:64270] No route to host "" (2) [No route to host]
```

**Comment by arvidn** [comment]
@skuizy thanks! would it be possible for you to post the routing table for your `vpn` user too? The routing table is used to determine whether an interface can reach an IP. the "No route to host" suggests that that logic determines that the `10.0.0.81` interface cannot reach the IP address of `elite-tracker.net`.

If you're already building libtorrent yourself, in the `test` directory there's a tool called `enum_if` that prints the routing table, the interfaces and all important properties. Otherwise (on linux), you can run `netstat -r -n`.

I don't understand where the invalid argument comes from. This is linux, right? At first I was thinking it could be that the tracker hostname resolves to an IPv6 address, but then I would have expected an "address family not supported".

**Comment by skuizy** [comment]
Thanks, I think the invalid argument thing comes from my VPN as I have 1600+ torrents that get resumed at once, it might be a liltle too much... But they should be ok at the next anounce.

As stated before, I'm using the daily bulid from launchpad, so I don't have acces to enum_if. But of course as it's a linux (`Ubuntu 19.10 Linux odroid 4.14.157+ #1 SMP PREEMPT Sat Jan 4 16:40:31 CET 2020 armv7l armv7l armv7l GNU/Linux`) I ran the `netstat -r -n` command :
```
[~]$ netstat -r -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 eth0
10.0.0.82       0.0.0.0         255.255.255.255 UH        0 0          0 tun0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
[~]$ sudo -u vpn netstat -r -n
[sudo] password for odroid:
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 eth0
10.0.0.82       0.0.0.0         255.255.255.255 UH        0 0          0 tun0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
```
But it doesn't show everything, so I used `ip route list` for both my default table and my vpn table :
```
[~]$ ip route list
default via 192.168.0.1 dev eth0 src 192.168.0.107 metric 202
10.0.0.82 dev tun0 proto kernel scope link src 10.0.0.81
169.254.0.0/16 dev eth0 scope link metric 1000
192.168.0.0/24 dev eth0 proto dhcp scope link src 192.168.0.107 metric 202
[~]$ ip route list table vpn
default via 10.0.0.82 dev tun0
default via 127.0.0.1 dev lo
```

**Comment by arvidn** [comment]
I think this is the relevant part:

```
[~]$ sudo -u vpn netstat -r -n
[sudo] password for odroid:
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.0.1     0.0.0.0         UG        0 0          0 eth0
10.0.0.82       0.0.0.0         255.255.255.255 UH        0 0          0 tun0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth0
192.168.0.0     0.0.0.0         255.255.255.0   U         0 0          0 eth0
```

Your default route does not seem to go over the tunnel, but to `eth0`. Are you specifying `tun0` as your listen interface?

**Comment by arvidn** [comment]
basically, from what I can see so far, libtorrent is right in determining that the `10.0.0.81` is not connected to the internet (it doesn't have a gateway). However, maybe my problem is that I don't interpret point-to-point interfaces correctly.

**Comment by skuizy** [comment]
Well as I read it, you need to use the default gateway to reach 10.0.0.82. That doesn't seems wrong to me as finaly everything will go through this interface.... 

It used to work for a long time, I don't think it was related to chance... But I didn't save the  .deb to rollback... Are the launchpad packages archived somewhere ?

Finally, other applications can connect to internet just fine using the vpn connection as stated in https://github.com/arvidn/libtorrent/pull/4320#issuecomment-583892607

I can verify it works when issuing these commands :
```
[~]$ dig +short myip.opendns.com @resolver1.opendns.com
89.156.xxx.xxx
[~]$ sudo -u vpn dig +short myip.opendns.com @resolver1.opendns.com
185.128.xxx.xxx

```

**Comment by arvidn** [comment]
I don't doubt that I'm wrong (especially since you can demonstrate it working). I'm reading up on this.

However, your log seems to suggest that you're *only* listening to `10.0.0.81`. How come? Why aren't you also listening to `192.168.0.107`. Do you set the listen interface to anything other than default? Do you set it to the name of the interface (`utun0`) or do you set it to the specific IP address?

Currently the way libtorrent determines whether there is a router or not is by looking at the device name of the listen socket. So, `10.0.0.81` has `utun0` as the device. Then it looks for a default route table entry for *that device*. A default route is one where the destination is `0.0.0.0`. I don't see why the kernel wouldn't end up using the source IP `192.168.0.107` if it would go to out over `eth`

**Comment by skuizy** [comment]
The problem is that by using the netstat command, you only get the default routing table, not other ones. In this case, I agree that it's not possible to use the VPN connection, and I'm fine with it since I only want my VPN user to go through this connection, so i'v set-up a split tunelling with openvpn. But when using ip route command, you can see that my default route goes via the tun0 interface or via the loopback as a kill switch.

That's why my IFaceWatch plug-in is monitoring the network address of my tun0 interface only and setting this address as the listen address of the deluge deamon.

**Comment by arvidn** [comment]
I'm still curious to know what you set your listen IP to. I suspect it's either `utun0` or `10.0.0.81` (plus a port), is that right?

*if so*, I would expect this to work if you restore it to default (which is `0.0.0.0:<port>,[::]:<port>`)

**Comment by arvidn** [comment]
```
$ sudo -u vpn netstat -r -n
```

This would show the routing table of the `vpn` user though, right?

**Comment by skuizy** [comment]
> 
> 
> I'm still curious to know what you set your listen IP to. I suspect it's either `utun0` or `10.0.0.81` (plus a port), is that right?
> 
> _if so_, I would expect this to work if you restore it to default (which is `0.0.0.0:<port>,[::]:<port>`)

Sorry, I thought I answered. My listen IP is 10.0.0.81, howerver I dont specify the port, it's on random.



> 
> 
> ```
> $ sudo -u vpn netstat -r -n
> ```
> 
> This would show the routing table of the `vpn` user though, right?

Nope, because routing tables aren't user dependent : packets from this user are marked by iptables and then, all makred packets are routed through the corresponding table as it's described here : https://ubuntuforums.org/showthread.php?t=2383121&p=13732611#post13732611

I don't know why netstat doesn't theses other table tho, but as it's deprecated, I never learned to use it, I use ip instead.

**Comment by arvidn** [comment]
thanks for baring with me. I clearly have some more reading to do on how this all works. I would hope, though, that the routing table libtorrent sees via the `PF_ROUTE`/`NETLINK_ROUTE` socket is the one that's actually used. It's run by the same user.

The other tools that you demonstrate to work *don't* bind to `10.0.0.81` (afaict), and I bet they end up using the other interface and route. Do you think it would be a problem to listen to `0.0.0.0:0`? it would resolve to both IPs, but the `10.0.0.81` interface wouldn't be able to route to anything, so it would effectively not be used.

**Comment by arvidn** [comment]
if it works for you if you do not change the `listen_interfaces` setting from the default, I don't think there's anything I need to fix.

If using the default `listen_interfaces` *still* doesn't work, I will definitely have to fix it. I would be interested in more details of how it fails in that case though.

**Comment by skuizy** [comment]
> Do you think it would be a problem to listen to `0.0.0.0:0`? it would resolve to both IPs, but the `10.0.0.81` interface wouldn't be able to route to anything, so it would effectively not be used.

Well in this case it would completly defeate the purpose of the vpn... So it wouldn't be a soultion...

The last build I could grab from launchpad was 6a88ffc+202001261233 and was already broken.

The version in Ubuntu repo works, but it's 1.1.13-1... I don't think think this is relevant considering how old this release is...

I see a lot of changes were made in the way libtorrent handles connection since 1.2.3. Would it be possible to request a build from this version to compare/benchmark against 1.2.4 ?

**Comment by arvidn** [comment]
given that `dig` in your example command line above wasn't explicitly bound to `10.0.0.81` and it worked, I don't think it would be a problem. You could always try this:

http://checkmyip.torrentprivacy.com/

**Comment by skuizy** [comment]
Well after running some more tests this weekend by your comments, I had the folowing results :

I reverted my listen interface to the default one and it seems to be working, routing my traffic through my vpn. It's quite a logic change compared to previous revisions tho as I had to set my listen interface to my vpn address to make it work

I also reran the dig command, binding to my vpn address this time and it is resolving as expected :
```
[~]$ sudo -u vpn dig +short myip.opendns.com @resolver1.opendns.com -b 10.0.0.81
185.128.xxx.xxx
```

I see you made a new PR about the routing stuff, unfortunately I cannot build LT, so I'll have to wait until it makes it to the master and gets picked by the build bot or until someone builds it for armhf or amd64 to try it.

**Pull request merged**
