### PR TITLE
fix similar torrents feature for v2 torrents

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by master255** [comment]
@arvidn I don't know, does that apply to [my question? ](https://github.com/arvidn/libtorrent/issues/6578#issuecomment-1024952740)

**Comment by arvidn** [comment]
@master255 I don't think it does

**Comment by master255** [comment]
@arvidn This is very bad.

**Comment by arvidn** [comment]
how so?

**Comment by master255** [comment]
@arvidn Maybe I don't understand something?
I asked - it's relevant to my question
You answered: No, it doesn't.
I wrote: it's very bad.
Unexpected response: how so? - What do you mean by that?

**Comment by arvidn** [comment]
You're saying there's something wrong (or "bad") with this patch. I'm curious what, specifically, is bad about it.

**Comment by master255** [comment]
@arvidn I'm saying it's too bad this patch doesn't solve my issue. I haven't looked at the patch code in detail and don't understand what it does.

**Pull request merged**
