### PR TITLE
more boost types cleanup and handling of deprecated macos libcrypto

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
lgtm. it would be nice to get rid of some of those blobs of disabling warnings on mac. maybe I'll look into using the native API for hashing at least

**Comment by aldenml** [comment]
I believe you already use the native API (built-in), but if you use the embedded openssl in macOS, that's the problem, because is outdated, deprecated and unmaintained :)

**Comment by arvidn** [comment]
oh.. but wouldn't it make sense to leave those warnings around then? My understanding is that boost.asio only supports libssl for its TLS support, so those uses would have to be wrapped, but not anything else.

**Comment by aldenml** [comment]
well...hmm....thinking about it...I suppose that for a while clients should be able to use the embedded openssl, they should be aware of the shortcomings, but at the same time be able to compile warnings free without adding `-Wno-deprecated-declarations`.

**Pull request merged**
