### PR TITLE
refactor to use the utility function for bind_socket_to_device()

### PR DESCRIPTION
**Pull request by arvidn**
instead of using the bind_to_device socket option directly, to make it best effort.

### CODE REVIEW

**Comment by ssiloti** [comment]
The behavior of `bind_socket_to_device` when bind_to_device fails is not what we want here. For listen sockets `bind_ep` has already been selected in `reopen_listen_sockets`. To use `bind_socket_to_device` here it needs to be able to take `bind_ep` as a parameter.

**Comment by arvidn** [comment]
@evsh I'm eager to hear back :)

**Comment by evsh** [comment]
The patch did not help, there is no download activity.

**Comment by arvidn** [comment]
Interesting. Any relevant error alerts? Bind to device failures shouldn’t prevent the socket from being opened now. However, even if the listen sockets were failing earlier, outgoing sockets should still have allowed for downloading. I suppose the outgoing sockets really are the main problem.

Do you have any observations that hint of what’s going on?

**Comment by arvidn** [comment]
(Please double check you ended up applying and linking the patched binary correctly too)

**Comment by evsh** [comment]
The log contains:
```
listening on <correct ipv4 address>:6881 (device: tun0) failed: [sock_bind] [UDP] Operation not permitted
listening on [<correct ipv6 address>%tun0]:6881 (device: tun0) failed: [sock_bind] [UDP] Operation not permitted
UDP error: Operation not permitted from: <correct ipv4 address>
UDP error: Operation not permitted from:<correct ipv6 address>%tun0
UDP error: Operation not permitted from: <correct ipv4 address>
UDP error: Operation not permitted from: <correct ipv6 address>%tun0
```
Downloading starts if I pass outgoing interface only; console output contains the same error messages.

> (Please double check you ended up applying and linking the patched binary correctly too)

Not sure what did you mean here, but I need to just drop a file with patch into a predefined directory, and the Gentoo package management system applies it when building and installing a package. It reports back that that the patch was applied.

Does the `client.py -i <interface name> -o <interface name>` work for you?

**Comment by evsh** [comment]
`client.py -o <interface name>` (omitting the listen_interfaces option) make it work.

**Comment by evsh** [comment]
> I could hard-code it to fail and see what happens I suppose.

I would appreciate that.

**Comment by arvidn** [comment]
it's interesting that you get those `UDP Error:` messages. That suggests that it's not just the socket option that fails, but subsequent attempts to read from the socket also fail.

**Comment by arvidn** [comment]
oh, also. It's not the `BIND_TO_DEVICE` socket option that's failing. it's `bind()`.

**Comment by arvidn** [comment]
please test again now

**Comment by evsh** [comment]
It works! I'm very grateful!

**Pull request merged**
