### PR TITLE
fix example of custom storage

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by latot** [comment]
Hi, i'm checking this, sadly (i dont' know to much about c++) there is something i don't understand, to use a custom storage we need send a ```file_storage``` too, but that means with every torrent file we need initialize the custom storage with it, but with the default storege (my suposition) the ```file_storage``` is loaded from libtorrent, why ```file_storage``` need to be loaded manually there?

Thx!

**Comment by latot** [comment]
Hi, for now here is the erros, i change a little the example ```simple_client``` to works with this and test:

```
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp:81:7: error: conflicting return type specified for ‘virtual bool temp_storage::rename_file(libtorrent::file_index_t, const string&, libtorrent::storage_error&)’
  bool rename_file(file_index_t file, std::string const& new_name, storage_error& ec) override
       ^~~~~~~~~~~
In file included from /home/pipe/Documentos/git/libtorrent/include/libtorrent/disk_io_thread.hpp:39:0,
                 from /home/pipe/Documentos/git/libtorrent/include/libtorrent/session_handle.hpp:41,
                 from /home/pipe/Documentos/git/libtorrent/include/libtorrent/session.hpp:41,
                 from /home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp:36:
/home/pipe/Documentos/git/libtorrent/include/libtorrent/storage.hpp:274:16: error:   overriding ‘virtual void libtorrent::storage_interface::rename_file(libtorrent::file_index_t, const string&, libtorrent::storage_error&)’
   virtual void rename_file(file_index_t index, std::string const& new_filename
                ^~~~~~~~~~~
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp:84:62: error: cannot convert ‘bool’ to ‘libtorrent::status_t’ in return
   , move_flags_t flags, storage_error& ec) override { return false; }
```

Bye!

**Comment by arvidn** [comment]
> Hi, i'm checking this, sadly (i dont' know to much about c++) there is something i don't understand, to use a custom storage we need send a `file_storage` too

are you talking about the `storage_interface` constsructor taking a `file_storage`?

You're just supposed to pass it on from the factory function, like in the example:

```
storage_interface* temp_storage_constructor(storage_params const& params)
{
  return new temp_storage(*params.files);
}
```

and the `temp_storage` constructor passes it on:

```
temp_storage(file_storage const& fs) : storage_interface(fs) {}
```

**Comment by arvidn** [comment]
@latot btw, I fixed the return value from `rename_file()` in the docs too

**Comment by latot** [comment]
Hi Tnks!, sorry check this too slow, i have more things to do this two days than the week.

**Comment by latot** [comment]
Hi sadly keep failing some parts:

```
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp: In function ‘libtorrent::storage_interface* {anonymous}::temp_storage_constructor(const libtorrent::storage_params&)’:
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp:107:27: error: no match for ‘operator*’ (operand type is ‘const libtorrent::file_storage’)
   return new temp_storage(*params.files);
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp: In member function ‘virtual libtorrent::status_t {anonymous}::temp_storage::move_storage(const string&, libtorrent::move_flags_t, libtorrent::storage_error&)’:
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp:94:63: error: cannot convert ‘bool’ to ‘libtorrent::status_t’ in return
    , move_flags_t flags, storage_error& ec) override { return false; }
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp: In member function ‘virtual void {anonymous}::temp_storage::rename_file(libtorrent::file_index_t, const string&, libtorrent::storage_error&)’:
/home/pipe/Documentos/git/libtorrent/examples/simple_client.cpp:92:27: error: return-statement with a value, in function returning 'void' [-fpermissive]
   { assert(false); return false; }
```

I'm thinking would be better move the examples in the doc to code or tests, and write in what part of the code they are, so when there is change the docs can be update proporly.

Thx!

**Comment by latot** [comment]
and change:
```
	storage_interface* temp_storage_constructor(storage_params const& params)
```
to
```
	storage_interface* temp_storage_constructor(storage_params const& params, file_pool&)
```
Thx!

**Comment by arvidn** [comment]
you're right. This example is complex enough to warrant it being built by CI

**Comment by arvidn** [comment]
this should fix it once and for all. The custom storage example is now compiled on CI (in `examples/custom_storage.cpp`)

**Comment by latot** [comment]
some test are still failing, seems to be almost done!

Thx!

**Comment by latot** [comment]
Thx!

**Pull request merged**
