### PR TITLE
fix regression in windows implementation of enum_net causing infinite loop

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
is this needed in `master` too?

**Comment by arvidn** [comment]
I think so. once I land this I will merge forward

**Comment by ajax16384** [comment]
master's loop implementatoin has no such regression

**Comment by ajax16384** [comment]
master:
````c++
				IP_ADAPTER_UNICAST_ADDRESS* unicast = adapter->FirstUnicastAddress;
				while (unicast)
				{
					if (valid_addr_family(unicast->Address.lpSockaddr->sa_family))
					{
						r.interface_address = sockaddr_to_address(unicast->Address.lpSockaddr);
						ret.push_back(r);
					}
					unicast = unicast->Next;
				}
````
RC_1_1
````c++
				IP_ADAPTER_UNICAST_ADDRESS* unicast = adapter->FirstUnicastAddress;
				while (unicast)
				{
					if (unicast->Address.lpSockaddr->sa_family != AF_INET
#if TORRENT_USE_IPV6
						&& unicast->Address.lpSockaddr->sa_family != AF_INET6
#endif
					)
						continue;

					r.interface_address = sockaddr_to_address(unicast->Address.lpSockaddr);

					ret.push_back(r);

					unicast = unicast->Next;
				}
````

**Comment by arvidn** [comment]
I turned both into a for-loop

**Pull request merged**
