### PR TITLE
Use UTF-8 encoding for messages coming from boost on Windows 

### PR DESCRIPTION
**Pull request by Chocobo1**
* Use UTF-8 encoding for messages coming from boost on Windows
  Previously it was using the system default locale encoding.
  https://www.boost.org/doc/libs/1_78_0/libs/system/doc/html/system.html#ref_macros
* Remove redundant compiler warning flag
  The flag is already implied by `-Wall`.

### CODE REVIEW

**Review by arvidn — APPROVED** [review]

**Comment by arvidn** [comment]
this patch enables https://github.com/arvidn/libtorrent/pull/6669

**Comment by stalkerok** [comment]
> * Use UTF-8 encoding for messages coming from boost on Windows
>   Previously it was using the system default locale encoding.

This is a bad change. If you can do without it, it's best not to use it.

**Comment by Chocobo1** [comment]
> This is a bad change. If you can do without it, it's best not to use it.
> 

Is it a screenshot of qbt?
If so, then it is better to patch up qbt instead IMO.

**Comment by stalkerok** [comment]
Yes, this is a screenshot from qbt.
If this can be done in qbt, then I'll close the PR.

**Pull request merged**
