### PR TITLE
fix regression in left= reporting to trackers when adding a seeding t…

### PR DESCRIPTION
**Pull request by arvidn**
…orrent

### CODE REVIEW

**Comment by an0n666** [comment]
Can this be backported to RC1_1? I’m facing similar issue with libtorrent 1.1.14. 
After restart, seeding torrent doesn’t report left = 0. Have to stop and start to make it work again.

**Comment by arvidn** [comment]
@arvidn do you know if the patch applies cleanly to `RC_1_1`?

**Comment by arvidn** [comment]
if it does, I imagine it would be simple to back-port. Testing might be trickier though.
If it doesn't apply cleanly, there's a risk that the issue you experience is caused by something else (but not necessarily)

**Comment by an0n666** [comment]
Sorry I think it's a different issue.

**Pull request merged**
