### PR TITLE
update required boost version and ax_boost_base.m4

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@cas-- does this seem reasonable?

**Comment by arvidn** [comment]
tested to work on osx with homebrew

**Comment by arvidn** [comment]
ping @cas--

**Comment by cas--** [comment]
It looks to me as though can actually drop the check for atomic. I removed the atomic lib packages and libtorrent build fine with the just header file available.

I am testing again with the debian build but I expect the same outcome.

**Comment by arvidn** [comment]
thanks for looking into this

**Pull request merged**
