### PR TITLE
[clang-tidy] remove bad const

### PR DESCRIPTION
**Pull request by neheb**
Found with performance-no-automatic-move

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by arvidn** [comment]
does this fix all reports from `performance-no-automatic-move`? if so, would you mind adding it to the clang-tidy command line on travis CI as well?

**Comment by neheb** [comment]
I think so.

**Comment by neheb** [comment]
Actually why is clang-tidy ran with the options manually? It looks for a .clang-tidy file automatically.

**Comment by arvidn** [comment]
no strong reason. it's simple and one less file in the root of the repository.

**Pull request merged**
