### PR TITLE
use a newer iconv.m4 script

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by Chocobo1** [comment]
Looks like you can get a more up-to-date version here: https://github.com/autotools-mirror/gettext/blob/master/gettext-runtime/m4/iconv.m4

**Comment by Chocobo1** [comment]
BTW, other scripts in the m4 folder are also largely outdated, you mind updating them too, or do you mind I submit a pull request?
Also how long do you plan to keep autotools around since you have cmake build system already?

**Comment by arvidn** [comment]
A pull request would be welcome!

**Comment by arvidn** [comment]
autotools have been removed in 2.0 (so next major release)

**Pull request merged**
