### PR TITLE
fix dht tests

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@aldenml does this look reasonable?

**Comment by aldenml** [comment]
Hi @arvidn, I created a function in `test_dht_storage` https://github.com/arvidn/libtorrent/blob/master/test/test_dht_storage.cpp#L87, maybe you can put it in a common place or just copy it in `test_dht`.

note: see my merge RC_1_1 comment before merge this.

**Comment by arvidn** [comment]
this is the failure I got that started all this:

file: '../src/kademlia/node_id.cpp'
line: 74
function: int libtorrent::dht::min_distance_exp(const node_id &, const std::vector<node_id> &)
expression: ids.size() > 0

```
  * frame #0: 0x00007fff8a29f8ea libsystem_kernel.dylib`__kill + 10
    frame #1: 0x0000000100e98377 test_primitives`assert_fail(expr="ids.size() > 0", line=74, file="../src/kademlia/node_id.cpp", function="int libtorrent::dht::min_distance_exp(const node_id &, const std::vector<node_id> &)", value=0x0000000000000000, kind=0) + 375 at assert.cpp:349
    frame #2: 0x00000001014f7f1d test_primitives`libtorrent::dht::min_distance_exp(n1=0x00007fff5fb881c0, ids=0x00000001026000f0) + 125 at node_id.cpp:74
    frame #3: 0x00000001014bc528 test_primitives`libtorrent::dht::(anonymous namespace)::immutable_item_comparator::operator(this=0x00007fff5fb87eb0, lhs=0x00007fff5fb881c0, rhs=0x00007fff5fb88110)(std::__1::pair<libtorrent::sha1_hash, libtorrent::dht::(anonymous namespace)::dht_immutable_item> const&, std::__1::pair<libtorrent::sha1_hash, libtorrent::dht::(anonymous namespace)::dht_immutable_item> const&) const + 40 at dht_storage.cpp:162
    frame #4: 0x00000001014bbe69 test_primitives`std::__1::map<libtorrent::sha1_hash, libtorrent::dht::(anonymous namespace)::dht_immutable_item, std::__1::less<libtorrent::sha1_hash>, std::__1::allocator<std::__1::pair<libtorrent::sha1_hash const, libtorrent::dht::(anonymous namespace)::dht_immutable_item> > >::const_iterator libtorrent::dht::(anonymous namespace)::pick_least_important_item<libtorrent::dht::(anonymous namespace)::dht_immutable_item>(std::__1::vector<libtorrent::sha1_hash, std::__1::allocator<libtorrent::sha1_hash> > const&, std::__1::map<libtorrent::sha1_hash, libtorrent::dht::(anonymous namespace)::dht_immutable_item, std::__1::less<libtorrent::sha1_hash>, std::__1::allocator<std::__1::pair<libtorrent::sha1_hash const, libtorrent::dht::(anonymous namespace)::dht_immutable_item> > > const&) + 834 at algorithm:2561
    frame #5: 0x00000001014bbb27 test_primitives`std::__1::map<libtorrent::sha1_hash, libtorrent::dht::(anonymous namespace)::dht_immutable_item, std::__1::less<libtorrent::sha1_hash>, std::__1::allocator<std::__1::pair<libtorrent::sha1_hash const, libtorrent::dht::(anonymous namespace)::dht_immutable_item> > >::const_iterator libtorrent::dht::(anonymous namespace)::pick_least_important_item<libtorrent::dht::(node_ids=0x00000001026000f0, table=0x0000000102600120)::dht_immutable_item>(std::__1::vector<libtorrent::sha1_hash, std::__1::allocator<libtorrent::sha1_hash> > const&, std::__1::map<libtorrent::sha1_hash, libtorrent::dht::(anonymous namespace)::dht_immutable_item, std::__1::less<libtorrent::sha1_hash>, std::__1::allocator<std::__1::pair<libtorrent::sha1_hash const, libtorrent::dht::(anonymous namespace)::dht_immutable_item> > > const&) + 599 at dht_storage.cpp:189
    frame #6: 0x00000001014b2ab1 test_primitives`libtorrent::dht::(anonymous namespace)::dht_default_storage::put_immutable_item(this=0x00000001026000d0, target=0x00007fff5fb89200, buf="d1:A1:a1:B1:b4:next20:c[�\x1b\x16��W��\x1f\x89o\vo�x9:num_peersi3eee1:q3:put1:t2:101:y1:qe", size=57, addr=0x00007fff5fb89178) + 705 at dht_storage.cpp:372
    frame #7: 0x00000001014e7a0e test_primitives`libtorrent::dht::node::incoming_request(this=0x00007fff5fbfe350, m=0x00007fff5fb8a868, e=0x00007fff5fb8a598) + 9214 at node.cpp:1047
    frame #8: 0x00000001014e5014 test_primitives`libtorrent::dht::node::incoming(this=0x00007fff5fbfe350, m=0x00007fff5fb8a868) + 1908 at node.cpp:321
    frame #9: 0x0000000100b16a83 test_primitives`send_dht_request(node=0x00007fff5fbfe350, msg="put", ep=0x00007fff5fbf694c, reply=0x00007fff5fb8c980, args=0x00007fff5fb8ee90, t="10", has_response=true) + 2627 at test_dht.cpp:232
    frame #10: 0x0000000100b1bf0f test_primitives`announce_immutable_items(node=0x00007fff5fbfe350, eps=0x00007fff5fbf6930, items=0x00007fff5fbf66b0, num_items=8) + 15967 at test_dht.cpp:350
```

**Comment by aldenml** [comment]
Thank you, I moved here :) I'm looking at the code right now

**Comment by aldenml** [comment]
@arvidn I believe I found what was happening. The following line in Jamfile
```
LN 699: <variant>debug:<define>TORRENT_DEBUG
```
is correct, but when one specify `variant=test_debug` in the command line is not like it works "magically" due to the line
```
LN 495: variant test_debug : debug
```
The net result is that `TORRENT_DEBUG` wasn't defined and then `TORRENT_USE_ASSERTS` wasn't defined either.

If I specify `asserts=on` in the jam command line, this test reliably fails (as expected).

Not sure how do want to approach this, if adding the minimal code necessary or add the update node id everywhere (module the refactor I suggested).

**Comment by arvidn** [comment]
thanks! I've enabled asserts in the test build variants now

**Pull request merged**
