### PR TITLE
update our id in the rpc manager when it changes

### PR DESCRIPTION
**Pull request by ssiloti**

### CODE REVIEW

**Comment by arvidn** [comment]
oops, good catch! do you think it's easy to write a test for this? send a message, catch the outgoing node ID in the message, trigger a recalculation of node ID and send another message and catch it and make sure it's different.

This fix seems reasonable. I looked at where m_our_id is used and it's only in add_our_id(), which is called from two places. Once from node (which has the node ID already) and the other time from observers, which don't have our node ID normally. So I think it makes sense to have the rpc manager know the node id. An alternate fix would be to make its member a const reference to the parent's (node's) node ID.

This fix should also be mentioned in ChangeLog I think

**Comment by ssiloti** [comment]
I'll add a test in a separate PR to master since the DHT tests got massively refactored since 1.1.

**Comment by arvidn** [comment]
good point

**Comment by arvidn** [comment]
it's been merged into master

**Pull request merged**
