### PR TITLE
consolidate address family checking

### PR DESCRIPTION
**Pull request by ajax16384**
fix no IPV6 windows and netlink builds

### CODE REVIEW

**Comment by arvidn** [comment]
lgtm. I'm tempted to try changing the base to RC_1_1 in github. I don't know what will happen doing that though. Do you think it's likely to apply cleanly?

**Comment by ajax16384** [comment]
you want to backport it to RC_1_1 ?

**Comment by arvidn** [comment]
github has some scary language around rebasing. I would imagine no actual change will be committed to your clone still, and that it would be reversible.

**Comment by arvidn** [comment]
heh.. no, that didn't work very well :/

**Comment by arvidn** [comment]
I imagine this problem exists in RC_1_1 as well, yes.

**Comment by arvidn** [comment]
did you see this? https://travis-ci.org/arvidn/libtorrent/jobs/199398548#L902

**Comment by ajax16384** [comment]
will fix it

**Comment by ajax16384** [comment]
after this PR will be merged i will create PR for RC_1_1

**Pull request merged**
