### PR TITLE
using structured binding

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
Looks good. However, one of the benefits of structured bindings is that you can make the variables const. I think there may be a few missed opportunities for that.

**Comment by aldenml** [comment]
agree, do you want me to review every `auto [` for adding a `const`?

**Comment by arvidn** [comment]
At least the ones you just added. I'm pretty sure some of them can be const now (but couldn't earlier, when using tie)

**Comment by aldenml** [comment]
OK, added `const` when possible

**Pull request merged**
