### PR TITLE
WebTorrent: update libdatachannel to v0.18 (re-licensed to MPL 2.0)

### PR DESCRIPTION
**Pull request by paullouisageneau**
This PR updates the libdatachannel submodule to v0.18.1. 

The library has been re-licensed to MPL 2.0. It is a copyleft license more permissive than the LGPL which gets along better with the BSD license of libtorrent. In particular _the library can now be linked statically against proprietary applications without additional restrictions_.

There are no critical fixes corresponding to the usage in libtorrent but some enhancements and smaller bugfixes.

### CODE REVIEW

**Comment by paullouisageneau** [comment]
Sorry for the rebases, the Jamfile of libdatachannel was not properly updated with new defines so it could not link against the static library on Windows in the last AppVeyor build. The build is fixed now.

@arvidn The leftover failures look like spurious ones to me, is it the case?

**Comment by arvidn** [comment]
> @arvidn The leftover failures look like spurious ones to me, is it the case?

Yes, it looks like it.

**Comment by arvidn** [comment]
@paullouisageneau 
there's a new issue that appears to have been introduced with this change (but I'm not sure).

```
../deps/libdatachannel/src/impl/icetransport.cpp:288:35: runtime error: member call on misaligned address 0x7fd388678ae2 for type 'struct IceTransport', which requires 8 byte alignment
0x7fd388678ae2: note: pointer points here
 5f 5d  c3 90 f3 0f 1e fa 55 48  89 e5 41 57 41 56 41 55  41 54 53 48 81 ec 98 05  00 00 48 89 bd 68
```

I've also seen this:
```
../deps/libdatachannel/src/impl/icetransport.cpp:288:35: runtime error: member call on address 0x7fbd4ce8bda0 which does not point to an object of type 'IceTransport'
0x7fbd4ce8bda0: note: object has invalid vptr
 5f 5d c3 90  f3 0f 1e fa 55 48 89 e5  41 57 41 56 41 55 41 54  53 48 81 ec 98 05 00 00  48 89 bd 68
              ^~~~~~~~~~~~~~~~~~~~~~~
              invalid vptr
```

**Comment by arvidn** [comment]
the stack trace is for the misaligned address is:

```
#2  0x00007ffff6c0e11f in __ubsan::__ubsan_handle_type_mismatch_v1_abort (Data=<optimized out>, Pointer=<optimized out>) at ../../../../src/libsanitizer/ubsan/ubsan_handlers.cpp:147
#3  0x0000555565545b81 in rtc::impl::IceTransport::StateChangeCallback (state=4092892784, user_ptr=0x555565547ee6 <rtc::impl::IceTransport::RecvCallback(juice_agent*, char const*, unsigned long, void*)>)
    at ../deps/libdatachannel/src/impl/icetransport.cpp:288
#4  0x0000555565704b49 in agent_gather_candidates ()
#5  0x00005555656f7a9b in juice_gather_candidates ()
#6  0x0000555565542c4c in rtc::impl::IceTransport::gatherLocalCandidates (this=0x613000013450, mid="") at ../deps/libdatachannel/src/impl/icetransport.cpp:198
#7  0x00005555650285a7 in rtc::PeerConnection::setLocalDescription (this=0x604000013260, type=rtc::Description::Type::Offer) at ../deps/libdatachannel/src/peerconnection.cpp:146
#8  0x000055556502e160 in rtc::PeerConnection::createDataChannel (this=0x604000013260, label="", init=...) at ../deps/libdatachannel/src/peerconnection.cpp:264
#9  0x000055556342165a in libtorrent::aux::rtc_signaling::generate_offers(int, std::function<void (boost::system::error_code const&, std::__debug::vector<libtorrent::aux::rtc_offer, std::allocator<libtorrent::aux::rtc_offer> > const&)>) (this=0x613000012490, count=9, handler=...) at ../src/rtc_signaling.cpp:159
#10 0x0000555562751442 in libtorrent::aux::torrent::generate_rtc_offers(int, std::function<void (boost::system::error_code const&, std::__debug::vector<libtorrent::aux::rtc_offer, std::allocator<libtorrent::aux::rtc_offer> >)>) (this=0x61d000060490, count=10, handler=...) at ../src/torrent.cpp:6011
#11 0x0000555562ed3519 in libtorrent::aux::tracker_manager::queue_request (this=0x62600000d678, ios=..., req=..., sett=..., c=std::weak_ptr<libtorrent::aux::request_callback> (use count 6, weak count 7) = {...})
    at ../src/tracker_manager.cpp:318
#12 0x0000555561f26c7b in libtorrent::aux::session_impl::queue_tracker_request (this=0x62600000c110, req=..., c=std::weak_ptr<libtorrent::aux::request_callback> (use count 6, weak count 7) = {...})
    at ../src/session_impl.cpp:1274
#13 0x00005555626dc401 in libtorrent::aux::torrent::announce_with_tracker (this=0x61d000060490, e=libtorrent::event_t::none) at ../src/torrent.cpp:3214
#14 0x00005555628059e2 in libtorrent::aux::torrent::start_announcing (this=0x61d000060490) at ../src/torrent.cpp:9949
#15 0x00005555627c37fc in libtorrent::aux::torrent::files_checked (this=0x61d000060490) at ../src/torrent.cpp:8545
#16 0x00005555626b0313 in libtorrent::aux::torrent::on_resume_data_checked (this=0x61d000060490, status=..., error=...) at ../src/torrent.cpp:2246
#17 0x000055556269a17d in operator() (__closure=0x60200002ccb0, st=..., error=...) at ../src/torrent.cpp:1952
#18 0x000055556288a9df in std::__invoke_impl<void, libtorrent::aux::torrent::init()::<lambda(libtorrent::status_t, const libtorrent::storage_error&)>&, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, const libtorrent::storage_error&>(std::__invoke_other, struct {...} &) (__f=...) at /usr/include/c++/12/bits/invoke.h:61
#19 0x0000555562871e9d in std::__invoke_r<void, libtorrent::aux::torrent::init()::<lambda(libtorrent::status_t, const libtorrent::storage_error&)>&, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, const libtorrent::storage_error&>(struct {...} &) (__fn=...) at /usr/include/c++/12/bits/invoke.h:111
```

**Comment by arvidn** [comment]
disabling ubsan but running with asan hits another issue, but they might be related:

```
==3157088==ERROR: AddressSanitizer: requested allocation size 0x2484c741f2f2f2f3 (0x2484c741f2f302f8 after adjustments for alignment, red zones etc.) exceeds maximum supported size of 0x10000000000 (thread T19)
    #0 0x7fc703ac0488 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95
    #1 0x56473559de47 in std::__new_allocator<char>::allocate(unsigned long, void const*) /usr/include/c++/12/bits/new_allocator.h:137
    #2 0x564735598209 in std::allocator_traits<std::allocator<char> >::allocate(std::allocator<char>&, unsigned long) /usr/include/c++/12/bits/alloc_traits.h:464
    #3 0x5647355929d7 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long) /usr/include/c++/12/bits/basic_string.tcc:155
    #4 0x5647355920b3 in void std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*>(char*, char*, std::forward_iterator_tag) /usr/include/c++/12/bits/basic_string.tcc:225
    #5 0x56473558a8e8 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /usr/include/c++/12/bits/basic_string.h:544
    #6 0x56473741ddf9 in rtc::impl::IceTransport::processCandidate(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ../deps/libdatachannel/src/impl/icetransport.cpp:280
    #7 0x56473741e45f in rtc::impl::IceTransport::CandidateCallback(juice_agent*, char const*, void*) ../deps/libdatachannel/src/impl/icetransport.cpp:297
    #8 0x564737504db4 in agent_update_gathering_done (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x4468db4)
    #9 0x5647374ff3bd in agent_run (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x44633bd)
    #10 0x5647374fd6eb in agent_thread_entry (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x44616eb)
    #11 0x7fc703290401 in start_thread nptl/pthread_create.c:442
```

<details>
<summary>SUMMARY: AddressSanitizer: allocation-size-too-big ../../../../src/libsanitizer/asan/asan_new_delete.cpp:95 in operator new(unsigned long)</summary>

```
Thread T19 created by T11 here:
    #0 0x7fc703a4af75 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x5647374fdc03 in agent_gather_candidates (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x4461c03)
    #2 0x5647374f0ace in juice_gather_candidates (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x4454ace)
    #3 0x56473741cb5b in rtc::impl::IceTransport::gatherLocalCandidates(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ../deps/libdatachannel/src/impl/icetransport.cpp:198
    #4 0x5647371b6c31 in rtc::PeerConnection::setLocalDescription(rtc::Description::Type) ../deps/libdatachannel/src/peerconnection.cpp:146
    #5 0x5647371ba07a in rtc::PeerConnection::createDataChannel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, rtc::DataChannelInit) ../deps/libdatachannel/src/peerconnection.cpp:264
    #6 0x5647363c6db4 in libtorrent::aux::rtc_signaling::generate_offers(int, std::function<void (boost::system::error_code const&, std::__debug::vector<libtorrent::aux::rtc_offer, std::allocator<libtorrent::aux::rtc_offer> > const&)>) ../src/rtc_signaling.cpp:159
    #7 0x564735d8fad0 in libtorrent::aux::torrent::generate_rtc_offers(int, std::function<void (boost::system::error_code const&, std::__debug::vector<libtorrent::aux::rtc_offer, std::allocator<libtorrent::aux::rtc_offer> >)>) ../src/torrent.cpp:6011
    #8 0x56473612d1be in libtorrent::aux::tracker_manager::queue_request(boost::asio::io_context&, libtorrent::aux::tracker_request&&, libtorrent::aux::session_settings const&, std::weak_ptr<libtorrent::aux::request_callback>) ../src/tracker_manager.cpp:318
    #9 0x5647359b9cc2 in libtorrent::aux::session_impl::queue_tracker_request(libtorrent::aux::tracker_request, std::weak_ptr<libtorrent::aux::request_callback>) ../src/session_impl.cpp:1274
    #10 0x564735d5fcb3 in libtorrent::aux::torrent::announce_with_tracker(libtorrent::event_t) ../src/torrent.cpp:3214
    #11 0x564735dcfd26 in libtorrent::aux::torrent::start_announcing() ../src/torrent.cpp:9949
    #12 0x564735dba58a in libtorrent::aux::torrent::files_checked() ../src/torrent.cpp:8545
    #13 0x564735d50e6c in libtorrent::aux::torrent::on_resume_data_checked(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, libtorrent::storage_error const&) ../src/torrent.cpp:2246
    #14 0x564735d4872e in operator() ../src/torrent.cpp:1952
    #15 0x564735e0d785 in __invoke_impl<void, libtorrent::aux::torrent::init()::<lambda(libtorrent::status_t, const libtorrent::storage_error&)>&, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, const libtorrent::storage_error&> /usr/include/c++/12/bits/invoke.h:61
    #16 0x564735dfef04 in __invoke_r<void, libtorrent::aux::torrent::init()::<lambda(libtorrent::status_t, const libtorrent::storage_error&)>&, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, const libtorrent::storage_error&> /usr/include/c++/12/bits/invoke.h:111
    #17 0x564735df5ba4 in _M_invoke /usr/include/c++/12/bits/std_function.h:290
    #18 0x564737141dfa in std::function<void (libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, libtorrent::storage_error const&)>::operator()(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::disk_storage_status_tag, void>, libtorrent::storage_error const&) const /usr/include/c++/12/bits/std_function.h:591
    #19 0x56473714024e in operator() ../src/disk_job.cpp:67
    #20 0x5647371415a4 in __invoke_impl<void, libtorrent::aux::(anonymous namespace)::caller_visitor, libtorrent::aux::job::check_fastresume&> /usr/include/c++/12/bits/invoke.h:61
    #21 0x56473714126f in __invoke<libtorrent::aux::(anonymous namespace)::caller_visitor, libtorrent::aux::job::check_fastresume&> /usr/include/c++/12/bits/invoke.h:96
    #22 0x564737140d1a in __visit_invoke /usr/include/c++/12/variant:1031
    #23 0x564737141004 in __do_visit<std::__detail::__variant::__deduce_visit_result<void>, libtorrent::aux::(anonymous namespace)::caller_visitor, std::variant<libtorrent::aux::job::read, libtorrent::aux::job::write, libtorrent::aux::job::hash, libtorrent::aux::job::hash2, libtorrent::aux::job::move_storage, libtorrent::aux::job::release_files, libtorrent::aux::job::delete_files, libtorrent::aux::job::check_fastresume, libtorrent::aux::job::rename_file, libtorrent::aux::job::stop_torrent, libtorrent::aux::job::file_priority, libtorrent::aux::job::clear_piece, libtorrent::aux::job::partial_read>&> /usr/include/c++/12/variant:1750
    #24 0x564737141067 in visit<libtorrent::aux::(anonymous namespace)::caller_visitor, std::variant<libtorrent::aux::job::read, libtorrent::aux::job::write, libtorrent::aux::job::hash, libtorrent::aux::job::hash2, libtorrent::aux::job::move_storage, libtorrent::aux::job::release_files, libtorrent::aux::job::delete_files, libtorrent::aux::job::check_fastresume, libtorrent::aux::job::rename_file, libtorrent::aux::job::stop_torrent, libtorrent::aux::job::file_priority, libtorrent::aux::job::clear_piece, libtorrent::aux::job::partial_read>&> /usr/include/c++/12/variant:1846
    #25 0x56473714096a in libtorrent::aux::disk_job::call_callback() ../src/disk_job.cpp:106
    #26 0x56473684e756 in libtorrent::aux::disk_completed_queue::call_job_handlers() ../src/disk_completed_queue.cpp:85
    #27 0x56473684ddf9 in operator() ../src/disk_completed_queue.cpp:54
    #28 0x564736850bd1 in operator() /home/arvid/dev/boost_1_79_0/boost/asio/detail/bind_handler.hpp:60
    #29 0x564736850408 in invoke<boost::asio::detail::binder0<libtorrent::aux::disk_completed_queue::append(boost::asio::io_context&, libtorrent::jobqueue_t)::<lambda()> >, boost::asio::detail::binder0<libtorrent::aux::disk_completed_queue::append(boost::asio::io_context&, libtorrent::jobqueue_t)::<lambda()> > > /home/arvid/dev/boost_1_79_0/boost/asio/detail/handler_invoke_helpers.hpp:51
    #30 0x5647368510b8 in do_complete /home/arvid/dev/boost_1_79_0/boost/asio/detail/executor_op.hpp:70
    #31 0x5647355e4e58 in boost::asio::detail::scheduler_operation::complete(void*, boost::system::error_code const&, unsigned long) /home/arvid/dev/boost_1_79_0/boost/asio/detail/scheduler_operation.hpp:40
    #32 0x5647355ecff3 in boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) /home/arvid/dev/boost_1_79_0/boost/asio/detail/impl/scheduler.ipp:492
    #33 0x5647355ec1f9 in boost::asio::detail::scheduler::run(boost::system::error_code&) /home/arvid/dev/boost_1_79_0/boost/asio/detail/impl/scheduler.ipp:210
    #34 0x5647356580b3 in boost::asio::io_context::run() /home/arvid/dev/boost_1_79_0/boost/asio/impl/io_context.ipp:63
    #35 0x5647358e9ba0 in operator() ../src/session.cpp:297
    #36 0x5647358ef9f1 in __invoke_impl<void, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/invoke.h:61
    #37 0x5647358ef9b4 in __invoke<libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/invoke.h:96
    #38 0x5647358ef961 in _M_invoke<0> /usr/include/c++/12/bits/std_thread.h:252
    #39 0x5647358ef935 in operator() /usr/include/c++/12/bits/std_thread.h:259
    #40 0x5647358ef919 in _M_run /usr/include/c++/12/bits/std_thread.h:210
    #41 0x7fc7036dc3a2  (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc3a2)

Thread T11 created by T0 here:
    #0 0x7fc703a4af75 in __interceptor_pthread_create ../../../../src/libsanitizer/asan/asan_interceptors.cpp:207
    #1 0x7fc7036dc478 in std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)()) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xdc478)
    #2 0x5647358eedb2 in _Construct<std::thread, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/stl_construct.h:119
    #3 0x5647358eed67 in construct<std::thread, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/alloc_traits.h:635
    #4 0x5647358eecba in _Sp_counted_ptr_inplace<libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/shared_ptr_base.h:604
    #5 0x5647358eea3e in __shared_count<std::thread, std::allocator<void>, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/shared_ptr_base.h:971
    #6 0x5647358ee81f in __shared_ptr<std::allocator<void>, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/shared_ptr_base.h:1712
    #7 0x5647358ee6b4 in shared_ptr<std::allocator<void>, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/shared_ptr.h:464
    #8 0x5647358ee578 in make_shared<std::thread, libtorrent::session::start(libtorrent::session_flags_t, libtorrent::session_params&&, boost::asio::io_context*)::<lambda()> > /usr/include/c++/12/bits/shared_ptr.h:1010
    #9 0x5647358eb8a6 in libtorrent::session::start(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>, libtorrent::session_params&&, boost::asio::io_context*) ../src/session.cpp:294
    #10 0x5647358ebd38 in libtorrent::session::start(libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>, libtorrent::settings_pack&&, boost::asio::io_context*) ../src/session.cpp:308
    #11 0x5647358ed757 in libtorrent::session::session(libtorrent::settings_pack const&, libtorrent::flags::bitfield_flag<unsigned char, libtorrent::session_flags_tag, void>) ../src/session.cpp:378
    #12 0x564735584007 in libtorrent::session::session(libtorrent::settings_pack const&) (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x24e8007)
    #13 0x56473558c64d in std::__detail::_MakeUniq<libtorrent::session>::__single_object std::make_unique<libtorrent::session, libtorrent::settings_pack&>(libtorrent::settings_pack&) (/home/arvid/dev/libtorrent/test/bin/test_tracker.test/gcc-9.2/debug-mode/address-model-64/address-sanitizer-norecover/cxxstd-17-iso/export-extra-on/link-static/picker-debugging-on/threading-multi/webtorrent-on/test_tracker+0x24f064d)
    #14 0x564735570c30 in unit_test_websocket_tracker /home/arvid/dev/libtorrent/test/test_tracker.cpp:699
    #15 0x5647355b31ea in main /home/arvid/dev/libtorrent/test/main.cpp:507
    #16 0x7fc70322350f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
```
</details>

All of these issues suggests there's some memory corruption somewhere.

**Comment by arvidn** [comment]
I have a feeling that `libusrsctp` and `libjuice` may not have been reubilt correctly when I updated the submodule. running `git clean -f` in those repositories now give me this build error instead:

```
CMake Error: The current CMakeCache.txt directory /home/arvid/dev/libtorrent/deps/libdatachannel/deps/usrsctp/build-debug-mode/CMakeCache.txt is different than the directory z:/libtorrent/deps/libdatachannel/deps/usrsctp/build-debug-mode where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/home/arvid/dev/libtorrent/deps/libdatachannel/deps/usrsctp/CMakeLists.txt" does not match the source "Z:/libtorrent/deps/libdatachannel/deps/usrsctp/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
```

the `Z:\` looks suspicious.

**Comment by arvidn** [comment]
I think all of this might have been a false alarm because those dependencies hadn't been rebuilt

**Pull request merged**
