### PR TITLE
restore the ipv6 http tracker argument

### PR DESCRIPTION
**Pull request by arvidn**
but restricted to only private torrents

### CODE REVIEW

**Comment by arvidn** [comment]
Is this really a good idea?

**Comment by aldenml** [comment]
hmmm...are you asking yourself?

**Comment by arvidn** [comment]
anyone really :)

**Comment by Indust** [comment]
the ipv6 doesn't seem to work properly on RC_1_1 branch, 
[e81ac58](https://github.com/arvidn/libtorrent/commit/e81ac58620184f8905d4025e3f9ad58fc042ea32) and [445cf4b](https://github.com/arvidn/libtorrent/commit/445cf4be0427252d62fcc6a37f4e8e9d63dd56de) look the same, but only previous commit in RC_1_0 branch works well and the RC_1_1 branch build is still missing ipv6 arg in announce url.

**Comment by arvidn** [comment]
because of privacy concerns, the resurrected ipv6 tracker argument is only active for private torrents

**Comment by arvidn** [comment]
the proper way to handle it is to announce using all local interfaces as sources.

**Comment by Indust** [comment]
actually, all of my torrents is private..

**Pull request merged**
