### PR TITLE
moved deadline_timer.hpp and debug.hpp to aux

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
it looks like something is exposed to clients and are now causing link errors: https://github.com/arvidn/libtorrent/pull/5857/checks?check_run_id=1692881436#step:7:194

**Comment by arvidn** [comment]
actually, not exposed to clients, but probably had the declaration moved into `aux` but not the definition: https://github.com/arvidn/libtorrent/pull/5857/checks?check_run_id=1692881403#step:4:363

**Comment by arvidn** [comment]
the debug stuff is a bit messy when enabled. There's no clean counterpart to `debug.hpp` where the definitions are.

**Comment by arvidn** [comment]
I think [these](https://github.com/arvidn/libtorrent/blob/master/src/session_impl.cpp#L160) need to me moved to `libtorrent::aux`

**Comment by aldenml** [comment]
thanks @arvidn, I think that is the problem (moving the definitions to aux)

**Pull request merged**
