### PR TITLE
Removed unused cpp files

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
heh, you would imagine I had removed these, as removing code is one of the most exciting things to do :)

**Comment by arvidn** [comment]
I take it none of the Jamfiles, Makefile.am or CMakeList.txt mentions these files, right?

**Comment by aldenml** [comment]
I checked at the time Makefile.am and verified now the CMakeList.txt file. No mention.

**Comment by arvidn** [comment]
the error on travis is very strange. I've re-built and it seems to fail consistently

**Comment by aldenml** [comment]
It's strange indeed

**Comment by aldenml** [comment]
Hi @arvidn, can you clear the cache in travis? I just run the build in my account and it ran fine.
Could this be a subtle bug in the compiler:
```
darwin.link.dll ./lib/libtorrent.dylib.1.1.0
ld: warning: directory not found for option '-L/opt/local/lib'
ld: warning: directory not found for option '-L/sw/lib'
ld: warning: directory not found for option '-L/usr/g++/lib'
CFISection::cfiParse() unexpected relocation size at r_address=0x00000000
clang: error: unable to execute command: Segmentation fault: 11
```

**Comment by aldenml** [comment]
Well, it's green now

**Pull request merged**
