### PR TITLE
Don't force an -std= flag in the Cflags field of the generated pkg-config file

### PR DESCRIPTION
**Pull request by FranciscoPombal**

### CODE REVIEW

**Comment by arvidn** [comment]
ping @zeule See linked ticket for context

**Comment by zeule** [comment]
Why don't you check the compiler default prior to setting C++ mode to a value. lower than that? Why does the client put libtorrent flags after its own settings (otherwise qBt settings would override the C++ mode)?

**Comment by FranciscoPombal** [comment]
@zeule Not sure if this is an issue with qBittorrent (and if so, with which buildsystem), Chocobo1 simply mentioned that it was unexpected that the generated pkgconfig always ends up forcing `-std=gnu++11`. Plus I don't think it's wise to rely on the order of these flags as a potential fix. The `-std` flags are supposed to be propagated in an order-agnostic way, no?

**Comment by zeule** [comment]
Why don't you check the compiler default prior to setting C++ mode to a value, lower than that?

**Comment by zeule** [comment]
Another question: why don't we choose the newest available if user did not request other version explicitly?

**Comment by FranciscoPombal** [comment]
@zeule 

> Why don't you check the compiler default prior to setting C++ mode to a value, lower than that?

What is the context of this question? Building libtorrent, or building something that requires libtorrent? And how would you check the compiler default, without using `CMAKE_CXX_STANDARD_DEFAULT`?

**Comment by FranciscoPombal** [comment]
@zeule 

> Another question: why don't we choose the newest available if user did not request other version explicitly?

I believe that was answered in the linked ticket: https://github.com/arvidn/libtorrent/issues/5012#issuecomment-675639644, https://github.com/arvidn/libtorrent/issues/5012#issuecomment-675706159, https://github.com/arvidn/libtorrent/issues/5012#issuecomment-675712519

**Comment by zeule** [comment]
> What is the context of this question?  

libtorrent.

> And how would you check the compiler default, without using `CMAKE_CXX_STANDARD_DEFAULT`?

If you reject `CMAKE_CXX_STANDARD_DEFAULT`, you can write a simple test program to check the standard value.

**Comment by FranciscoPombal** [comment]
@zeule 

> > What is the context of this question?
> 
> libtorrent.

When building libtorrent, CMake doesn't set the C++ standard to anything specific if it doesn't have to. It uses the compiler default if it can, otherwise it passes `-std=gnu++11` to satisfy the minimum requirement enforced by the call to `target_compile_features()`. The generated CMake config file propagates this minimum requirement up, so that a program that links against libtorrent will only be forced to use `-std=gnu++11` if it would otherwise use something lower.

The problem here is that it is not possible to convey these semantics with pkg-config.
With pkg-config, if you want to have `-std=` in the `Cflags`, you either pass it the value of the compile features (which is always C++11), or somehow determine the compiler default and pass that, which leads us to...

> > And how would you check the compiler default, without using `CMAKE_CXX_STANDARD_DEFAULT`?
> 
> If you reject `CMAKE_CXX_STANDARD_DEFAULT`, you can write a simple test program to check the standard value.

Why should we do that instead of what this PR does (previous justifications here: https://github.com/arvidn/libtorrent/pull/5013#issuecomment-675760232)?

**Comment by zeule** [comment]
Because the libtorrent ABI depends on the C++ standard value used while building the library. That's unfortunate, but we have to export that standard value (and export it as the compiler flag like pkg-config does).

**Comment by arvidn** [comment]
the only place that I know of (apart from possible changes in standard library types, but they try to avoid that) is that `entry` dictionaty type. Which I think should be communicated via pkg-configs cflags as `TORRENT_CXX11_ABI`. But I haven't looked at @FranciscoPombal's report on that patch yet

**Comment by arvidn** [comment]
> Because the libtorrent ABI depends on the C++ standard value used while building the library. That's unfortunate, but we have to export that standard value (and export it as the compiler flag like pkg-config does).

Is the conclusion that @Chocobo1's [observation](https://github.com/arvidn/libtorrent/issues/5012) is an *improvement* over the previous behavior?

**Pull request merged**
