### PR TITLE
Project cleanup

### PR DESCRIPTION
**Pull request by Chocobo1**
I assume all python script is in python2, I didn't check every one of them...
The whitespace/tab cleanup is a byproduct though, my editor will remove it automatically...

Added .gitignore file, this make working with git easier.

Comments are welcome.

### CODE REVIEW

**Comment by arvidn** [comment]
"/usr/bin/env python2" does not work on OSX. that goes for just invoking "python2" as well. Do you think there's a way that would work both on (modern) linux and osx? I would imagine most python scripts are mostly python 2 and 3 compatible

**Comment by Chocobo1** [comment]
>"/usr/bin/env python2" does not work on OSX

Sorry, I didn't know that, it's seems similar to this one: https://github.com/clinton-hall/nzbToMedia/issues/454, right?
They solved it by creating a link `/usr/local/bin/python2` -> `/usr/local/bin/python2.7`... not a perfect solution to me.

If you want, I can revert to `/usr/bin/env python` and drop commit ad69331. The user/dev of this project should know python2 is in use instead of python3.

>I would imagine most python scripts are mostly python 2 and 3 compatible

I hope this was true... but unfortunately not, even a simple one `print` is different. There is tool to convert though: https://docs.python.org/2/library/2to3.html

**Comment by arvidn** [comment]
yeah, please revert the python changes. I'll take a look at how much work it is to make them python3 compatible

**Comment by Chocobo1** [comment]
OK, it's done.
I added another commit which zero out ccache stats (it didn't touch cache) for every travis build, because I feel the stats shown at the end of a build should not be a cumulative value, but as a per build session value, it's more meaningful.

**Comment by arvidn** [comment]
I only printed the stats in there to understand why ccache didn't seem to work.

**Pull request merged**
