### PR TITLE
hike required windows version to vista

### PR DESCRIPTION
**Pull request by john-peterson**
because xp has faded into the sunset

### CODE REVIEW

**Comment by arvidn** [comment]
Don't you need to remove or change the "_WIN32_WINNT" define too? In fact, perhaps that whole #undef and #define could be removed (assuming this patch makes _WIN32_WINNT be defined throughout the build)

**Comment by john-peterson** [comment]
>Don't you need to remove or change the "_WIN32_WINNT" define too? 

where?

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/blob/bc849b8d0756700212f35b1a61f53cc47cb928a3/src/assert.cpp#L100

**Comment by john-peterson** [comment]
done

**Comment by arvidn** [comment]
appveyor is still failing on the CreateSemaphoreEx() call. is setting _WIN32_WINNT not enough to make that function visible?

**Comment by john-peterson** [comment]
i dont see any appveyor build of this branch. the link https://ci.appveyor.com/project/arvidn/libtorrent/build/1.0.146 lead to another branch 1c708cca

**Comment by john-peterson** [comment]
i dont get the warning in this branch that i get in master https://github.com/arvidn/libtorrent/pull/19#issuecomment-118684648

	git clean -fxd
	b2 -j8 -q -s BOOST_ROOT=D:\repo\boost toolset=msvc-12.0 address-model=64 variant=debug link=shared boost-link=shared runtime-link=shared debug-symbols=on boost=source character-set=unicode encryption=off windows-api=desktop | ack --color --passthru error
	msvc.link.dll bin\msvc-12.0\debug\address-model-64\boost-link-shared\boost-source\encryption-off\threading-multi\torrent.dll
   Creating library bin\msvc-12.0\debug\address-model-64\boost-link-shared\boost-source\encryption-off\threading-multi\torrent.lib and object bin\msvc-12.0\debug\address-model-64\boost-link-shared\boost-source\encryption-off\threading-multi\torrent.exp
msvc.manifest.dll bin\msvc-12.0\debug\address-model-64\boost-link-shared\boost-source\encryption-off\threading-multi\torrent.dll

**Comment by john-peterson** [comment]
a build command more similar to appveyor also worx

	git clean -fxd
	b2 msvc -j8 -q -s BOOST_ROOT=D:\repo\boost boost=source variant=test_barebones link=shared encryption=off warnings=off --abbreviate-paths | ack --color --passthru error
msvc.link.dll bin\msvc-12.0\tst_b\bst-src\encry-off\torrent.dll
	   Creating library bin\msvc-12.0\tst_b\bst-src\encry-off\torrent.lib and object bin\msvc-12.0\tst_b\bst-src\encry-off\torrent.exp
	msvc.manifest.dll bin\msvc-12.0\tst_b\bst-src\encry-off\torrent.dll
	...updated 135 targets...

**Comment by arvidn** [comment]
oh, you're right. weird.

**Pull request merged**
