### PR TITLE
Fix repeating torrent_error_alert for same error Issue #274

### PR DESCRIPTION
**Pull request by ruslanfedoseenko**

### CODE REVIEW

**Comment by arvidn** [comment]
do you know why set_error() is called multiple times in this case? When set_error() is called, the torrent is supposed to be stopped. I imagine that while the disk io job queue is drained, each job may fail in the same way. That should only be a handful of calls though. Is that consistent with the symptom you see?

If the save path is never accessible, I would expect the first (check_resume_data) job to fail. At that point there should only be a single outstanding job, and no opportunity to call set_error() multiple times.

There should be a test covering this as well (ideally under simulation, using a custom storage implementation that always just fail with EPERM presumably would do it)

**Comment by ruslanfedoseenko** [comment]
yes, I think it is consistetent with symptoms i see.

**Comment by arvidn** [comment]
I didn't mean it doesn't warrant this patch. I was just worried that there may be a deeper bug, that this patch would cover.

for instance, if you assert that the error_code in subsequent set_error() calls is the same as what's already set, I think that would make it a good patch.

**Comment by ruslanfedoseenko** [comment]
I'll agree with you that it can be a deeper bug(that is why i closed pull request). But may be you forgot that i'm using 1.0.7 whitch have only one disk thread(as i know in master version of libtorrent there can be multiple disk threads). So do you still consider that behaviour you discribed applies to such case?

**Comment by arvidn** [comment]
even with a single thread, there's a backlog/queue of disk jobs. So if there's a permission error, chances are that every job in the queue will fail with the same error.

**Pull request closed without merging**
