### PR TITLE
support building python bindings for python 3 and 64 bit

### LINKED ISSUE #2813: building libtorrent under python 3.6.4 64bit failed
**Please provide the following information**

libtorrent version (or branch):
1.1.6

platform/architecture:
Windows 10 64bit
Python 3.6.4 64bit
Boost 1.66

compiler and compiler version:
MSVC Community 14.11.25503

STEP 1, change  /setup.py for python 3 compatible:
C:\tmp\libtorrent-rasterbar-1.1.6
line 5:
`execfile('setup.py') `
change to: 
`exec(open('setup.py').read())`

STEP 2, change /bindings/python/setup.py to build a 64bit
C:\tmp\libtorrent-rasterbar-1.1.6\bindings\python\setup.py
line 79
`			toolset = ' msvc-9.0'`
change to:
`			toolset = ' msvc'`

line 85:
`		cmdline = 'b2 libtorrent-link=static boost-link=static release optimization=space stage_module --abbreviate-paths' + toolset + parallel_builds`
change to:
`		cmdline = 'b2 libtorrent-link=static boost-link=static release optimization=space stage_module architecture=x86 address-model=64 --abbreviate-paths' + toolset + parallel_builds
`

STEP3: run following command to build:
`python setup.py install --bjam`

Then build report a lot of link errors:
...patience...
...patience...
...patience...
...found 5450 targets...
...updating 4 targets...
msvc.link.dll bin\msvc-14.1\rls\adrs-mdl-64\archt-x86\bst-lnk-sttc\lbtrn-lnk-sttc\optmz-spc\libtorrent.pyd
   Creating library bin\msvc-14.1\rls\adrs-mdl-64\archt-x86\bst-lnk-sttc\lbtrn-lnk-sttc\optmz-spc\libtorrent.lib and object bin\msvc-14.1\rls\adrs-mdl-64\archt-x86\bst-lnk-sttc\lbtrn-lnk-sttc\optmz-spc\libtorrent.exp
module.obj : error LNK2019: unresolved external symbol "__declspec(dllimport) struct _object * __cdecl boost::python::detail::init_module(struct PyModuleDef &,void (__cdecl*)(void))" (__imp_?init_module@detail@python@boost@@YAPEAU_object@@AEAUPyModuleDef@@P6AXXZ@Z) referenced in function PyInit_libtorrent
error_code.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
datetime.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
peer_info.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
ip_filter.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl boost::python::throw_error_already_set(void)" (__imp_?throw_error_already_set@python@boost@@YAXXZ)
...

Please check details in the attachment.
[build.txt](https://github.com/arvidn/libtorrent/files/1761399/build.txt)

### PR DESCRIPTION
**Pull request by ssiloti**
Fixes #2813

### CODE REVIEW

**Comment by arvidn** [comment]
nice!

**Comment by arvidn** [comment]
I think it makes sense to encode the compiler version based on the python version. The ABI compatibility of python modules is subtle and not something I think most python developers are familiar with. However, I wonder why this used to work, I did right? Is the test only running python3 on appveyor?

**Comment by ssiloti** [comment]
On master appveyor only tests with Python 3.5 and msvc-14.0. I'm not sure why this PR is failing. I'm pretty sure the reason is that I'm only specifying the major version in the toolset parameter instead of the full version number. I think only specifying the major number _should_ work, it works on my machine but I'm using newer versions of boost and msvc.

**Comment by ssiloti** [comment]
Alright, I'm not totally satisfied with this but it's the best I've got for now.

**Pull request merged**
