### PR TITLE
Typo in comment

### PR DESCRIPTION
**Pull request by Col-blimp**

### CODE REVIEW

**Comment by arvidn** [comment]
would you mind just remove the mention of any default value instead? I'm pretty sure the actual default is included in the generated documentation

**Comment by Col-blimp** [comment]
Shall all references to defaults be removed from that file?

**Comment by arvidn** [comment]
yes, they should

**Comment by arvidn** [comment]
as you can see [here](http://libtorrent.org/reference-Settings.html#settings_pack), the defaults are extracted from the source.

**Pull request closed without merging**
