### PR TITLE
fix handling edge cases of padfiles in web seed peer connection

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
I believe there's an edge case not covered if the last part of a request is a pad file, since with this patch pad files are handled when receiving content

**Comment by ajax16384** [comment]
tryed "web-seed-padfiles-1.1" branch changes with possibly affected torrents (with webseed and padfiles): seems ok.

**Comment by arvidn** [comment]
I made the test case more aggressive to test lots of odd combinations and realized that there were still cases that failed. After spending about two days trying to fix it I determined the current logic in the web peer connection is hopeless and I'm currently re-writing parts of it to make it simpler and correct in all cases. Thanks for testing this though!

**Comment by arvidn** [comment]
the unit test here needs some serious shaping up

**Comment by arvidn** [comment]
allright. I think I'm done with this patch now. would you mind giving it another try?

**Pull request merged**
