### PR TITLE
bump cibuildwheel action to v2.17.0

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by xavier2k6** [comment]
@arvidn try using Boost 1.82.0 instead.

**Comment by arvidn** [comment]
it looks like there's some progress. Now the failure is a rename that happens after the build, [here](https://github.com/arvidn/libtorrent/actions/runs/9045001325/job/24854272600?pr=7672#step:5:910).

```
    rename build\lib.win-amd64-cpython-37\libtorrent.cp37-win_amd64.pyd -> build\lib.win-amd64-cpython-37\libtorrent\__init__.cp37-win_amd64.pyd
    error: [WinError 2] The system cannot find the file specified: 'build\\lib.win-amd64-cpython-37\\libtorrent.cp37-win_amd64.pyd' -> 'build\\lib.win-amd64-cpython-37\\libtorrent\\__init__.cp37-win_amd64.pyd'
```

**Comment by xavier2k6** [comment]
It should make no difference to error but just as an FYI v2.18.0 of cibuildwheel action has been released.

**Comment by qstokkink** [comment]
Thanks for picking this up! I'd like to see this fixed, so I'll support to the best of my ability.

<details> <summary> [Click me for analysis] </summary>

If I'm interpreting the log correctly, this is the "rename" log entry just before failure:

https://github.com/arvidn/libtorrent/blob/31003b7c8d08ba2e4b5956f3e2c0cfab6da7bdd5/bindings/python/setup.py#L361

I assume the following `os.rename(src, dst)` is the cause of the crash.

On the other builds this succeeds. For example, Mac:

```
common.copy /Users/runner/work/libtorrent/libtorrent/bindings/python/build/lib.macosx-10.9-x86_64-cpython-37/libtorrent.cpython-37m-darwin.so
    ...updated 276 targets...
    rename build/lib.macosx-10.9-x86_64-cpython-37/libtorrent.cpython-37m-darwin.so -> build/lib.macosx-10.9-x86_64-cpython-37/libtorrent/__init__.cpython-37m-darwin.so
```

However, on Windows, `build\lib.win-amd64-cpython-37\libtorrent.pyd` is apparently created instead of the expected `build\lib.win-amd64-cpython-37\libtorrent.cp37-win_amd64.pyd`:

```
common.copy D:\a\libtorrent\libtorrent\bindings\python\build\lib.win-amd64-cpython-37\libtorrent.pyd
    bin\msvc-14.3\rls\adrs-mdl-64\cxstd-14-iso\pythn-3.7\libtorrent.pyd
            1 file(s) copied.
    ...updated 266 targets...
    rename build\lib.win-amd64-cpython-37\libtorrent.cp37-win_amd64.pyd -> build\lib.win-amd64-cpython-37\libtorrent\__init__.cp37-win_amd64.pyd
```

</details>

As I see it, you could remedy this by either changing the `setup.py` output-detection logic or the build logic that creates the output in the first place (probably in the jamfile).

**Comment by qstokkink** [comment]
@arvidn if you want some help and you don't mind me hammering your GitHub Actions builds for a bit, I can try getting the action (back) up and running. Just let me know and I'll pick this up.

**Comment by qstokkink** [comment]
According to the following line, the `EXT_SUFFIX` is empty on Windows. I'm not 100% sure but that might be causing the failure.

```
2024-05-11T16:35:18.8519849Z   using python : 3.7 : "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-ffbtcev5\\cp37-win_amd64\\build\\venv\\Scripts\\python.exe" : "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-ffbtcev5\\cp37-win_amd64\\build\\venv\\include" "C:\\Users\\runneradmin\\AppData\\Local\\pypa\\cibuildwheel\\Cache\\nuget-cpython\\python.3.7.9\\tools\\include" "C:\\Users\\runneradmin\\AppData\\Local\\pypa\\cibuildwheel\\Cache\\nuget-cpython\\python.3.7.9\\tools\\Include" : "C:\\Users\\runneradmin\\AppData\\Local\\Temp\\cibw-run-ffbtcev5\\cp37-win_amd64\\build\\venv\\libs" : <libtorrent-python>on : "" ;
```

**Comment by arvidn** [comment]
the next issue:
```
+ bash -c "cd 'D:\a\libtorrent\libtorrent/bindings/python' && python test.py"
  Error: Command bash -c "cd 'D:\a\libtorrent\libtorrent/bindings/python' && python test.py" failed with code 2816. None
```

**Comment by arvidn** [comment]
exit code 2813, according to [this](https://missionimpossiblecode.io/windowsinstallererrorcodes) means:
> The EndDialog event was called with the argument [2], but the dialog has a parent

Possibly some issue related to the program running in a console, without a GUI.

the other python test fails with exit code `0xC0000005`, which is `ACCESS VIOLATION`

**Comment by xavier2k6** [comment]
>exit code 2813

@arvidn Where did you see this?

https://github.com/arvidn/libtorrent/pull/7672#issuecomment-2155980837 shows **2816**

>The EventMapping table refers to an invalid control [4] on dialog [2] for the event [3]

**Comment by arvidn** [comment]
https://github.com/arvidn/libtorrent/actions/runs/9427920137/job/25972643164?pr=7672#step:5:995

**Comment by qstokkink** [comment]
Almost there 🎉 I think `2816` is simply a segfault (`11`) in disguise due to bash running on Windows (for reasons explained [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105335#c0)).

It would be easier to debug if we could check out the `.whl` that was produced. Could you skip the test command and share the wheel?

**Comment by qstokkink** [comment]
Thanks for the wheel! I'll prod around and see what I can find.

**Comment by qstokkink** [comment]
I don't think I can do anything more with the current log output. Replaying the logged commands locally with the same software versions works as expected. That implies that there is some path/configuration error specific to the GitHub Actions builder images.

My current theory is that the test code _somehow_ pulls in the GitHub Action's default OpenSSL ([OpenSSL 1.1.1w](https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md)) instead of the version that the Action installs (`3.3.1`).

If fixing the path doesn't work, I can open a PR to dig through the environment variables but @arvidn I want your explicit permission/consent before I do that.

**Comment by qstokkink** [comment]
Hold on, there _was_ a change since the last time the `Windows / Test (release)` passed. This command is now installing `Win64OpenSSL-3_3_1.exe` instead of `Win64OpenSSL-3_3_0.exe`:

https://github.com/arvidn/libtorrent/blob/31003b7c8d08ba2e4b5956f3e2c0cfab6da7bdd5/.github/workflows/python.yml#L79

There is a chance that adding `--version=3.3.0` here will magically fix the `Windows / Test (release)` tests.

**Comment by qstokkink** [comment]
It seems like everything except Mac stuff is now operational (which I guess is getting fixed in #7606). 🥳 

I consider my work done here and I'll retreat back to my usual repos until some other esoteric failure occurs again.

**Comment by arvidn** [comment]
@qstokkink thanks for the help! (and sorry for not having so much time to address this sooner)

**Comment by qstokkink** [comment]
@arvidn no worries, thanks for getting everything up-and-running again. If there is still anything stopping you from uploading the wheels to PyPI for the next release, feel free to @ me.

**Pull request merged**
