### PR TITLE
Don't force the compiler to search in /usr/include

### PR DESCRIPTION
**Pull request by aldenml**
This was causing problems with android and the clang toolchain and probably other hidden issues.

### CODE REVIEW

**Comment by arvidn** [comment]
it occurs to me that maybe it's a bad idea to add any of those system paths. if cross-compiling, I imagine they could cause trouble.

**Comment by aldenml** [comment]
Do you think we can cleanup this little by little?

**Comment by arvidn** [comment]
sure

**Comment by arvidn** [comment]
would you mind rebasing this on top of master to try again? I had the same problem in the std::bind branch, so I switched to mingw32, which worked (and is in master now).

**Comment by aldenml** [comment]
rebased

**Pull request merged**
