### PR TITLE
[clang-tidy] use raw strings

### PR DESCRIPTION
**Pull request by neheb**
Found with modernize-raw-string-literal

Signed-off-by: Rosen Penev <rosenp@gmail.com>

### CODE REVIEW

**Comment by arvidn** [comment]
It's not completely obvious to me that this is an improvement. only one of the changes reduces the number of characters for instance, and only by 2 characters.

**Comment by FranciscoPombal** [comment]
@arvidn Even though there might not be a reduction in the number of characters, IMO the benefit of using raw strings is to not have to worry about escaping anything or missing escapes.

**Comment by arvidn** [comment]
> Even though there might not be a reduction in the number of characters, IMO the benefit of using raw strings is to not have to worry about escaping anything or missing escapes.

but with that logic *all* strings ought to be raw string literals, in case something need to be escaped, or if someone forgets to escape something that was meant to be. (I think it really only applies to `"`, since you don't really forget to escape `\n`).

I think the main benefit of raw string literals are when there is so much escaping that the "meaning" is obfuscated.

I'm not opposed to this change, but I also don't feel like it's particularly well justified. Should all string literals with a `"` it them be a raw string literal? Is it just to satisfy clang-tidy?

**Comment by FranciscoPombal** [comment]
Good points. I suppose it's a matter of style/policy in the end then. You could decide "every string in the code base should be raw, for maximum consistency and `clag-tidy` statisfiability" or "every string in the code base should not be raw, for maximum consistency", or even "I'll know good candidates for raw strings when I see them, otherwise they should not be used". Up to you. Full disclosure, I'm more partial to the first option - but is there any particular disadvantage (in terms of performance or something) to using them?

**Comment by arvidn** [comment]
I'm with Tony :) https://youtu.be/GPP64opjy_Y?t=1169

**Comment by neheb** [comment]
There's no performance difference with raw strings. Not even compile time.

Let's look at a hilarious example: https://github.com/jbeder/yaml-cpp/pull/876/commits/cfe99dc1078cd772c6fc718d10690cfead0c9a73#diff-46e7b027d02f780467a7b7ed7b0a7cedR384

The original is unreadable to me.

**Comment by arvidn** [comment]
I think it's obvious that there's no performance difference (unless we're measuring performance in legibility).
I'm suggesting that sometimes escaping a quote is more readable than using a raw string literal, and sometimes it isn't

**Comment by neheb** [comment]
To each his own I guess...

**Comment by arvidn** [comment]
in that commit, changing `"\x20"` -> `R(" ")` seems a bit odd and inconsistent. Why not change it to `" "`?

**Comment by neheb** [comment]
Different project. If I were to speculate, \x20 is to prevent compilers from being clever.

**Pull request closed without merging**
