### PR TITLE
fix binding setup without complie_cmd

### PR DESCRIPTION
**Pull request by se-m**

### CODE REVIEW

**Comment by se-m** [comment]
build binding in FreeBSD #4204

**Comment by arvidn** [comment]
do these bindings work on BSD as well? Do they end up linking against the main libtorrent library correctly?

**Comment by arvidn** [comment]
@filips123 would you mind reviewing this too?

On MacOS, I ran this out of the `bindings/python` directory:

```
$ python3 setup.py build
```

I get this problem:

```
/Users/arvid/Documents/dev/libtorrent/bindings/python/src/boost_python.hpp:8:10: fatal error: 'cstdio' file not found
#include <cstdio>
         ^~~~~~~~
1 warning and 1 error generated.
```

Which is caused by distutils building a C++ file as if it was C, so the C++ library isn't available.

The command that's invoked is:

```
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I../../include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /Users/arvid/Documents/dev/libtorrent/bindings/python/src/alert.cpp -o build/temp.macosx-10.14-x86_64-3.7/Users/arvid/Documents/dev/libtorrent/bindings/python/src/alert.o -DTORRENT_DISABLE_ENCRYPTION -DBOOST_ASIO_HAS_STD_CHRONO=1 -DBOOST_EXCEPTION_DISABLE -DBOOST_ASIO_ENABLE_CANCELIO -DTORRENT_LINKING_SHARED -g -O2 -ftemplate-depth=512 -Wno-format-zero-length -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-declarations -g0 -Os -std=c++11 -Wno-error=unused-command-line-argument-hard-error-in-future
```

Which has these problems:

* it's calling `clang` instead of `clang++`
* it's passing in all of `-O3`, `-O2` and `-Os`. It doesn't seem to have made up its mind of which optimization level to use.
* it's passing in `-fwrapv` which is a pessimization. libtorrent nor the python module relies on signed integer overflow.

**Comment by arvidn** [comment]
I recognize that these problems may not have much to do with this patch. I don't know enough about how to build C++ code with distutils though, so I would appreciate any help.

**Comment by se-m** [comment]
Hi @arvidn.
FreeBSD configure build via environment.
E.g. resulting build command looks like this:
```
 HOME=/usr/ports/net-p2p/py-libtorrent-rasterbar/work-py27 \
 PATH=/usr/ports/net-p2p/py-libtorrent-rasterbar/work-py27/.bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/sem/bin \
 NO_PIE=yes \
 MK_DEBUG_FILES=no \
 MK_KERNEL_SYMBOLS=no \
 SHELL=/bin/sh \
 NO_LINT=YES \
 LDSHARED="cc -shared" \
 PYTHONDONTWRITEBYTECODE= \
 PYTHONOPTIMIZE= \
 PREFIX=/usr/local  \
 LOCALBASE=/usr/local  \
 CC="cc" \
 CFLAGS="-O2 -pipe  -DTORRENT_DISABLE_LOGGING -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing "  \
 CPP="cpp" \
 CPPFLAGS="-DLIBICONV_PLUG -isystem /usr/local/include"  \
 LDFLAGS=" /usr/local/lib/libboost_python27.so /usr/local/lib/libiconv.so -fstack-protector-strong " \
 LIBS="-L/usr/local/lib"  \
 CXX="c++" \
 CXXFLAGS="-O2 -pipe -DTORRENT_DISABLE_LOGGING -DLIBICONV_PLUG -fstack-protector-strong -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include "  \
 MANPREFIX="/usr/local" \
 BSD_INSTALL_PROGRAM="install  -s -m 555"  \
 BSD_INSTALL_LIB="install  -s -m 0644"  \
 BSD_INSTALL_SCRIPT="install  -m 555"  \
 BSD_INSTALL_DATA="install  -m 0644"  \
 BSD_INSTALL_MAN="install  -m 444" \
 /usr/local/bin/python2.7 setup.py build
```

Most variables set by FreeBSD port system. For example in CXXFLAGS manually was set only `-DTORRENT_DISABLE_LOGGING`.

I think in MacOS you need to define CXX="clang++" and set proper CXXFLAGS (e.g. add -O2) if you wish to build with plain setup.py.

**Pull request merged**
