### PR TITLE
!): Fix for div Zero crash.

### PR DESCRIPTION
**Pull request by tbfly**
Fix for div Zero crash.

### CODE REVIEW

**Comment by arvidn** [comment]
are you sure this fixes the problem? also, this seems to handle the invalid state rather than avoiding getting into the invalid state in the first place. did you figure out how it gets into this state?

are you sure the difference isn't greater than 1 sometimes?

**Comment by tbfly** [comment]
08-04 15:40:05.715  1976  1976 F DEBUG   : signal 8 (SIGFPE), code -6 (SI_TKILL), fault addr 0x413b
08-04 15:40:05.740  1976  1976 F DEBUG   :     r0 00000000  r1 0000414b  r2 00000008  r3 56697978
08-04 15:40:05.740  1976  1976 F DEBUG   :     r4 56697980  r5 56697930  r6 00000000  r7 0000010c
08-04 15:40:05.740  1976  1976 F DEBUG   :     r8 4d2de980  r9 4b1d0acc  sl 56599000  fp 4d479d13
08-04 15:40:05.740  1976  1976 F DEBUG   :     ip 00000008  sp 56697698  lr 40303eb9  pc 403062b4  cpsr 400f0010
08-04 15:40:05.770  1976  1976 F DEBUG   : 
08-04 15:40:05.770  1976  1976 F DEBUG   : backtrace:
08-04 15:40:05.770  1976  1976 F DEBUG   :     #00 pc 000442b4  /system/lib/libc.so (tgkill+12)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #01 pc 00041eb5  /system/lib/libc.so (pthread_kill+32)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #02 pc 0001b943  /system/lib/libc.so (raise+10)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #03 pc 0027bcf8  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (__aeabi_idiv0+8)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #04 pc 00195293  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN10libtorrent12piece_picker3addEi+106)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #05 pc 00195e25  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN10libtorrent12piece_picker18set_piece_priorityEii+420)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #06 pc 001f0449  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN10libtorrent7torrent17prioritize_piecesERKSt6vectorIiSaIiEE+72)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #07 pc 001f05dd  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN10libtorrent7torrent23update_piece_prioritiesEv+316)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #08 pc 001f0751  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN10libtorrent7torrent16prioritize_filesERKSt6vectorIiSaIiEE+324)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #09 pc 001fb57f  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN5boost3_bi6bind_tIvNS_4_mfi3mf1IvN10libtorrent7torrentERKSt6vectorIiSaIiEEEENS0_5list2INS0_5valueINS_10shared_ptrIS5_EEEENSD_IS8_EEEEEclEv+22)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #10 pc 001fb81b  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN5boost4asio6detail18completion_handlerINS_3_bi6bind_tIvNS_4_mfi3mf1IvN10libtorrent7torrentERKSt6vectorIiSaIiEEEENS3_5list2INS3_5valueINS_10shared_ptrIS8_EEEENSG_ISB_EEEEEEE11do_completeEPNS1_15task_io_serviceEPNS1_25task_io_service_operationERKNS_6system10error_codeEj+66)
08-04 15:40:05.770  1976  1976 F DEBUG   :     #11 pc 001480fb  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN5boost4asio6detail15task_io_service3runERNS_6system10error_codeE+306)
08-04 15:40:05.775  1976  1976 F DEBUG   :     #12 pc 0019f63d  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN5boost4asio10io_service3runEv+32)
08-04 15:40:05.775  1976  1976 F DEBUG   :     #13 pc 0019edcf  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (_ZN5boost4asio6detail12posix_thread4funcINS_3_bi6bind_tIjNS_4_mfi3mf0IjNS0_10io_serviceEEENS4_5list1INS4_5valueIPS8_EEEEEEE3runEv+20)
08-04 15:40:05.775  1976  1976 F DEBUG   :     #14 pc 0014cd1b  /data/app/xxx/lib/arm/libtorrent-rasterbar.so (boost_asio_detail_posix_thread_function+8)
08-04 15:40:05.775  1976  1976 F DEBUG   :     #15 pc 000417b7  /system/lib/libc.so (_ZL15__pthread_startPv+30)
08-04 15:40:05.775  1976  1976 F DEBUG   :     #16 pc 00019243  /system/lib/libc.so (__start_thread+6)


I met this crash, and the fix is for it.

**Comment by tbfly** [comment]
It point to "void piece_picker::add(int index) " line "else new_index = random() % (range_end - range_start + 1) + range_start;"

**Comment by aldenml** [comment]
@tbfly could you tell the context of the error, was it during a download? a partial download? a piece/file priority change?

**Comment by arvidn** [comment]
thanks for the additional information! Presumably, a more reliable fix for the *symptom* would be to clamp *any* condition where end < begin to 0. I would really like to understand how it gets into this state in the first place though, since this is an invariant violation. I recently added more asserts to try to catch this earlier (which might also increase the chances of catching it).

**Comment by tbfly** [comment]
@aldenml  partial download, file priority switch.

**Comment by tbfly** [comment]
I use release version 1.1.0 meet this exception.

**Comment by aldenml** [comment]
@tbfly I think this is the same as https://github.com/arvidn/libtorrent/issues/972 and it links to this. I'm not sure if @arvidn  is willing to accept this PR btw.

**Comment by ssiloti** [comment]
I've tried messing around with file priorities on an active torrent with 1.1.0 and was able to produce an assertion failure which may be related:

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:
version: 1.1.0.0-044ee0f
file: 'piece_picker.cpp'
line: 955
function: void libtorrent::piece_picker::update(int, int)
expression: int(m_priority_boundries.size()) > priority
stack:
1: assert_fail(char const*, int, char const*, char const*, char const*, int)
2: libtorrent::piece_picker::update(int, int)
3: libtorrent::piece_picker::update_piece_state(__gnu_cxx::__normal_iterator<libtorrent::piece_picker::downloading_piece*, std::v
4: libtorrent::piece_picker::set_piece_priority(int, int)
5: libtorrent::torrent::prioritize_pieces(std::vector<int, std::allocator<int> > const&)
6: libtorrent::torrent::update_piece_priorities()
7: libtorrent::torrent::prioritize_files(std::vector<int, std::allocator<int> > const&)
8:
9:
10:
11:
12:
13: clone

I've got a core dump as well which I'm looking into.

**Comment by ssiloti** [comment]
As always the piece picker code is quite mind bending. So far the problem appears to be with a piece which is de-prioritized to zero ("Do Not Download") while being downloaded then re-prioritized to something non-zero.

**Comment by arvidn** [comment]
I think steven figured out the root cause of this bug, or at least an aspect of it (I don't fully understand how the bug steven found will lead to this, but it seems likely it would). I'm closing this PR in favor of https://github.com/arvidn/libtorrent/pull/987 and https://github.com/arvidn/libtorrent/pull/989. This ticket covers the bug https://github.com/arvidn/libtorrent/issues/972

**Pull request closed without merging**
