### PR TITLE
add setting urlseed_max_request_bytes to handle large web seed requests #1405

### PR DESCRIPTION
**Pull request by Falcosc**
Pull for #1405 at master

### CODE REVIEW

**Comment by arvidn** [comment]
is this the same as the other PR for this ticket?

**Comment by arvidn** [comment]
oh, I see. the other one is against RC_1_1

**Comment by Falcosc** [comment]
I hope it was correct to create 2 pull requests to get both branches because I did not find multible pull requests from other user.

**Comment by arvidn** [comment]
if a fix applies to both RC_1_1 and master, just putting it in RC_1_1 is enough, since I periodically merge RC_1_1 into master. However, if the branches have diverged significantly, it may be best fixed with two separate patches

**Comment by Falcosc** [comment]
Ok, I will close it.

**Pull request closed without merging**
