### PR TITLE
don't delete pieces from cache with refcount > 0

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
Do you think this could be "the" reason for the storage crashes?

**Comment by arvidn** [comment]
Not sure. Only if it happens on shutdown probably

**Comment by aldenml** [comment]
shutdown in general, or torrent removal too?

**Comment by arvidn** [comment]
I think the issue this PR addresses is only for full shutdown, where the disk threads terminate

**Pull request merged**
