### PR TITLE
Documentation typos and minor cleanup

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
would you mind rebasing this on top of RC_1_1?

**Comment by aldenml** [comment]
Hi, I rebased on top of RC_1_1, but I don't know how you will solve the conflict. The PR was originally post to master. You tell me.

**Comment by arvidn** [comment]
oh. the pull request still points to master, instead of RC_1_1.. there's no obvious way to edit that on github. do you know?

**Comment by aldenml** [comment]
A quick search in Google reveals that it's not possible, closing and the new one is here: https://github.com/arvidn/libtorrent/pull/420

**Pull request closed without merging**
