### PR TITLE
make the random function produce proper random distributions, based o…

### PR DESCRIPTION
**Pull request by arvidn**
…n uniform_int_distribution of C++11. also clean up piece_picker's priority_range to return two results instead of taking pointers to out-parameters

### CODE REVIEW

**Comment by aldenml** [comment]
I can imagine the struggle with the name `one_past_end` :)

I want to comment that I see in at least eight times that you replaced `random() % num` by `random(num)`. Is that OK?

**Comment by arvidn** [comment]
I did that when the exact range of the random number was not important (or at least not as far as I could tell). Things like generating random port numbers.

**Comment by aldenml** [comment]
Thanks, I didn't want to bother you, just wanted to make sure.

Have you considered removing `randint`?

**Comment by arvidn** [comment]
yes, but I would have to upgrade all the uses of random_shuffle() too, so I was putting that off for this patch

**Pull request merged**
