### PR TITLE
disable use of SetFileValidData() by default (windows).

### PR DESCRIPTION
**Pull request by arvidn**
A new setting allows enabling it.

### CODE REVIEW

**Review by MOZGIII — APPROVED** [review]
LGTM

**Comment by arvidn** [comment]
@FranciscoPombal @cas-- 
Do you think it's reasonable to change this default?
Would you enable `SetFileValidData()` by default in qbt and Deluge?

**Comment by MOZGIII** [comment]
For the record, I'm a qbt user too, and it looks like with my daily usage it's not active either way because I'm not running qbt with admin permissions.
From the perspective of the `libtorrent` user - as long as it's configurable I don't care what the default is :D

**Comment by cas--** [comment]
@arvidn Considering the security issue, I think it's a wise move. Deluge would not expose or change the setting, instead would leave it to power users to optionally change in a 'settings pack' plugin

**Comment by FranciscoPombal** [comment]
@arvidn 

I agree with leaving it OFF by default in libtorrent. qBittorrent is going to leave it hard coded to ON for now, to preserve the previous behavior for people who are running qBittorrent as administrator: https://github.com/qbittorrent/qBittorrent/pull/13355. I believe we are open to change this and/or expose it as an advanced setting in the future, though.

**Pull request merged**
