### PR TITLE
Add a DHT router immediately if its host is an IP address

### PR DESCRIPTION
**Pull request by jpetso**
No resolution or asynchrony is necessary in that case.

Plus two other small fixes for warnings in the same file.

### CODE REVIEW

**Comment by arvidn** [comment]
Is this related to the problem of starting the DHT bootstrap before the DHT routers have resolved? If so, I think it should probably be solved properly by postponing the bootstrap if there are outstanding hostname lookups for dht routers. Or perhaps by re-starting the bootstrap when the first router is added if the routing table is empty. (the latter is probably quite simple)

**Comment by jpetso** [comment]
Yes, that's what it was trying to solve. Note that I previously had a patch that tried to postpone the bootstrap, however because it deferred/queued all DHT calls it also introduced additional complexity. I guess I'll open an issue and close this pull request, as it doesn't seem to be the desired kind of fix.

**Comment by arvidn** [comment]
I would expect that a very common bootstrap server would be "router.utorrent.com", which would be unaffected by this patch.

**Comment by jpetso** [comment]
Yeah. My thinking was that I'd be resolving "router.utorrent.com" myself and then add it & start the DHT only after it's resolved. Clearly there are better fixes for this problem, but maybe not easier-to-implement ones :P

**Pull request closed without merging**
