### PR TITLE
Test merge

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew could you help me interpret this error message:


```
ERROR: Could not find a version that satisfies the requirement libtorrent (from versions: none)
275
ERROR: No matching distribution found for libtorrent
276
ERROR: InvocationError for command /Users/runner/work/libtorrent/libtorrent/.tox/py/bin/python -m pip install --upgrade --force-reinstall --ignore-installed --find-links=dist --no-index libtorrent (exited with code 1)
277
```

This is right after building it.

https://github.com/arvidn/libtorrent/runs/4635839118?check_suite_focus=true#step:13:274

**Comment by arvidn** [comment]
If I bump the mac os deployment target to 11, I get this error instead:

>  ERROR: libtorrent-2.0.5-cp37-cp37m-macosx_11_0_x86_64.whl is not a supported wheel on this platform.

**Comment by AllSeeingEyeTolledEweSew** [comment]
Will investigate. That warning is confusing since `MACOSX_DEPLOYMENT_TARGET` is supposed to be a minimum, maybe it's misleadingly worded

**Comment by arvidn** [comment]
I believe it used to work before merging RC_2_0 into it too

**Pull request merged**
