### PR TITLE
decrease cryptoapi aux::random_bytes() cpu usage

### PR DESCRIPTION
**Pull request by ajax16384**
Every Windows aux::random_bytes calls spent too much time at CryptAcquireContext
````c++
Function Name	Total CPU (%)	Self CPU (%)	Total CPU (ms)	Self CPU (ms)	Module
 - libtorrent::aux::random_bytes	2.92 %	0.00 %	300	0
   - CryptAcquireContextW	2.88 %	0.00 %	296	0	cryptsp.dll
   + CryptReleaseContext	0.04 %	0.00 %	4	0	cryptsp.dll
````

### CODE REVIEW

**Comment by arvidn** [comment]
lgtm. please rebase this on top of master. I believe I just fixed the merge issue causing the tests to fail

**Comment by arvidn** [comment]
hm. it appears I still haven't fixed this. I'll try again tomorrow

**Comment by ajax16384** [comment]
ok. what do you think of moving all make_crypt_provider() to include\libtorrent\aux_\win_util.hpp ?

**Comment by arvidn** [comment]
as far as I can tell, the crypto provider code doesn't use the dll loading code, so maybe it would make more sense to put it in its own header. maybe ``win_cryptoprovider.hpp`` or something like that?

**Comment by ajax16384** [comment]
ok, so i will try to make it in separate pull request.

**Pull request merged**
