### PR TITLE
factor out code from alert_manager::should_post template into non-template

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
question, does this impact the performance?

**Comment by arvidn** [comment]
probably, by generating less code

**Comment by aldenml** [comment]
do you think it worth to have some trick to have that function not inlined?

**Comment by arvidn** [comment]
I think if a compiler thinks it should be inlined, it's probably a good idea. my impression is that compilers are much better at inlining than outlining though, so I think this would help (although, it's a small function and probably only has a negligible impact).

**Pull request merged**
