### PR TITLE
fix error handling of merkle torrents

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by Col-blimp** [comment]
```
version: 1.2.0.0-62cdec8

#: 1
file: 'src\torrent.cpp'
line: 311
function: libtorrent::torrent::torrent
expression: <unconditional>

stack:
 0: 00007FF65C3B0AF7 print_backtrace +311 

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.0.0-62cdec8

#: 1
file: 'src\torrent_info.cpp'
line: 577
function: libtorrent::torrent_info::torrent_info
expression: m_piece_hashes

stack:
 0: 00007FF65C3B0AF7 print_backtrace +311 

assertion failed. Please file a bugreport at https://github.com/arvidn/libtorrent/issues
Please include the following information:

version: 1.2.0.0-62cdec8

#: 2
file: 'src\torrent_info.cpp'
line: 604
function: libtorrent::torrent_info::torrent_info
expression: m_piece_hashes >= m_info_section.get()

stack:
 0: 00007FF65C3B0AF7 print_backtrace +311 
```

You get the above  with this patch arvidn.

**Comment by arvidn** [comment]
is there a specific torrent you're trying to load that triggers this?

**Comment by Col-blimp** [comment]
No just a random folder that happened to be on the desktop that I created a torrent from.

**Comment by arvidn** [comment]
do you get all those 3 asserts on separate torrents? or are you building with production-asserts and you get them all in a single run? (if the latter, I think only the first one is relevant).

Second, as far as I can tell, you're trying to open a merkle torrent without providing the merkle tree itself. Is that right?

could you share the torrent file that triggers this assert?

**Comment by Col-blimp** [comment]
[libtorrent master merkle torrent.zip](https://github.com/arvidn/libtorrent/files/1632035/libtorrent.master.merkle.torrent.zip)

Adding the .torrent to the session with no .merkle file gives you this:

```
version: 1.2.0.0-62cdec8


#: 1
file: 'src\torrent.cpp'
line: 311
function: libtorrent::torrent::torrent
expression: <unconditional>

stack:
 0: 00007FF762840A97 print_backtrace +311 
```

then restarting the session and adding back the torrent from the resume file (`handle.save_resume_data(torrent_handle::save_info_dict)`) gives you this:

```
version: 1.2.0.0-62cdec8

#: 1
file: 'src\torrent_info.cpp'
line: 577
function: libtorrent::torrent_info::torrent_info
expression: m_piece_hashes

stack:
 0: 00007FF762840A97 print_backtrace +311 

version: 1.2.0.0-62cdec8

#: 2
file: 'src\torrent_info.cpp'
line: 604
function: libtorrent::torrent_info::torrent_info
expression: m_piece_hashes >= m_info_section.get()

stack:
 0: 00007FF762840A97 print_backtrace +311 
 1: 00007FF76284082B assert_fail +107 
 2: 00007FF762844C9F libtorrent::torrent_info::torrent_info +975 
 3: 00007FF762700C79 restore_torrent +4025 c:\...\test-client\source\client_functions.cpp:3088
 4: 00007FF762701AAD get_restored_torrents +2285 c:\...\test-client\source\client_functions.cpp:3188
 5: 00007FF762737128 test-client::frame::setup +1144 c:\...\test-client\source\test-client.cpp:126
 6: 00007FF762749202 test-client::main_frame::main_frame +450  c:\...\test-client\source\test-client.cpp:1855
 7: 00007FF762755D14 wWinMain +1364 c:\...\test-client\source\main_functions.cpp:865
 8: 00007FF762AB6B4A __scrt_common_main_seh +266  f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
 9: 00007FFD25B31FE4 BaseThreadInitThunk +20  
10: 00007FFD25C6EFB1 RtlUserThreadStart +33  
```

So the above would be in the case that you got the merkle .torrent but you need to merkle tree sent to you.

Now below you have both the .torrent and the .merkle file and you call:

```
add_torrent_params p;
p.ti->set_merkle_tree(tree);
```
to set the tree before calling `async_add_torrent` and you get the following once added to the session:

```
version: 1.2.0.0-62cdec8

#: 1
file: 'src\torrent.cpp'
line: 311
function: libtorrent::torrent::torrent
expression: <unconditional>

stack:
 0: 00007FF687941637 print_backtrace +311 
```

then again after saving off the resume data that includes the `save_info_dict` plus the merkle tree you get this when starting the session again and adding back the resume:

```
version: 1.2.0.0-62cdec8

#: 1
file: 'src\torrent_info.cpp'
line: 577
function: libtorrent::torrent_info::torrent_info
expression: m_piece_hashes

stack:
 0: 00007FF687941637 print_backtrace +311 

version: 1.2.0.0-62cdec8

#: 2
file: 'src\torrent_info.cpp'
line: 604
function: libtorrent::torrent_info::torrent_info
expression: m_piece_hashes >= m_info_section.get()

stack:
 0: 00007FF687941637 print_backtrace +311 
 1: 00007FF6879413CB assert_fail +107 
 2: 00007FF6879456AF libtorrent::torrent_info::torrent_info +975 
 3: 00007FF68780104F restore_torrent +4031 c:\...\test\source\client_functions.cpp:3125
 4: 00007FF687801E7D get_restored_torrents +2285 c:\...\test\source\client_functions.cpp:3225
 5: 00007FF687837BB8 test::frame::setup +1144 c:\...\test\source\test.cpp:126
 6: 00007FF687849C92 test::main_frame::main_frame +450  c:\...\test\source\test.cpp:1855
 7: 00007FF6878567A4 wWinMain +1364 c:\...\test\source\main_functions.cpp:865
 8: 00007FF687BB73EA __scrt_common_main_seh +266  f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283
 9: 00007FFD25B31FE4 BaseThreadInitThunk +20  
10: 00007FFD25C6EFB1 RtlUserThreadStart +33  
```
Here is the resume file created by `handle.save_resume_data(torrent_handle::save_info_dict)` that has the merkle info added:

[0c706124a0cf74669ecc46ba8f28cdef489eb16b.zip](https://github.com/arvidn/libtorrent/files/1632148/0c706124a0cf74669ecc46ba8f28cdef489eb16b.zip)

as far as I can tell in the bencode editor it looks like any non merkle resume file should.

**Comment by arvidn** [comment]
those zipfiles are not compatible with ``unzip`` :/

**Comment by Col-blimp** [comment]
https://nofile.io/f/gnnA8cprWeE/libtorrent+master+merkle+torrent.tar

Here is a .tar, 7zip only lets you make .zip .7z or .tar,

**Comment by arvidn** [comment]
I cannot reproduce any asserts by just loading that torrent file. Is it important to load the resume file as well?

**Comment by Col-blimp** [comment]
This is on Windows (should have said that really), on my setup I don't bother managing .torrent files as you can just create one on demand that has relevant trackers and web seeds so it's important to me but I'm not sure if any other client does this.

It might be something stupid, Libtorrent is built with Merkle support and I know this works as I can create Merkle torrents, included is `libtorrent/aux_/merkle.hpp` and I can build Libtorrent and the client without errors or warnings, anything else needed?

**Pull request merged**
