### PR TITLE
fix race when two threads are opening the same file

### PR DESCRIPTION
**Pull request by arvidn**
one for reading and one for writing, and the writing thread loses the race

### CODE REVIEW

**Comment by arvidn** [comment]
one concern is that; imagine the writer thread loses the race, the read-only file is left in the `file_view_pool`.

1. The reader reads some part of the file (we're guaranteed that it won't be reading anything overlapping what the writer is about to write).
2. The writer writes to its own file and closes it as it goes out of scope.
3. Imagine another job now comes in to read the bytes just written in step 2. It will pick up the read-only file mapping from the `file_view_pool` and look there. Will the bytes written in step 2 be visible in the read-only mapping? I don't think it would be on linux. The views would have different virtual addresses.

It seems safer to me to have the "stronger" file always win. i.e. if a read-write file loses, and the existing file is read-only, it overwrites the file in the pool.

**Comment by arvidn** [comment]
I added a commit that implements a slightly different approach.

> the first lookup is only used if the open-mode is a match, otherwise we always move on to opening the file. The second lookup/insert replaces the entry if the existing one has the wrong open-mode.

I think this might be safer since subsequent *reads* will use the same mapping that was used to write.

I'm starting to think that there probably should be a stress test for the disk I/O, to catch things like this

**Comment by MassaRoddel** [comment]
Just a thought ...
If several threads (running in parallel on different cores) use the same memory mapped files doesn't that have a bad impact on the cpu core caches because they have to be synchornized?

**Comment by arvidn** [comment]
> If several threads (running in parallel on different cores) use the same memory mapped files doesn't that have a bad impact on the cpu core caches because they have to be synchornized?

I would not expect so. Threads never overlap *writes*, and threads should already be synchronizing from a write to reading the same block. Once a block is written, it's immutable, so from that point it's fine for it to exist in multiple caches, reading won't invalidate another core's cache.

**Comment by arvidn** [comment]
@MassaRoddel can you still reproduce the issue with this patch?

**Comment by MassaRoddel** [comment]
It seems to be fixed.

**Pull request merged**
