### PR TITLE
use /dev/random as random number source on macOS

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
Well, this PR have a few unintended consequences :)

now it requires `libssl` if using `libcrypto` due to missing `SSL_library_init` and others....

**Comment by arvidn** [comment]
I see. perhaps I misunderstand the libcrypto error handling. is ``ERR_get_error()`` a libssl call?
Do I need a separate error_category for libcrypto?

**Comment by aldenml** [comment]
looking at it (to fix it), can't say anything yet

**Comment by aldenml** [comment]
see comments at https://github.com/arvidn/libtorrent/pull/1570

**Comment by arvidn** [comment]
the reason libssl ended up being pulled in was because I assumed the ssl error_category from boost.asio was the appropriate one

**Comment by aldenml** [comment]
just arrived to the same conclusion :)

**Pull request merged**
