### PR TITLE
removed buffer::interval

### PR DESCRIPTION
**Pull request by aldenml**
This is soft PR, it's just a refactor to eliminate what I think is a redundant type. If you have something else in mind, feel free to discard/close it.

### CODE REVIEW

**Comment by arvidn** [comment]
I like the spirit of this. I think the const_interval could also be replaced though. I'm also not sure about the replacement. Do you think there are good reasons not to use array_view instead?
I could even imagine using array_view instead of asio::mutable_buffer and asio::const_buffer (and create overloads for buffer_cast<>() and buffer_size(), but I'm not sure what that would look like exactly).

**Comment by aldenml** [comment]
Removing `const_interval` is my second step if you accept this PR. I like `array_view` but the template nature of it keep me worried about more use of it in public API. Maybe if you create an specialized child type with a proper `TORRENT_EXPORT` macro, I would be more confortable.

btw, could you restart this: https://travis-ci.org/arvidn/libtorrent/jobs/138946951

**Comment by arvidn** [comment]
what do you mean by "child type"? lots of template classes are used in the API.. std::vector, boost::optional and std::chrono::steady_clock::time_point/time_duration for instance. what specifically is your concern? that a DLL might instantiate and export part of it, while a client uses the header file, getting a duplicate definition?

**Comment by aldenml** [comment]
I mean something along the lines of `struct TORRENT_EXPORT buffer_view : array_view<int8_t>`.

Remember that my point of view here is more from outside C++ and how to integrate with the native library. `std::vector` is so used (and abused) that a lot of special cases are made to handle this template, and the others you mention are a little problematic to represent (including tuple). I rather research a little more before give an opinion in the duplicate definition issue.

What do you think is the issue with the failed travis job? could it be related to this change?

**Comment by aldenml** [comment]
Hi, do you want me to do something else here?

**Comment by arvidn** [comment]
I'm not sure about using the boost asio type. I feel like using the array_view would be more appropriate (since it's more generic). In fact, it may even make sense to replace the asio buffers with array_view (and add buffer_cast<>() and buffer_size() overloads for it). Now, I haven't seen what it would look like, so I can't say for sure I necessarily will like it. But in general, I think it's a good idea to coalesce these types that basically do the same thing. The DHT has it's own version too (but just uses std::pair<char*, int>)

**Comment by aldenml** [comment]
Ok, I think I can workaround `array_view` in swig, maybe you should move it out of `aux` namespace. Is that ok?

**Comment by arvidn** [comment]
yeah, I will try to replace it with a typedef of boost's multi array view. hopefully this weekend

**Comment by arvidn** [comment]
I would imagine you could bind specific template instantiations in swig, no?

**Comment by aldenml** [comment]
Yes, I can do that (it could get a little tricky if the template is not simple). Closing this.

**Pull request closed without merging**
