### PR TITLE
Fix Jamfile in libdatachannel

### PR DESCRIPTION
**Pull request by paullouisageneau**
Fixes https://github.com/arvidn/libtorrent/issues/4855

The PR updates libdatachannel to build its dependencies usrsctp and libjuice with the correct variant and in different directories for different build configurations.

### CODE REVIEW

**Comment by aldenml** [comment]
@paullouisageneau do you know how to pass `MINGW` when building with Jamfile? I'm having problems because  this line is not called
```
target_compile_definitions(usrsctp-static PUBLIC -DSCTP_STDINT_INCLUDE=<stdint.h>)
```

**Comment by paullouisageneau** [comment]
@aldenml Setting `toolset=gcc-mingw` in the `b2` command should set `MINGW`.

**Comment by aldenml** [comment]
I was using another toolset (btw, I'm compiling for windows with mingw-w64 under linux), I will try your suggestion and report back, thanks

**Comment by arvidn** [comment]
I'm open to suggestions on how to avoid `Werror` to apply to dependencies. https://ci.appveyor.com/project/arvidn/libtorrent/builds/34029852/job/6quhfabxod3397e1#L381

**Comment by paullouisageneau** [comment]
@arvidn Sadly I don't know how to do that in Jamfiles, I'm fixing the warning for now.

**Comment by arvidn** [comment]
https://ci.appveyor.com/project/arvidn/libtorrent/builds/34037634/job/5ikp9etowhrfyahj#L1230

it looks like perhaps some mixup in where `libusrsctp.lib` is supposed to end up.

**Comment by arvidn** [comment]
tested that this works now:

```
b2 -j30 -l250 crypto=openssl webtorrent=on variant=release,debug
```

However, this still fails:

```
b2 -j30 -l250 crypto=openssl,gnutls webtorrent=on
```

It would be nice if gnutls vs. openssl was also represented in the build directory. I haven't dug into which library is causing this, but I imagine it's one of the ones built outside of boost-build.

This is the error I get (when the initial build was with gnutls):

```
/usr/bin/ld: libtorrent.so.2.0.0: undefined reference to `nettle_hmac_sha1_set_key'
/usr/bin/ld: libtorrent.so.2.0.0: undefined reference to `nettle_hmac_sha1_digest'
/usr/bin/ld: libtorrent.so.2.0.0: undefined reference to `nettle_hmac_sha1_update'
```

**Comment by paullouisageneau** [comment]
This seems to be caused by libjuice. Strangely, openssl/gnutls is now represented in the build directory, so I guess this is a problem with it not being registered as a different build by b2. I'll look into it.

**Pull request merged**
