### PR TITLE
fix directory creation on windows shared folders

### PR DESCRIPTION
**Pull request by arvidn**
commit on behalf of FletcherD

### CODE REVIEW

**Review by glassez — APPROVED** [review]

**Comment by arvidn** [comment]
@glassez did you test this on a real windows system downloading to a network share?

**Comment by glassez** [comment]
> @glassez did you test this on a real windows system downloading to a network share?

Sorry, no. I'm just glad that such a non-obvious cause of the problem has been discovered and (most likely) fixed.

**Comment by arvidn** [comment]
@FletcherD would you mind testing this patch to ensure I didn't break anything from your original patch?

**Comment by FletcherD** [comment]
> @FletcherD would you mind testing this patch to ensure I didn't break anything from your original patch?

Apologies, just got a chance to do this. It works great for me.

**Pull request merged**
