### PR TITLE
fix missing header in test_fast_extension.cpp

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by FranciscoPombal** [comment]
@arvidn Will you tag 1.2.9 after this?

**Comment by arvidn** [comment]
yes, that's my hope

**Comment by FranciscoPombal** [comment]
:+1:, don't forget the missing entries in the changelog

**Comment by arvidn** [comment]
do you want to propose some?

**Comment by arvidn** [comment]
does this look good? https://github.com/arvidn/libtorrent/pull/5021

**Pull request merged**
