### PR TITLE
don't support c++98 anymore

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by ssiloti** [comment]
So does this mean are we free to use C++11 features in PRs now?

**Comment by arvidn** [comment]
That's my idea at least (but travis and appveyor will fail until this is merged). I was going to ask people on the mailing list if anyone thought this would be a problem.

**Comment by glassez** [comment]
+1 (с++11)

**Comment by cas--** [comment]
Could this be an issue for python bindings linking against Python 2.7 as it is built with msvc 9.0?

**Comment by arvidn** [comment]
yes, probably. From what I understand though, current versions of python build with msvc-14.0 (2015) and uses its ABI.

**Pull request merged**
