### PR TITLE
fix issue resuming 1.0.x downloads with a file priority 0

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
This PR is related I think so I'll state my problem here.
It isn't easy to replicate but I encounter a problem with multi-file torrents occasionally.
1. Download **some** files from a multi-file torrent completely.
2. Then set 0 priority to one of them. Make sure that this file shares edge pieces with another one.
3. Start seeding.
4. When an edge piece from the 0 priority file is requested `file_error_alert` is reported. The `message()` of the alert returns this:
```
<torrent name> partfile read (<path to 0 priority file>) error: No such file or directory
```
Notice that although it talks about partfile read it points to the requested file instead.
Because I don't trigger the bug often and easily my step 4 observations might be off. For example, it might be triggered because it tries to **uncoditionally** look into the parts file for 0 priority files even if they are downloaded fully and regardless if an edge piece is requested.

**Another quirk about qbt:** When a user unselects a file(0 priority) we call `torrent_handle::rename_file()` on that file moving it into a hidden subdirectory called `.unwanted`. That's where the alert points to (along with the filename).

@arvidn it would be nice if you could check the code to verify if it does "the right thing" in the above scenarios too.

**Comment by arvidn** [comment]
I believe libtorrent does not do the right thing in this case. the logic to find the block is tied to the file priority. If the file priority changes, it expects to find the block in a different place. But as you may have noticed, importing files into the part file is not supported.

**Comment by arvidn** [comment]
I think this patch as-is though, still is a useful improvement over the current behavior, especially when upgrading.

**Comment by sledgehammer999** [comment]
>I think this patch as-is though, still is a useful improvement over the current behavior, especially when upgrading.

Ok, then consider at least merging this PR today. I am planning to do a release myself so it would be nice if I could include this. (I build libtorrent RC_1_1 for windows/macOS release, and for Ubuntu PPA).

Unless, you aren't yet confident in this PR. I don't want to rush you.

**Comment by sledgehammer999** [comment]
@arvidn I should have run it earlier. Anyway, today as I prepared my new release I used latest RC_1_1 and then did a test run on my machine using my torrents.
2 of them came back with 0% progress as if the fastresume was rejected. I force rejected and they went to 100%. After client restart same problem. Even though it looks like a fastresume rejection I don't the relevant alert.
In any case, I test with this commit and the previous one. This is the offending one. The previous commit doesn't reject the fastresume after client restart.

Unfortunately one of the torrents during the downgrade finished as 99% and I can seem to get the rest of pieces from peers. The other one still fine. But I fail to see any connection between the 2. Both of them were multifile torrents with some files unselected(0 priority).

How should I proceed with this? Any idea why a fastresume rejection alert isn't posted?

**Comment by arvidn** [comment]
ok, so basically you're seeing the same behavior as documented here: https://github.com/arvidn/libtorrent/issues/2674#issuecomment-364246854

I'll take a look.

**Pull request merged**
