### PR TITLE
[Bindings/Py] Add missing move_flags_t to torrent_handle

### PR DESCRIPTION
**Pull request by cas--**
I think this is the correct fix for missing flags

### CODE REVIEW

**Comment by arvidn** [comment]
would you mind making sure this fix is in master too?

**Comment by cas--** [comment]
Sure but is it not quicker for you to cherry-pick the commit between the branches?

**Comment by arvidn** [comment]
cherry pick doesn't work. It especially doesn't work in this repository because it was imported from subversion, so the connection between the branches isn't really what git expects (I assume svn2git isn't perfect). It also still needs to be staged in via a branch and a pull request, to make sure nothing breaks

**Comment by cas--** [comment]
That's fine I'll create the pull request, understand wanting to have it run through continuous integration.

I have to disagree though about cherry pick, divergent branch history is the use-case for it, I'm constantly using it between our divergent stable and develop branches and when creating the pull requests for the libtorrent master branch. Obviously as exemplified with this very commit, it often requires resolving a merge conflict but that's is basically unavoidable.

**Comment by arvidn** [comment]
in my experience:

git show <hash> | patch -p1

is much more likely to work and do what I expect than:

git cherry-pick <hash>

cherry pick has a tendency to pull in other changes than the one the hash refers to. Perhaps I'm just expecting it to be a different feature

**Pull request merged**
