### PR TITLE
undeprecate the upnp_ignore_nonrouters setting

### PR DESCRIPTION
**Pull request by arvidn**
with a slightly different meaning. still default to false and make it mean to ignore routers outside of the local subnet

### CODE REVIEW

**Comment by iz8mbw** [comment]
Hi @arvidn 
I can confirm this patch works well both for local router and remote UPnP "server".
I have tested it with qBittorrent in these scenarios:

1. Local router in LAN (router/default gateway in LAN)
2. Remote UPnP "server" outside LAN (example a VPN scenario)

Thank you very much!

**Comment by arvidn** [comment]
thanks for testing!

**Comment by iz8mbw** [comment]
> thanks for testing!

does this patch will be included in libtorrent 1.2.7?
Thank you!

**Comment by arvidn** [comment]
yes

**Pull request merged**
