### PR TITLE
hold an owning reference to storage objects in try_flush_write_blocks

### PR DESCRIPTION
**Pull request by ssiloti**
It is possible for all other references to a storage object to be
destroyed while try_flush_write_blocks is running. If the storage is
destroyed then find_piece will crash when trying to re-aquire the
shared_ptr. To prevent this, keep the storage alive by holding a
shared_ptr to it in try_flush_write_blocks.

Normally the fence job when stopping a torrent would prevent the storage
object from being destroyed until all flush jobs are complete.
try_flush_write_blocks can be run after every disk job though so it has
the potential to "stradle the fence".

If the associated torrent does get unloaded then it is expected that
find_piece will return NULL thus causing the entry to be ignored.

### CODE REVIEW

**Comment by aldenml** [comment]
do you think that this could be the root of weird memory crashes related to the storage IO? (there are at least two of them in the issues)

**Comment by ssiloti** [comment]
I see #2140 and #2089 which I don't think are related to this because they involves a regular flush piece request. Did you have any others in mind?

**Comment by aldenml** [comment]
they are the ones, I was just asking, because sometimes memory errors manifest in a strange ways

**Comment by arvidn** [comment]
good catch!

**Pull request merged**
