### PR TITLE
use can_disconnect in bt_peer_connection upload-to-upload connection

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@joriscarrier would you mind testing this patch to make sure it works for you?

**Comment by joriscarrier** [comment]
> @joriscarrier would you mind testing this patch to make sure it works for you?

i will do that

**Comment by joriscarrier** [comment]
test in progress (i think is missing an other can_disconnect: #6318)

**Comment by joriscarrier** [comment]
@arvidn for me it is good, I do not see any other case.

**Pull request merged**
