### PR TITLE
cleanup CMakeLists.txt for python bindings

### PR DESCRIPTION
**Pull request by Kolcha**
see commits messages for detailed description

### CODE REVIEW

**Review by arvidn — APPROVED** [review]
the only way I can judge the correctness of this is by the tests, but it seems reasonable

**Comment by arvidn** [comment]
I don't think there are any tests exercising this path thought, are there?

**Comment by Kolcha** [comment]
from my point of view there is nothing to test, these changes affect only python-specific metadata which can be used by `pip` and maybe some other tools (at least `pip list` can display `libtorrent  2.0.5` if this metadata present alongside library itself).
I decided to fix this just because it waas annoying to version like this `2.0.5-usr-src-packages-BUILD-bindings-python` (real example from build server I'm using) and I noticed the warning from python tools noticed on one of commits

**Comment by arvidn** [comment]
building the python bindings using cmake is a feature that isn't exercised by the CI (as far as I can tell), and if this breaks it, I can't tell. If it was exercised by CI, I *could* tell. That's what I mean by not being covered by a test.

**Pull request merged**
