### PR TITLE
revert to use Boost variables  in CMakeLists.txt

### PR DESCRIPTION
**Pull request by aldenml**
See https://github.com/arvidn/libtorrent/pull/2938/files#r185007457 for more information

### CODE REVIEW

**Comment by arvidn** [comment]
isn't it odd that `Boost::system` doesn't work though? that library has been around for almost 10 years!

**Comment by aldenml** [comment]
yes, it's odd, not sure if having boost from source (and not installed via brew) is a factor. I can hack my environment, but this way seems to works in any situation.

**Comment by arvidn** [comment]
does the `Boost_LIBRARIES` variable contain every boost library?

**Comment by arvidn** [comment]
it looks like `Boost_LIBRARIES` aren't *targets*, and that you have to add the include directory manually as well.

**Comment by aldenml** [comment]
I believe it's only the ones resolved by `find_package(Boost REQUIRED COMPONENTS system)`

**Comment by arvidn** [comment]
https://ci.appveyor.com/project/arvidn/libtorrent/build/8987/job/k0qf0mj7poaur8vh#L1121

**Comment by aldenml** [comment]
I'm adding `target_include_directories(torrent-rasterbar PUBLIC ${Boost_INCLUDE_DIRS})` but I'm open to a better solution

**Comment by evsh** [comment]
You might want to consider `Boost_SYSTEM_LIBRARY` variable as well as making the same changes in `bindings/python/CMakeLists.txt`

**Comment by aldenml** [comment]
@evsh I appreciate some help with that (or even a PR to my branch) since I'm not familiar with the python build part, and I know very little of `cmake`.

**Comment by evsh** [comment]
I suggest (please note those variable names are case sensitive):
```cmake
target_include_directories(torrent-rasterbar PUBLIC {Boost_INCLUDE_DIRS})
target_link_libraries(torrent-rasterbar PUBLIC ${Boost_SYSTEM_LIBRARY})
```
and then in `bindings/python/CMakeLists.txt` instead of `target_link_libraries(python-libtorrent Boost::${boost-python-module-name})` you write 
```cmake
string(TOUPPER "${boost-python-module-name}" boost_python_module_name_uppercase)
target_link_libraries(python-libtorrent ${Boost_${boost_python_module_name_uppercase}_LIBRARY})
```

You may want to use
```cmake
include(CMakePrintHelpers)
cmake_print_properties(TARGETS python-libtorrent
	PROPERTIES LINK_LIBRARIES)
```
to check afterwards that everything is OK.

**Comment by aldenml** [comment]
interesting...I will explore that, thanks

**Comment by evsh** [comment]
Sorry for breaking your workflow with those imported targets.

**Comment by arvidn** [comment]
lgtm. would you mind squashing this?

**Comment by aldenml** [comment]
sure, I will wait for the completion of CIs

**Pull request merged**
