### PR TITLE
updated libsimulator module reference

### PR DESCRIPTION
**Pull request by aldenml**
I believe this was pushed in some commit in `RC_1_1` but maybe it was lost in the merge

### CODE REVIEW

**Comment by arvidn** [comment]
I did not deliberately update the submodule in RC_1_1, but submodules are notoriously "sticky" and switching branch back and forth can easily cause accidental updates I've noticed.

**Comment by arvidn** [comment]
on a side note; do you know if there's a way to make ``travis_retry`` wait longer in between retries?

**Comment by aldenml** [comment]
agree, I will close this

**Comment by aldenml** [comment]
no idea, I was asking myself the same :)

**Pull request closed without merging**
