### PR TITLE
improve handling of filesystems not supporting fallocate()

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by Raitsa** [comment]
Thank you very much @arvidn but no luck.

A helpful guy, livingsilver94 in #Solus-chat in Freenode, compiled libtorrent with the patch, I applied it to my Solus and fired up qbittorrent and started downloading a 805 mb file, got to 66.1% and then i/o error again.

Here is the patched libtorrent if anyone wants to try it out:
https://mega.nz/#!ut5iWSjI!CXIS6pblzAhBpVBOvyBRduOLxoVu3CaDC-SO5ygsNSw

(N) 2018-08-19T23:45:18 - qBittorrent v4.1.2 started
(N) 2018-08-19T23:47:00 - qBittorrent v4.1.2 started
(N) 2018-08-19T23:47:00 - 'If.I.Leave.Here.Tomorrow.A.Film.About.Lynyrd.Skynyrd.2018.HDTV.x264-aAF [ettv]' added to download list.
(N) 2018-08-19T23:48:03 - An I/O error occurred, 'If.I.Leave.Here.Tomorrow.A.Film.About.Lynyrd.Skynyrd.2018.HDTV.x264-aAF[ettv]' paused. If.I.Leave.Here.Tomorrow.A.Film.About.Lynyrd.Skynyrd.2018.HDTV.x264-aAF[ettv] open (/run/user/1000/gvfs/smb-share:server=192.168.0.120,share=ladatut/If.I.Leave.Here.Tomorrow.A.Film.About.Lynyrd.Skynyrd.2018.HDTV.x264-aAF[ettv]/If.I.Leave.Here.Tomorrow.A.Film.About.Lynyrd.Skynyrd.2018.HDTV.x264-aAF[ettv].mkv) error: Operation not supported

**Comment by arvidn** [comment]
that output looks like the previous version. I fixed a separate issue where errors were ascribed to `open()` where it really was some other call failing. I find it hard to believe that `open()` is failing for you, and with the patch it would say something else.

are you sure you don't have another version of `libtorrent.so` installed somewhere?
(the new build should be ABI compatible with the 1.1.x release, so you shouldn't actually need to rebuild qbt)

**Comment by Raitsa** [comment]
Hopefully this was the right way to add the patch:

http://i.imgur.com/YkEuCr5.png

This is what my search finds:
http://i.imgur.com/Ok1Oafa.png

I have another spare PC too which has a fresh install of Solus in it with no libtorrent or qbittorent in it yet.

**Comment by arvidn** [comment]
that first screenshot doesn't seem to be applying any patch

**Comment by Raitsa** [comment]
Yeah this is my 2nd week in Linux so I dont really know my way around these things well enough.

I've got Teamviewer installed though if you want make sure things are done the right way...

**Comment by Raitsa** [comment]
Is there some sort of newbie enough way I could help out regarding this issue?

**Comment by JoshStrobl** [comment]
Sorry to necro the PR @arvidn, I've backported this our libtorrent-rasterbar package (1.1.9) on Solus (unstable repo) so @Raitsa can test it. Thanks for the quick response :+1: https://dev.solus-project.com/R1871:f4d44da8bb810d8e96a43d9750159d199181f3bc

**Comment by Raitsa** [comment]
Thank you both very much.

After testing the patch in Solus with the invaluable help of @JoshStrobl , I am sad to report that the same error still pops out on 2 oif the 3 torrents i tried, each sized around 1Gib.

(N) 2018-08-22T17:05:54 - qBittorrent v4.1.2 started
(N) 2018-08-22T17:05:55 - 'Solus-3-Budgie.iso'' added to download list.
(N) 2018-08-22T17:07:14 - An I/O error occurred, ''Solus-3-Budgie.iso' paused. Solus-3-Budgie.iso'open (/run/user/1000/gvfs/smb-share:server=192.168.0.120,share=ladatut/Solus-3-Budgie.iso') error: Operation not supported

**Pull request merged**
