### PR TITLE
moved socket_io.hpp to aux

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by aldenml** [comment]
a long one :)

**Comment by arvidn** [comment]
do you understand why the file shows up as deleted and added, rather than renamed? I'm a bit worried about potential changes to the file in RC_2_0 not merging cleanly into master.

**Review by arvidn — APPROVED** [review]

**Comment by aldenml** [comment]
Yes, it’s because I indented to the left most of the file, git rename threshold seems higher. If that’s a problem, let me know and I add the `\t`s back

**Comment by arvidn** [comment]
I'm sure it's fine. hopefully changes in `RC_2_0` will have tests anyway, to fail if they don't merge correctly

**Pull request merged**
