### PR TITLE
fix issue where stop-when-ready would not close files

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by summerqB** [comment]
@arvidn could you kindly backport this to RC_1_2 as the issue was present there as well.

**Comment by xavier2k6** [comment]
>could you kindly backport this to RC_1_2 as the issue was present there as well.

@arvidn gentle ping.

**Comment by arvidn** [comment]
I'll add this to the list before next release

**Comment by arvidn** [comment]
@xavier2k6 would you be able to test this? https://github.com/arvidn/libtorrent/pull/7134
it doesn't have great test coverage.

**Comment by xavier2k6** [comment]
> @xavier2k6 would you be able to test this? #7134 it doesn't have great test coverage.

Will try get to it tomorrow, @summerqB can you verify in the meantime or do you need a windows build provided?

**Pull request merged**
