### PR TITLE
account for partially downloaded pieces when announcing as a seed

### LINKED ISSUE #3008: Downloaded bytes in event=completed announce more than in the next announce
libtorrent version (or branch):
RC 1.1 8808eb7

platform/architecture:
Windows 1803 x64 (qBittorrent 4.1.0)

Some trackers are not properly reported the uploaded quantity because they are not take the first announce after the download completed. We tracked down the root cause of this issue. The downloaded bytes in the 1st announce (when the download completed) is more than in the next announce.
related qbittorrent issue: https://github.com/qbittorrent/qBittorrent/issues/8849

example:

event=completed announce: downloaded bytes= 5228289362
letotlesvege

next announce: downloaded bytes= 5228224536 (this is the real file size)
elsoannounce

### PR DESCRIPTION
**Pull request by ssiloti**
Fixes #3008

### CODE REVIEW

**Comment by sledgehammer999** [comment]
For anyone wanting to test here is a build of qbittorrent v4.1.0 using this PR.
Link: https://builds.shiki.hu/temp/qbittorrent_4.1.0_x64_libt_PR_3025.7z

**Comment by Lash78** [comment]
@sledgehammer999 : Just made some quick tests, it looks good. The downloaded bytes are match, and the tracker has properly accounted the uploaded and downloaded quantity.

**Comment by erasmux** [comment]
Yes this seems to solve the problems I was experiencing.
Good job, thank you :clap:

**Comment by x9248** [comment]
Stats are being reported correctly on IPT. Nice work guys!

**Comment by Thefrank** [comment]
Checking this under FreeBSD right now. Will report if there are still issues.

**Pull request merged**
