### PR TITLE
version to 1.2

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
please use the python tool set_version.py to update all places where the version is specified (like in the documentation)

**Comment by aldenml** [comment]
ok, let me see it

**Comment by aldenml** [comment]
@arvidn, in appveyor `The process cannot access the file because it is being used by another process.` is a new one. Any hint?

**Comment by arvidn** [comment]
I've seen that in the past too, I don't think your patch affected it. It's on my list to take a look at.

**Pull request merged**
