### PR TITLE
remove use of deprecated function readdir_r

### LINKED ISSUE #2172: readdir_r is deprecated
libtorrent version (or branch): **master**

platform/architecture: **Linux**

compiler and compiler version: **gcc 6.2, libc 2.24**

```
file.cpp: In member function ‘void libtorrent::directory::next(boost::system::error_code&)’:
file.cpp:423:7: warning: ‘int readdir_r(DIR*, dirent*, dirent**)’ is deprecated [-Wdeprecated-declarations]
   if (readdir_r(m_handle, &m_dirent, &dummy) != 0)
       ^~~~~~~~~
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:502,
                 from /usr/include/c++/6/cstddef:49,
                 from /usr/include/boost/config/compiler/gcc.hpp:165,
                 from /usr/include/boost/config.hpp:39,
                 from ../include/libtorrent/config.hpp:40,
                 from file.cpp:33:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
file.cpp:423:44: warning: ‘int readdir_r(DIR*, dirent*, dirent**)’ is deprecated [-Wdeprecated-declarations]
   if (readdir_r(m_handle, &m_dirent, &dummy) != 0)
                                            ^
In file included from /usr/include/features.h:364:0,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/6/bits/c++config.h:502,
                 from /usr/include/c++/6/cstddef:49,
                 from /usr/include/boost/config/compiler/gcc.hpp:165,
                 from /usr/include/boost/config.hpp:39,
                 from ../include/libtorrent/config.hpp:40,
                 from file.cpp:33:
/usr/include/dirent.h:189:12: note: declared here
 extern int __REDIRECT (readdir_r,
            ^
```

### PR DESCRIPTION
**Pull request by ssiloti**
Fixes #2172

### CODE REVIEW

**Comment by arvidn** [comment]
lgtm

**Comment by aldenml** [comment]
Hi @ssiloti (or @arvidn), I just want to confirm that potential thread issues (if applicable) were considered in this change, per doc:

>  In cases where multiple threads must read from the same directory stream,
using readdir(3) **with external synchronization** is still preferable to the use of readdir_r()

**Comment by ssiloti** [comment]
libtorrent does not share streams between threads, so that clause does not apply.

**Comment by aldenml** [comment]
Thanks!

**Pull request merged**
