### PR TITLE
Workaround for python3 in setup.py

### PR DESCRIPTION
**Pull request by stuaxo**

### CODE REVIEW

**Comment by arvidn** [comment]
I'm not a python expert, but if this function was removed in python 3, is there a better alternative that's available in 2 that should be used instead?

**Comment by arvidn** [comment]
@cas-- does this look reasonable to you?

**Comment by cas--** [comment]
It's overcomplicated, using exec means version check is unneeded so replace the execfile with either of these below. As it's simply running setup.py I'd be tempted to go with the latter single line version:
```
with open('setup.py) as filename:
    exec(filename.read())
```
or
```
exec(open('setup.py').read())
```

**Comment by stuaxo** [comment]
Updated to use the first version.

**Pull request merged**
