### PR TITLE
added clear_resolver_cache_on_ip_change setting

### PR DESCRIPTION
**Pull request by aldenml**
for your consideration

### CODE REVIEW

**Comment by arvidn** [comment]
is the assumption behind this feature that when you change IP, you may implicitly have changed geolocation, and load balancing DNS servers may give you new (and presumably better) results?

Other than that, and for the most part, I wouldn't expect hostnames to resolve to different IPs depending on your IP.

**Comment by aldenml** [comment]
This is a follow up of your comment https://github.com/arvidn/libtorrent/issues/1862#issuecomment-290741582, the main issue being IPv4 vs IPv6 name resolution (and I don't mind if you feel like it's not necessary).

**Comment by arvidn** [comment]
ah, I see. Rereading that, do you know if we filter endpoints of the "wrong" family in the cache? I would have expected both IPv6 and IPv4 endpoints would be cached in the resolver cache.

**Comment by aldenml** [comment]
There is no such filtering at the cache level, it stores all the addresses, and there are a fair amount of logic all over other places to deal with that. Now, is it possible that while connected via NAT64, you get _only_ IPv6 addresses? @jberkel?

**Comment by arvidn** [comment]
hm, perhaps

**Comment by jberkel** [comment]
@aldenml that is my understanding, you get ipv4 addresses embedded in ipv6, tagged with a well known-prefix:

https://tools.ietf.org/html/rfc6052#section-2.2

**Comment by aldenml** [comment]
Thanks for the link, to be honest, I'm not a big fan of this setting, but it took me 10 mins. It's @arvidn call

**Comment by arvidn** [comment]
yeah, I'm not a big fan of this patch either. it feels like it's addressing a much more specific case than it triggers on (i.e. perhaps it would make sense to do this when changing between all IPs being v4 to all IPs being v6 or vice versa). Still though, being able to disable the cache may be good enough.

**Pull request closed without merging**
