### PR TITLE
finished non-seed torrents can also be in super-seeding mode (1.0)

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
I think there is another minor issue. It seems that `post_torrent_updates()`/`state_update_alert` doesn't consider this change in status and doesn't report it in the alert.
Explicitly requesting the status seems to report the new value back.
Can you confirm?

**Comment by arvidn** [comment]
thanks, I'll look into that

**Comment by arvidn** [comment]
I think that update should fix it

**Comment by sledgehammer999** [comment]
I confirm that it works.

**Pull request merged**
