### PR TITLE
fix bug: urlseed never timeout

### PR DESCRIPTION
**Pull request by tnextday**
updates `m_last_sent` in `peer_connection::setup_send()` instand of `peer_connection::keep_alive()`

### CODE REVIEW

**Comment by arvidn** [comment]
what happened to the test?
Also, it just occurred to me, this most likely also affects RC_1_1. Would you mind creating the PR against that branch?

**Comment by tnextday** [comment]
ok

**Comment by tnextday** [comment]
I have fixed the test failed.

**Comment by arvidn** [comment]
I thought you had left the test in here, but it seems you closed the PR that had the test in it. I will merge the fix from RC_1_1 into master. but would you mind putting the test in RC_1_1 first?

**Comment by tnextday** [comment]
I will update it later.

**Pull request closed without merging**
