### PR TITLE
Merge RC_1_1 into master

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@aldenml This is a do-over of the same merge. I intend to inject this in the right location, rebase and force push master soon

**Comment by aldenml** [comment]
👍 thanks!

**Comment by arvidn** [comment]
actually, it doesn't look like anything else made it on top of this merge in master.

**Comment by arvidn** [comment]
@aldenml thanks for noticing!

**Pull request merged**
