### PR TITLE
make get_download_queue() return the queue

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
Are you planning to deprecate the other one?

**Comment by arvidn** [comment]
I'm not sure. do you think I should?
There may be edge cases where having to reallocate the vector for every call may be too expensive

**Comment by aldenml** [comment]
Good point, I will take a look at the code to clarify something first

**Comment by aldenml** [comment]
Hi @arvidn, I checked and I agree that it should stay for the cases where performance is a concern

**Pull request merged**
