### PR TITLE
simplify logic for opening listen sockets-1.0

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
Just so you know with this I don't get success alerts for `::` anymore. I get only for `0.0.0.0`.
(when passing 0 for interface to let the system decide)

**Comment by arvidn** [comment]
yeah, the theory is that listening to 0.0.0.0 (INADDR_ANY) can accept incoming IPv6 connections as well. I believe this is true at least.

**Comment by ssiloti** [comment]
To accept both IPv4 and IPv6 connections on the same listen socket you must bind to :: instead of 0.0.0.0. Also, when you do that IPv4 connections will look like IPv6 connections with the IPv4 address mapped into ::ffff:0:0/96 (i.e. an IPv4-mapped IPv6 address).

**Comment by arvidn** [comment]
yeah, I just looked this up. I would also have to disable IPV6_ONLY.
http://stackoverflow.com/questions/1618240/how-to-support-both-ipv4-and-ipv6-connections

**Comment by aldenml** [comment]
If the the accepted response in stackoverflow is true, how you will handle the Windows XP support? (This is RC_1_0)

**Comment by arvidn** [comment]
yeah, I guess XP was the reason I did it this (complicated) way to begin with. Having one socket per address family

**Comment by arvidn** [comment]
I get the feeling though that the more "clever" I get here, the more error prone the code become. But it probably makes sense to have two separate INADDR_ANY sockets.

**Pull request merged**
