### PR TITLE
upgrade libtommath to 1.0

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by Athorcis** [comment]
Have you ever experienced the bugs showed in tests (libtorrent) neither download nor seeding?

**Comment by arvidn** [comment]
yeah, some of those tests are flakey. in this case I think one instance failed to bind the listen port because some other process was still owning it.

**Comment by Athorcis** [comment]
When i build libtorrent i have errors with tommath includes, i fixed it in the following commit: fcd666a3c84e1fd2ed6bb61d0e43ee4a13ed8c63

**Comment by Athorcis** [comment]
still this won't compile unless libtommath is installed on your system (fcd666a)

**Comment by arvidn** [comment]
I'm surprised the issue with the includes didn't show up on travis or appveyor. maybe they have tommath installed...

**Comment by Athorcis** [comment]
i don't really either why theses builds weren't failing

**Pull request merged**
