### PR TITLE
Retire autotools

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by zeule** [comment]
@arvidn, will this be merged into the 1.2? If so, does b2 toolchain generate pkg-config?

**Comment by arvidn** [comment]
I think this is too big of a change to make it into 1.2. b2 does not create a `pkg-config` file (yet).

**Comment by zeule** [comment]
If I backport CMake fixes for pkg-config would you accept the changes?

**Comment by arvidn** [comment]
you mean back-port to `RC_1_1`? sure

**Comment by zeule** [comment]
OK, thanks. Will do.

**Comment by aldenml** [comment]
Is the ios compilation done with 64 bits by default? (I don't know)

**Comment by arvidn** [comment]
it's the ios simulator, and it's probably configured as the old simulator, back when iOS was 32 bit

**Comment by aldenml** [comment]
I think then that for iOS switching to 64 bits is reasonable and this problem should go away

**Pull request merged**
