### PR TITLE
use a proper optional value instead of a sentiel value for bytes_left()

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by Krakean** [comment]
Why to use boost::optional if there is std::optional?

**Comment by arvidn** [comment]
master is targeting c++11

**Comment by Krakean** [comment]
Oh, I see.
Curious, why not bump it to C++17 to lower dependency on boost as much as possible?
Current compilers(VS2017, GCC7, CLang 4) support mostly all important C+17 (and completely all C++14) features. It doesn't cost much to update to VS2017 Community Edition (which is free), same for other two. For those who wont or can't - can still use previous version of libtorrent.
Makes sense?

**Comment by arvidn** [comment]
@Krakean The version of GCC shipping in ubuntu LTS is more relevant than the latest release

**Pull request merged**
