### PR TITLE
removed openssl related code to deal with old versions

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
maybe I misunderstood. I thought all the code you removed is no longer needed in 2.0, *because* older version of openssl are no longer supported. It looks like a good change to me

**Comment by aldenml** [comment]
Well, I would say the issue is mostly in `master` with `webtorrent` on. I rather not change anything here in `RC_2_0`, but are you OK with removing support for openssl pre 1.1 in `master`?

**Comment by arvidn** [comment]
oh, I see. I misread the version check in the code. Do you think it's reasonable to drop support for pre 1.1 in master?
it probably is. It would also simplify the Jamfile for windows, since the library names are unified on windows and unix then.

**Comment by aldenml** [comment]
I think it's, they will be releasing a major version soon, so openssl 1.0.X is way in the past, and libtorrent `master` is way in the future :)

**Pull request closed without merging**
