### PR TITLE
add function to clear the peer list for a torrent

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by an0n666** [comment]
@arvidn 
I noticed an issue with this. If a torrent is in paused state and tracker is changed...peers are not cleaned.

**Comment by arvidn** [comment]
I don't understand the second condition. "the tracker has changed". What do you mean by that exactly?

**Comment by arvidn** [comment]
also, what symptom do you see to make you think the peer list isn't cleared?

**Comment by arvidn** [comment]
and you also called `clear_peers()`, right? and it didn't work?

**Comment by an0n666** [comment]
> and you also called `clear_peers()`, right? and it didn't work?

Yes. qBt calls that function now everytime changes are made to trackers. It works when a torrent is active. Doesn’t work when it’s paused.

**Comment by an0n666** [comment]
@arvidn 
Extremely sorry for wasting your valuable time. Somehow my libtorrent got replaced with a older build :(

**Pull request merged**
