### PR TITLE
test invalid torrent info

### PR DESCRIPTION
**Pull request by Falcosc**
https://github.com/arvidn/libtorrent/issues/1528

### CODE REVIEW

**Comment by arvidn** [comment]
RC_1_0 and RC_1_1 can be built without exceptions, in which case errors are reported by ``error_code`` output parameters

**Comment by arvidn** [comment]
please add the actual fix too, to the loading of the torrent in ``torrent_info``.

also, would you mind taking a look at why create_torrent() crashes? it shouldn't do that, even with a bad torrent as input.

**Comment by Falcosc** [comment]
I didn't find the broken code, because I can't create a broken torrent info.
Do you have an example for the exception less handling? I don't know where to get the error_code without exceptions after I did a wrong aktion.

**Comment by arvidn** [comment]
This constructor takes a reference to an ``error_code``. In case it fails, that error code is set to indicate which error occurred:

https://github.com/arvidn/libtorrent/blob/RC_1_0/include/libtorrent/torrent_info.hpp#L351

**Comment by Falcosc** [comment]
No you can't, that is the point of my problem because each **torrent_info::torrent_info** constructor calls parse_torrent_file() https://github.com/arvidn/libtorrent/blob/RC_1_0/src/torrent_info.cpp#L1187
which does all the checks.

You need to clone a broken torrent info, or adjust a already validated torrent info. Or you construct torrent_info with another torrent info.

For that reason I need to know wich constructor was used to crash libtorrent. Maybe one of the constructors are able to skip parse_torrent_file on special conditions.

**Comment by arvidn** [comment]
ok. so what does this patch do?

**Comment by Falcosc** [comment]
just test something which does already work

**Comment by arvidn** [comment]
it's probably better to extend test coverage in RC_1_1 (or no older than RC_1_1 at least)

**Pull request closed without merging**
