### PR TITLE
extensions refactor to use span and std::shared_ptr

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by arvidn** [comment]
looks good. please update ChangeLog as well, especially since this alters the API

**Comment by aldenml** [comment]
OK, btw, something very strange is happening when  using `std::unordered_multimap` in `resolve_links` when compiling with gcc

**Comment by arvidn** [comment]
it looks like there may be some subtle difference in semantics between boost::shared_ptr and std::shared_ptr

**Comment by aldenml** [comment]
it's very strange, I'm testing in my account

**Comment by aldenml** [comment]
This PR just went off track with a nasty memory crash running the simulation tests and a very strange behavior using `std::unordered_multimap` with `gcc`, closing it to redo in smaller parts.

**Pull request closed without merging**
