### PR TITLE
Http connection on resolve interrupt closed

### PR DESCRIPTION
**Pull request by AlexeyKhrolenko**
Do not try to connect() in http_connection::on_resolve if connection is closed. Otherwise, there is a delay about 30 seconds on libtorrent session close if on_resolve() runs after http_connection::close()

### CODE REVIEW

**Comment by AlexeyKhrolenko** [comment]
Sorry, I suppose I chose wrong branch =( Which branch should I use?

**Comment by summerqB** [comment]
RC2_0

**Comment by AlexeyKhrolenko** [comment]
done,

**Comment by AlexeyKhrolenko** [comment]
moved to https://github.com/arvidn/libtorrent/pull/6901

**Pull request closed without merging**
