### PR TITLE
Updated numerous repo addresses & revs of `pre-commit-hooks`

### PR DESCRIPTION
**Pull request by xavier2k6**

### CODE REVIEW

**Comment by xavier2k6** [comment]
@arvidn How would you like to proceed with the `toml-sort` & `black` failures?

**Comment by arvidn** [comment]
I think it's fine to apply those patches. maybe as a separate commit

**Comment by xavier2k6** [comment]
> I think it's fine to apply those patches. maybe as a separate commit

Ok, it'll probably be the weekend before I get back to this.

Just one other question, Would it be ok to back port this & PR https://github.com/arvidn/libtorrent/pull/7425 to `RC_1_2` Branch?

**Comment by arvidn** [comment]
> Would it be ok to back port this & PR https://github.com/arvidn/libtorrent/pull/7425 to RC_1_2 Branch?

Yes

**Comment by xavier2k6** [comment]
@arvidn Apologies but I'm lost with regard to the `black failures` -> **bindings/python/setup.py** & **/tools/vmstat.py**

Have handled the other failures.

**Comment by xavier2k6** [comment]
> I made this PR: #7468

@arvidn Thanks, I don't know if you'd like to update to latest repo revs for `mirrors-mypy` -> `1.4.1` & `PyCQA/autoflake/` -> `2.2.0` (these were updated betwen the time I opened this PR & your new one)

**Comment by xavier2k6** [comment]
BTW: Reminder for (RC_1_2) Ref.: #7041

`Python`
https://github.com/arvidn/libtorrent/blob/cd490aeaf442fddf684d6f34dfc7fd3379d4f103/configure.ac#L489

**Pull request closed without merging**
