### PR TITLE
cut down on travis testing a bit to make it quicker

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
Question: What happens with all the flags in `gcc-sanitizer`, no code will be running with these flags?

**Comment by arvidn** [comment]
The sims still run with sanitizer. Maybe the regular tests should too though

**Comment by aldenml** [comment]
I think it's a good idea to run regular tests with sanitizer too.

**Comment by arvidn** [comment]
@aldenml I think this is good. it cuts down on some of the redundant building and testing. you want to double check?

**Comment by aldenml** [comment]
LGTM

**Pull request merged**
