### PR TITLE
removed leading :: in posix_fadvise to allow for fix in old android API build

### PR DESCRIPTION
**Pull request by aldenml**
Hi @arvidn, this little change makes all the difference in the workaround I need to do for android API 16

### CODE REVIEW

**Comment by arvidn** [comment]
what's the issue on android? is this a macro there?

**Comment by arvidn** [comment]
I think it might make sense to leave a comment too, that there's something fishy right there on android

**Comment by aldenml** [comment]
No, is that `POSIX_FADV_RANDOM` is defined, but the function is not there, I redefine it in the compiler command line to nullify the call. This is due to bugs in the headers.

**Comment by arvidn** [comment]
thanks. lgtm

**Comment by arvidn** [comment]
the arm failures here are transient, right?

**Pull request merged**
