### PR TITLE
Fix bug caused by RP #96.

### PR DESCRIPTION
**Pull request by thomas-yuan**
Apparently PR #96 involve a incorrect logic which will cause DHT couldn't work correctly. 

I'm testing DHT mput/mget using tools/dht_put.cpp. (There is another bug need fix to run this test).
It doesn't work at all. But it does work before, so I was wondering which patch caused this issue. 
Almost spend two days to figure it out, it's caused by my PR #96.  :cold_sweat:

How to verify:
run dht_put mput/mget without/with this patch to see the different result.

Before test, need fix a bug in dht_put.cpp.

dht_put.cpp won't work by default. because session constructor will start dht by default, but there is no router/nodes, so bootstrap alert will immediately pushed in alert queue, which will trigger mput/mget.
since there is no router/nodes, mget/mput will also finished immediately without doing anything.

How fo fix:
add another ```wait_for_alert(s, dht_bootstrap_alert::alert_type); ``` in ```void bootstrap(lt::session& s)```; Or disable dht when constructor session, and then add router and call start_dht() (which is deprecated)

### CODE REVIEW

**Comment by arvidn** [comment]
why does this patch fix the problem? the dht_put command should probably be fixed to not start the DHT by default, add the routers and then start it. Perhaps the best solution would be to make the router nodes part of the settings so they can be added as the session is constructed.

**Comment by thomas-yuan** [comment]
I think for get_item, Timeout() and reply() have different logic which will effect add_requests(). Then if there is a error response, add_requests() will never return true which means done() will never be called. 

There is another PR for dht_put.cpp, almost same as your suggestion.

**Comment by thomas-yuan** [comment]
>I'm a bit worried about any subtle changes in the other patch though, why on_reply() vs. on_timeout() would make a difference.

I think I might find the root cause.
 
timeout() and reply() are all virtual function of class observer, the different is for get_item, the timeout is not override, but reply is a pure function and has to be implemented in derived-class. 

So when o->timeout(), the call stack looks like observer::timeout() => traversal_algorithm::failed() which will change the value of m_invoke_count/m_branch_factor. 
If it's o->reply, If it's a correct response, then the call stack will be get_item_observer::reply() => find_data_observer::reply() => observer::done() => traversal_algorithm::finished(), which will also change the m_invoke_count/m_branch_factor. BUT, if there is no "r" (an error response), then the function just return. It means the m_invoke_count/m_branch_factor has no chance to clean up. And since the observer has been removed from transaction of rpc_manager, the timeout() will not be called even after 15 seconds.

So this patch seems like a quick fix, should I make another patch to fix all reply() logic?

**Comment by arvidn** [comment]
it sounds like fixing the reply() logic would make the code more robust. If you're willing to make that patch, that would be great. I'm assuming errors like this one would be much less likely to happen. In either case, I would really appreciate if you would capture what you described here in a comment in the code.

The code is clearly meant to never be able to decrement the invoke count to 0 without completing the traversal_algorithm. If you can think of a way to organize the code to guarantee that, I think that would be ideal. Perhaps all decrementing of that counter should always go through the same path/function, and maybe it should only be accessible from that function. (m_invoke_count could be a private member of a base class for instance).

**Comment by thomas-yuan** [comment]
Checked all reply() today, seems like it's not a good solution to fix this in reply(). Please check comments in code.

**Comment by arvidn** [comment]
thanks, that comment is helpful. However, I get the impression that some traversal algorithm is still breaking in case a reply it gets doesn't fit its expectations. I would expect every traversal algorithm to always decrement the invoke count when it gets a response, regardless if it can parse it or not.

am I missing something?

**Comment by thomas-yuan** [comment]
You are right. This patch only fixed the bug involved by PR#96.

**Pull request merged**
