### PR TITLE
fix s390x tests and endian bugs

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@aldenml after fixing the incorrect `test-launcher.sh`, I get the same thing on travis as I do at home, https://travis-ci.com/github/arvidn/libtorrent/builds/179460650#L848

```
terminate called:

<not supported>
```

**Comment by aldenml** [comment]
interesting, I will run it in my VM and write back the result

**Comment by arvidn** [comment]
I got it. https://travis-ci.com/github/arvidn/libtorrent/builds/179653600#L2500

**Comment by aldenml** [comment]
@arvidn great! and the use of travis arch looks like a real win

**Pull request merged**
