### PR TITLE
fixes for python documentation and client.py

### PR DESCRIPTION
**Pull request by David-Luis**
fix python binding documentation error
fix client.py incorrect var name

### CODE REVIEW

**Comment by arvidn** [comment]
thanks! I imagine this applies to RC_1_1 too.

**Comment by David-Luis** [comment]
yes it applies for RC_1_1 :)

**Comment by arvidn** [comment]
damn. that never works. would you mind submitting this patch against RC_1_1?

**Comment by David-Luis** [comment]
hi, I'm checking and the client is already fixed in RC_1_1, also the fixes in the docs are not in that branch, so I will make the pull request again when this is merged, cheers!

**Comment by arvidn** [comment]
I've merged RC_1_1 into master now

**Comment by David-Luis** [comment]
Cool, this is the new pull request: https://github.com/arvidn/libtorrent/pull/2877

**Pull request closed without merging**
