### PR TITLE
fix ssl_version configuration issue in session constructor

### PR DESCRIPTION
**Pull request by arvidn**
introduce a generic tls version to use as default

### CODE REVIEW

**Comment by FranciscoPombal** [comment]
What does this "generic tls version" default to? 1.2?

**Comment by arvidn** [comment]
it's a bit unclear in the boost.asio documentation. The answer can probably be found in the openssl docs. But I suspect it means *any* TLS version.

**Comment by FranciscoPombal** [comment]
> it's a bit unclear in the boost.asio documentation. The answer can probably be found in the openssl docs. But I suspect it means _any_ TLS version.

Isn't there an alternative to doing things this way then? If there isn't, please make it abundantly clear i n the docs that libtorrent does not make any guarantees about the TLS version used when `tls` is specified and that people should double check what version will actually used, otherwise it could be a security risk for users.

**Comment by arvidn** [comment]
actually, reading about this ([here](https://www.openssl.org/docs/manmaster/man3/SSL_CTX_new.html)). It seems the version specific "methods" are deprecated, and that maybe this shouldn't be configurable at all..

**Comment by arvidn** [comment]
I think this is the right approach. I'm undoing the `ssl_version` setting and defer to OpenSSL to do the right thing. If anyone can think of a good reason *not* to apply this patch, please let me know.

**Comment by FranciscoPombal** [comment]
> I think this is the right approach. I'm undoing the `ssl_version` setting and defer to OpenSSL to do the right thing. If anyone can think of a good reason _not_ to apply this patch, please let me know.

Seems reasonable, but I sill think you should explicitly disable TLS <1.2. This is to prevent TLS < 1.2 from being auto selected if the OpenSSL version used is old enough to default to TLS < 1.2, but recent enough to have TLS 1.2 support. TLS 1.2 support was added in OpenSSL 1.0.1, released back in 2012, so I don't think you need to care about OpenSSL versions that don't support TLS 1.2.

**Comment by arvidn** [comment]
> Seems reasonable, but I sill think you should explicitly disable TLS <1.2.

I don't know of a way to do that. OpenSSL doesn't even have a deprecated API to do this, as far as I can tell. I assume the reason for this is for OpenSSL itself to have full control of disabling any insecure features, without giving the option to turn them back on again.

**Comment by rwasef1830** [comment]
@arvidn The latest version of this pull request fixes the tracker connection problem I described to you in email. Thanks!

**Comment by FranciscoPombal** [comment]
@arvidn 
What about this?
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_options.html

or this (the `no-*` options):
https://www.boost.org/doc/libs/1_72_0/doc/html/boost_asio/reference/ssl__context.html

> OpenSSL itself to have full control of disabling any insecure features, without giving the option to turn them back on again.

This only makes sense on OpenSSL's part if they always default to the latest supported version. Not sure if this is the case or not, I know nothing about their API.

**Comment by NotTsunami** [comment]
The macro in `include/libtorrent/config.hpp` should be removed as well.

**Comment by arvidn** [comment]
@FranciscoPombal it seems reasonable to disable old versions of TLS. However:

* I'm not an authority on this so deferring this to what OpenSSL does by default seems reasonable.
* The steps of authenticating trackers *at all* is already the most significant step, so I think this is sufficient for one PR. Tuning of which TLS versions to support could always be added later, but I also have faith in OpenSSL disabling insecure features by default, as they come up.

**Comment by FranciscoPombal** [comment]
I suppose you're right. Now that I think about it, a better way of achieving essentially the same result is to bump the dependency version requirement of OpenSSL. For example, in this case you could force libtorrent to require that the dependency on OpenSSL be `OpenSSL >= 1.0.1`. As protocols become insecure in the future, you just bump this version requirement accordingly, to a version of OpenSSL that doesn't default to them or disables them entirely.

**Pull request merged**
