### PR TITLE
Clang tidy

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
How strong is this PR? I see that creating the database this way will only check with the arguments in linux, maybe collecting the arguments by hand per platform and with a simple bash script create it do the trick, and then runs the tidy per database.

**Comment by arvidn** [comment]
the intention was just to run it on linux on travis.

**Comment by arvidn** [comment]
I've put it on hold for now. I may get back to it later. I think a better approach is to make a boost-build toolset that runs clang-tidy (instead of compile and link)

**Comment by aldenml** [comment]
feel like a cleanup (close PR) :)

**Pull request closed without merging**
