### PR TITLE
passing block size to smart_ban plugin methods for hashing

### PR DESCRIPTION
**Pull request by aldenml**

### CODE REVIEW

**Comment by ssiloti** [comment]
lgtm

**Comment by arvidn** [comment]
this is an issue in 1.1 and probably 1.0 too, isn't it?

**Comment by aldenml** [comment]
no, for what I see this was introduced in the refactor https://github.com/arvidn/libtorrent/commit/fc9dabe1ab954c80d4c4072063545e3f87308d98

**Comment by arvidn** [comment]
ah, yes

**Pull request merged**
