### PR TITLE
WebTorrent: Update libdatachannel to v0.13.3

### PR DESCRIPTION
**Pull request by paullouisageneau**
This PR updates libdatachannel to fix https://github.com/paullouisageneau/libdatachannel/issues/427. Breaking changes in v0.13 affect mostly the media API. As libdatachannel does not expose plog anymore, I refactored debug logging.

### CODE REVIEW

**Review by arvidn — APPROVED** [review]

**Comment by arvidn** [comment]
would you mind rebasing this on top of master? I think the CI failures have been fixed there.

**Comment by paullouisageneau** [comment]
@arvidn It's rebased on top of last master.

**Comment by arvidn** [comment]
it looks like `test_rtc` is having some difficulty still.

https://github.com/arvidn/libtorrent/pull/6233/checks?check_run_id=2712793076#step:8:129

I'll try to reproduce this in a bit

**Comment by arvidn** [comment]
This is the output I get when I run the failing test locally:

```
../deps/libdatachannel/src/impl/icetransport.cpp:285:35: runtime error: member call on misaligned address 0x000000000837 for type 'struct IceTransport', which requires 8 byte alignment
0x000000000837: note: pointer points here
<memory cannot be printed>
```

**Comment by paullouisageneau** [comment]
> This is the output I get when I run the failing test locally:
> 
> ```
> ../deps/libdatachannel/src/impl/icetransport.cpp:285:35: runtime error: member call on misaligned address 0x000000000837 for type 'struct IceTransport', which requires 8 byte alignment
> 0x000000000837: note: pointer points here
> <memory cannot be printed>
> ```

This really looks like an ABI issue, something like libdatachannel was compiled with libjuice headers from a version incompatible with the version it is linked with (I guess there might be a caching issue with how libdatachannel's Jamfile builds dependencies).

I'm investigating why the test hangs, for now I'm unable to reproduce locally.

**Comment by arvidn** [comment]
you're right. I did not take care to ensure the make-based build was rebuilt. I sometimes find it hard to clear previous build targets that are external to the build system.

**Comment by arvidn** [comment]
`test_rtc` is still failing with this:
```
../deps/libdatachannel/src/impl/icetransport.cpp:285:35: runtime error: member call on misaligned address 0x000000000837 for type 'struct IceTransport', which requires 8 byte alignment
0x000000000837: note: pointer points here
```

**Comment by arvidn** [comment]
I managed to rebuild everything cleanly (I think) and now the problem I encounter is a hang at the end, after all tests have completed (successfully).

```
(gdb) info threads
  Id   Target Id                                           Frame 
* 1    Thread 0x7ffff6683c80 (LWP 3470190) "test_rtc"      futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x614000005dd0) at ../sysdeps/nptl/futex-internal.h:183
  6    Thread 0x7fffefbad700 (LWP 3470198) "SCTP iterator" futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x152b3e1c <sctp_it_ctl+124>) at ../sysdeps/nptl/futex-internal.h:183
  7    Thread 0x7fffef396700 (LWP 3470199) "SCTP timer"    0x00007ffff67683bf in __GI___clock_nanosleep (clock_id=clock_id@entry=0, flags=flags@entry=0, req=0x7fffef394980, rem=0x7fffef394990) at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
  23   Thread 0x7fffedad3700 (LWP 3470215) "test_rtc"      0x00007ffff67a012b in __GI___select (nfds=10, readfds=0x7fffedad1530, writefds=0x0, exceptfds=0x0, timeout=0x7fffedad1520) at ../sysdeps/unix/sysv/linux/select.c:41
  24   Thread 0x7fffee311700 (LWP 3470216) "test_rtc"      futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x61600007403c) at ../sysdeps/nptl/futex-internal.h:183
```

Thread 1 is waiting:

```
#0  futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x614000005dd0) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x614000005d80, cond=0x614000005da8) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x614000005da8, mutex=0x614000005d80) at pthread_cond_wait.c:638
#3  0x00007ffff7446e50 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000000005d4ebe7 in std::condition_variable::wait<rtc::impl::Processor::join()::<lambda()> >(std::unique_lock<std::mutex> &, rtc::impl::Processor::<lambda()>) (this=0x614000005da8, __lock=..., __p=...) at /usr/local/include/c++/9.2.0/condition_variable:101
#5  0x0000000005d4e5dc in rtc::impl::Processor::join (this=0x614000005c40) at ../deps/libdatachannel/src/impl/processor.cpp:29
#6  0x0000000005d66321 in rtc::impl::PeerConnection::~PeerConnection (this=0x61f00000c490, __in_chrg=<optimised out>) at ../deps/libdatachannel/src/impl/peerconnection.cpp:77
#7  0x0000000005ad5daa in __gnu_cxx::new_allocator<rtc::impl::PeerConnection>::destroy<rtc::impl::PeerConnection> (this=0x61f00000c490, __p=0x61f00000c490) at /usr/local/include/c++/9.2.0/ext/new_allocator.h:153
#8  0x0000000005ad5c6b in std::allocator_traits<std::allocator<rtc::impl::PeerConnection> >::destroy<rtc::impl::PeerConnection> (__a=..., __p=0x61f00000c490) at /usr/local/include/c++/9.2.0/bits/alloc_traits.h:497
#9  0x0000000005ad44d9 in std::_Sp_counted_ptr_inplace<rtc::impl::PeerConnection, std::allocator<rtc::impl::PeerConnection>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x61f00000c480) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:557
#10 0x00000000026b3021 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x61f00000c480) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:155
#11 0x00000000026a1588 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x60400001dab0, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:730
#12 0x0000000005ab2ba6 in std::__shared_ptr<rtc::impl::PeerConnection, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x60400001daa8, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:1169
#13 0x0000000005ab2c27 in std::shared_ptr<rtc::impl::PeerConnection>::~shared_ptr (this=0x60400001daa8, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr.h:103
#14 0x0000000005ab2d3d in rtc::CheshireCat<rtc::impl::PeerConnection>::~CheshireCat (this=0x60400001daa0, __in_chrg=<optimised out>) at ../deps/libdatachannel/include/rtc/utils.hpp:155
#15 0x0000000005aa3be0 in rtc::PeerConnection::~PeerConnection (this=0x60400001daa0, __in_chrg=<optimised out>) at ../deps/libdatachannel/src/peerconnection.cpp:51
#16 0x000000000416d07e in __gnu_cxx::new_allocator<rtc::PeerConnection>::destroy<rtc::PeerConnection> (this=0x60400001daa0, __p=0x60400001daa0) at /usr/local/include/c++/9.2.0/ext/new_allocator.h:153
#17 0x000000000416cf59 in std::allocator_traits<std::allocator<rtc::PeerConnection> >::destroy<rtc::PeerConnection> (__a=..., __p=0x60400001daa0) at /usr/local/include/c++/9.2.0/bits/alloc_traits.h:497
#18 0x000000000416c9f3 in std::_Sp_counted_ptr_inplace<rtc::PeerConnection, std::allocator<rtc::PeerConnection>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x60400001da90) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:557
#19 0x00000000026b3021 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x60400001da90) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:155
#20 0x00000000026a1588 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x61200002f8f0, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:730
#21 0x000000000268ed12 in std::__shared_ptr<rtc::PeerConnection, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x61200002f8e8, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:1169
#22 0x000000000268ed93 in std::shared_ptr<rtc::PeerConnection>::~shared_ptr (this=0x61200002f8e8, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr.h:103
#23 0x00000000041b3fb0 in libtorrent::aux::rtc_stream_impl::~rtc_stream_impl (this=0x61200002f8d0, __in_chrg=<optimised out>) at ../include/libtorrent/aux_/rtc_stream.hpp:59
#24 0x00000000041b4062 in __gnu_cxx::new_allocator<libtorrent::aux::rtc_stream_impl>::destroy<libtorrent::aux::rtc_stream_impl> (this=0x61200002f8d0, __p=0x61200002f8d0) at /usr/local/include/c++/9.2.0/ext/new_allocator.h:153
#25 0x00000000041b3c4d in std::allocator_traits<std::allocator<libtorrent::aux::rtc_stream_impl> >::destroy<libtorrent::aux::rtc_stream_impl> (__a=..., __p=0x61200002f8d0) at /usr/local/include/c++/9.2.0/bits/alloc_traits.h:497
#26 0x00000000041b36e7 in std::_Sp_counted_ptr_inplace<libtorrent::aux::rtc_stream_impl, std::allocator<libtorrent::aux::rtc_stream_impl>, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x61200002f8c0) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:557
#27 0x00000000026b3021 in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x61200002f8c0) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:155
#28 0x00000000026a1588 in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fffffffd470, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:730
#29 0x000000000417dd32 in std::__shared_ptr<libtorrent::aux::rtc_stream_impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fffffffd468, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr_base.h:1169
#30 0x000000000417ddb3 in std::shared_ptr<libtorrent::aux::rtc_stream_impl>::~shared_ptr (this=0x7fffffffd468, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/bits/shared_ptr.h:103
#31 0x000000000417de35 in std::_Head_base<0ul, std::shared_ptr<libtorrent::aux::rtc_stream_impl>, false>::~_Head_base (this=0x7fffffffd468, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/tuple:120
#32 0x000000000417deda in std::_Tuple_impl<0ul, std::shared_ptr<libtorrent::aux::rtc_stream_impl>, boost::system::error_code>::~_Tuple_impl (this=0x7fffffffd458, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/tuple:185
#33 0x000000000417df5b in std::tuple<std::shared_ptr<libtorrent::aux::rtc_stream_impl>, boost::system::error_code>::~tuple (this=0x7fffffffd458, __in_chrg=<optimised out>) at /usr/local/include/c++/9.2.0/tuple:893
#34 0x000000000417e000 in std::_Bind<void (libtorrent::aux::rtc_stream_impl::*(std::shared_ptr<libtorrent::aux::rtc_stream_impl>, boost::system::error_code))(boost::system::error_code const&)>::~_Bind() (this=0x7fffffffd448, __in_chrg=<optimised out>)
    at /usr/local/include/c++/9.2.0/functional:386
#35 0x0000000004191b04 in boost::asio::detail::work_dispatcher<std::_Bind<void (libtorrent::aux::rtc_stream_impl::*(std::shared_ptr<libtorrent::aux::rtc_stream_impl>, boost::system::error_code))(boost::system::error_code const&)> >::~work_dispatcher() (this=0x7fffffffd440, 
    __in_chrg=<optimised out>) at /home/arvid/dev/boost_1_73_0/boost/asio/detail/work_dispatcher.hpp:30
#36 0x00000000041aa939 in boost::asio::detail::executor_op<boost::asio::detail::work_dispatcher<std::_Bind<void (libtorrent::aux::rtc_stream_impl::*(std::shared_ptr<libtorrent::aux::rtc_stream_impl>, boost::system::error_code))(boost::system::error_code const&)> >, std::allocator<void>, boost::asio::detail::scheduler_operation>::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) (owner=0x0, base=0x6080000150a0) at /home/arvid/dev/boost_1_73_0/boost/asio/detail/executor_op.hpp:62
#37 0x00000000026710a9 in boost::asio::detail::scheduler_operation::destroy (this=0x6080000150a0) at /home/arvid/dev/boost_1_73_0/boost/asio/detail/scheduler_operation.hpp:45
#38 0x000000000267f7f0 in boost::asio::detail::scheduler::shutdown (this=0x611000000040) at /home/arvid/dev/boost_1_73_0/boost/asio/detail/impl/scheduler.ipp:166
#39 0x0000000002673b0b in boost::asio::detail::service_registry::shutdown_services (this=0x606000000020) at /home/arvid/dev/boost_1_73_0/boost/asio/detail/impl/service_registry.ipp:44
#40 0x0000000002675465 in boost::asio::execution_context::shutdown (this=0x15291600 <(anonymous namespace)::io_context>) at /home/arvid/dev/boost_1_73_0/boost/asio/impl/execution_context.ipp:41
#41 0x00000000026752e4 in boost::asio::execution_context::~execution_context (this=0x15291600 <(anonymous namespace)::io_context>, __in_chrg=<optimised out>) at /home/arvid/dev/boost_1_73_0/boost/asio/impl/execution_context.ipp:34
#42 0x0000000002685ae1 in boost::asio::io_context::~io_context (this=0x15291600 <(anonymous namespace)::io_context>, __in_chrg=<optimised out>) at /home/arvid/dev/boost_1_73_0/boost/asio/impl/io_context.ipp:56
#43 0x00007ffff66d1a27 in __run_exit_handlers (status=0, listp=0x7ffff6873718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#44 0x00007ffff66d1be0 in __GI_exit (status=<optimised out>) at exit.c:139
#45 0x00007ffff66af0ba in __libc_start_main (main=0x26f9212 <main(int, char const**)>, argc=1, argv=0x7fffffffd7f8, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffd7e8) at ../csu/libc-start.c:342
#46 0x000000000261b05e in _start ()
```

This looks like a global destructor, which seems risky. I would imagine it's hard to synchronize shutdown of threads at that point. Is this a global variable?

Thread 24 seems to not realize it's time to shut down:

```
#0  futex_wait_cancelable (private=<optimised out>, expected=0, futex_word=0x61600007403c) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x616000074098, cond=0x616000074010) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x616000074010, mutex=0x616000074098) at pthread_cond_wait.c:638
#3  0x00007ffff7446e50 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x0000000005ef9c71 in std::condition_variable::wait<rtc::impl::Queue<std::shared_ptr<rtc::Message> >::wait(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > > const&)::{lambda()#2}>(std::unique_lock<std::mutex>&, rtc::impl::Queue<std::shared_ptr<rtc::Message> >::wait(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > > const&)::{lambda()#2}) (this=0x616000074010, __lock=..., __p=...) at /usr/local/include/c++/9.2.0/condition_variable:101
#5  0x0000000005ef8468 in rtc::impl::Queue<std::shared_ptr<rtc::Message> >::wait (this=0x616000073f98, duration=std::optional<struct std::chrono::duration<long, std::ratio<1, 1000> >> [no contained value]) at ../deps/libdatachannel/src/impl/queue.hpp:145
#6  0x0000000005ef30c7 in rtc::impl::DtlsTransport::runRecvLoop (this=0x616000073e90) at ../deps/libdatachannel/src/impl/dtlstransport.cpp:543
#7  0x0000000005efc2a0 in std::__invoke_impl<void, void (rtc::impl::DtlsTransport::*)(), rtc::impl::DtlsTransport*> (__f=@0x6030000713c0: (void (rtc::impl::DtlsTransport::*)(class rtc::impl::DtlsTransport * const)) 0x5eeeffe <rtc::impl::DtlsTransport::runRecvLoop()>,
    __t=@0x6030000713b8: 0x616000073e90) at /usr/local/include/c++/9.2.0/bits/invoke.h:73
#8  0x0000000005efbcdd in std::__invoke<void (rtc::impl::DtlsTransport::*)(), rtc::impl::DtlsTransport*> (__fn=@0x6030000713c0: (void (rtc::impl::DtlsTransport::*)(class rtc::impl::DtlsTransport * const)) 0x5eeeffe <rtc::impl::DtlsTransport::runRecvLoop()>,
    __args#0=@0x6030000713b8: 0x616000073e90) at /usr/local/include/c++/9.2.0/bits/invoke.h:95
#9  0x0000000005efbb19 in std::thread::_Invoker<std::tuple<void (rtc::impl::DtlsTransport::*)(), rtc::impl::DtlsTransport*> >::_M_invoke<0ul, 1ul> (this=0x6030000713b8) at /usr/local/include/c++/9.2.0/thread:244
#10 0x0000000005efb9cd in std::thread::_Invoker<std::tuple<void (rtc::impl::DtlsTransport::*)(), rtc::impl::DtlsTransport*> >::operator() (this=0x6030000713b8) at /usr/local/include/c++/9.2.0/thread:251
#11 0x0000000005efb98e in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (rtc::impl::DtlsTransport::*)(), rtc::impl::DtlsTransport*> > >::_M_run (this=0x6030000713b0) at /usr/local/include/c++/9.2.0/thread:195
#12 0x00007ffff744cd84 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#13 0x00007ffff6883609 in start_thread (arg=<optimised out>) at pthread_create.c:477
#14 0x00007ffff67aa293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by paullouisageneau** [comment]
Sorry, I forgot to get back on this. The problem is indeed triggered when closing a `PeerConnection` from a global destructor, and it is caused by libdatachannel stopping its thread pool at exit, which is at the mercy of the order of global destructors.

**Pull request merged**
