### PR TITLE
Update default windows OpenSSL build paths (RC_1_2)

### PR DESCRIPTION
**Pull request by AllSeeingEyeTolledEweSew**
#6473 on `RC_1_2`

### CODE REVIEW

**Review by arvidn — APPROVED** [review]

**Comment by arvidn** [comment]
the appveyor CI seems to rely on the default paths for openssl. `appveyor.yml` should be updated to either specify `openssl-lib=` and `openssl-include=` or use chocolatey to get openssl

**Comment by AllSeeingEyeTolledEweSew** [comment]
I updated this before I saw #6487

**Comment by AllSeeingEyeTolledEweSew** [comment]
I got confused about the difference between https://github.com/arvidn/libtorrent/pull/6487 and https://github.com/AllSeeingEyeTolledEweSew/libtorrent/pull/22 ... should I have merged https://github.com/AllSeeingEyeTolledEweSew/libtorrent/pull/22 or waited for you to change it further?

**Comment by arvidn** [comment]
I was hoping that my PR against your PR would also trigger the CI, but it didn't. So I also made the same change in my repository, as a draft, to see whether it actually worked

**Pull request merged**
