### PR TITLE
FIX(peer_list): clear the m_candidate_cache when clear peer_list, and…

### PR DESCRIPTION
**Pull request by Lwxiang**
… set m_num_seeds to 0

### CODE REVIEW

**Comment by Lwxiang** [comment]
when user call `torrent_handle::clear_peers()`, it will trigger the `peer_list::clear()`.

then the `m_candidate_cache` which contains the pointers of peers should also be cleaned after the pointers being freed. I believe this issue causes some crash in #7386 or #7398.

also the `m_num_seeds` should be reset to 0.

**Comment by arvidn** [comment]
great catch!
yes, I will have to update the test certificates.

Would you mind extending the unit test to cover this fix as well?

**Comment by Lwxiang** [comment]
sure, I will add some test later.

**Comment by Lwxiang** [comment]
already add the `clear_peers` unit test for peer_list.

before fix, it will not pass the test:
企业微信截图_549922df-747b-4b77-be20-55bf821b7133

after fix, it pass the test:
企业微信截图_b35c76e9-2e4c-450e-a8f6-c36d0cbc197f

**Comment by Lwxiang** [comment]
@arvidn hi PTAL, can this be merged?

**Review by arvidn — APPROVED** [review]

**Comment by Lwxiang** [comment]
@arvidn seems there are some mistakes with `test_resume`, the testcase compares the microsecond-duration with second-duration.

**Pull request merged**
