### PR TITLE
attempt to fix issue with binding udp sockets on windows

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
would you mind breaking in udp_socket::bind() and step through to see exactly which operation fails?
(keep an eye on "ec" and possibly on "err", but the latter is supposed to be for non-fatal errors).

Also, if you observe a failure, which error code is it?

Also, do you have IPv6 enabled? do you perhaps have an IPv6 connection?

I've been spending some time stepping through this code on my windows machine adn trying to disable IPv6 (unsuccessfully) but haven't been able to trigger a (fatal) failure. The only weird thing I see is that setsockopt() for SO_REUSEADDR fails on the IPv6 socket with "invalid argument" (error code 10022). I can't explain that, and I suppose that failing could cause the error you see down the line.

**Comment by arvidn** [comment]
@sledgehammer999 btw ^^^

**Comment by sledgehammer999** [comment]
Going through the debugger doesn't reproduce the problem. Apparently the delay caused by the break between the 2 calls to bind is enough for the 2nd bind to work.

How do I use error_code? I tried reading the boost docs but I couldn't find examples.
I don't know if this is what you're looking for but `error_code.value() == 10048`

**Comment by arvidn** [comment]
did any of the socket options on the socket fail? specifically reuse_address

**Comment by sledgehammer999** [comment]
>did any of the socket options on the socket fail? specifically reuse_address

Do you mean while in the debugger?
If yes, can you give more instructions. I am a noob. I am able to set the breakpoint to udp_socket::bind but then what?

**Comment by arvidn** [comment]
right, sorry. I should have responded to the error_code question too.

if you break in udp_socket::bind() and step through it, you will pass calls to create, configure and bind the socket. those calls take an error_code reference through which they return errors. as you guessed, the "value" of the error_code corresponds to what GetLastError() returns, and the category() specifies the domain the error codes belong to (in this case it should be boost::system::system_category, to indicate the system's native error codes).

Some operations return errors into the "ec" variable and some into the local "err" variable (if the error is ignored). I would be curious if exclusive_addr_use or reuse_addr fail, either the first time the socket is bound or the second time.

The fact that just a slight delay between closing and re-opening makes a difference makes me think that sockets aren't closed immediately on windows, but scheduled to be closed very soon after (a bit like deleting files on ntfs).

**Comment by arvidn** [comment]
@sledgehammer999 I pushed another change to this branch. for UDP sockets, it attempts to not rebind them if the existing one is already bound to what we want to bind it to.

would you mind giving it a try?

**Comment by sledgehammer999** [comment]
>would you mind giving it a try?

Yes, I'll try it. Sorry for not following through with the debugging, I had other matters with qbt.
FYI, 1.0.9 shows the exact same problem now for me. I get it 100% of the time. Previous versions failed randomly for other users.

**Comment by sledgehammer999** [comment]
Get compilation errors:
>src\session_impl.cpp(2051): error C2065: 'err': undeclared identifier
src\session_impl.cpp(2052): error C2065: 'err': undeclared identifier

**Comment by arvidn** [comment]
fixed

**Comment by sledgehammer999** [comment]
Hmm some interesting results.
I still get a double listen succeed for UDP/-myport and I think the second one is the rebinding. But now it doesn't fail.
But I also get a listen succeed alert for TCP/0. I thought you had fixed that. NOTE: The zero port comes in the 2nd round succeed alert aka when I close the ssl port.

**Comment by arvidn** [comment]
ah, right. I just made it skip the closing and reopening the udp socket. it will still send the same alerts as if it did.

**Comment by sledgehammer999** [comment]
Ok, but what about the 0 TCP port?

**Comment by arvidn** [comment]
I can't recall off-hand what was causing that. I'll look into that as well. However, thinking about what has changed in 1.0.9, I'm starting to suspect what's behind this is reuseaddr and exclusiveaddruse options. Previously neither of those were set on windows, but both of them together should offer the same semantics as reuseaddr on other systems. Perhaps there's some issue with closing the socket has a delay before freeing the port.

**Comment by sledgehammer999** [comment]
About tcp/0 : https://github.com/arvidn/libtorrent/pull/489#issuecomment-187221607

**Comment by sledgehammer999** [comment]
any news on this?

**Comment by arvidn** [comment]
no. I would like to close out the uTP issue before moving back onto this one. Maybe I'll find some more time this weekend.

**Comment by sledgehammer999** [comment]
Then this seems to fix the utp issue. I have been running with it several days now and it I haven't run on that issue again. (only the zero port). So it would be great if you merge it and fix it in RC_1_0 so I can make release too.
PS: You might want to squash your commits together.

**Comment by arvidn** [comment]
I'm tracking a separate uTP issue (unrelated to failing to bind/create the UDP socket). (this one https://github.com/arvidn/libtorrent/issues/509#issuecomment-194690465 )

**Comment by arvidn** [comment]
@sledgehammer999 
ok, I've reverted the use of exclusive_addruse (and reuseaddr) on windows. It's a bit counter intuitive that this would help, but given that you experienced the same regression in 1.0.9 vs. 1.0.8, it seems like this is the likely cause.

This pull request still implements the optimization to not reopen and rebind the udp socket if it's configured to listen on the same interface and port as the one already open. So I'm guessing there's still an improvement in likelihood of failure.

**Comment by arvidn** [comment]
please give it a try when you have a chance

**Comment by sledgehammer999** [comment]
New commit still works.
However I still get a success message after fake rebinding for a zero TCP port.

**Comment by arvidn** [comment]
I had forgotten to rebase this patch. Now it's on top of RC_1_1 and should have the fix for the port mapping and TCP/0 alert (as far as I understand)

**Comment by sledgehammer999** [comment]
I just tried it again. The problem is still there and there might be another one.
Let me remind you first what happens in qbt. We pass the port in the session's constructor which results in a batch of listen succeed/fail alerts. Then almost immediately we set the ssl port to zero to disable it, which results in a 2nd batch of listen succeed/listen alerts.

In the first batch, where the ssl port is automatically opened, I get 2 listen succeed alerts for it. One is of type `listen_succeeded_alert::tcp` and the other `listen_succeeded_alert::tcp_ssl`. The port number is in both cases `4433` and I get them only for the `0.0.0.0` interface. The `::` has only one of type `tcp_ssl`.

In the 2nd batch of alerts I get:
1. One for `::` and my chosen port for TCP
2. One for `0.0.0.0` and my chosen port for TCP
3. One for `0.0.0.0` and port 0 for TCP
4. One for `0.0.0.0` and my chosen port for UDP

**Comment by arvidn** [comment]
I wonder if the extra alert for the ssl port is for the udp socket, and is just mislabeled. That could explain the 0 port too, since you set ssl_listen to 0. Thanks for the description, I'll keep looking.

**Comment by arvidn** [comment]
ok. I could reproduce what you see, except I saw the socket type as SSL/uTP (not TCP). This patch should fix it. I will also disable ssl_listen by default. I don't think it makes sense for ssl to be enabled.

**Comment by sledgehammer999** [comment]
>except I saw the socket type as SSL/uTP (not TCP).

Sorry, in my if/else block I didn't handle that type and had a catch-all block assigning TCP.

>This patch should fix it

Indeed it fixes it. Please backport it to RC_1_0 too. It has the same problem.

>I will also disable ssl_listen by default.

Are you talking about a future patch? Because current PR still opens the ssl port(4433) initially.

**Comment by arvidn** [comment]
yes, I pushed the change to disable ssl_listen by default straight to RC_1_1 (otherwise you wouldn't be able to test this patch)

**Comment by arvidn** [comment]
thanks for testing

**Comment by arvidn** [comment]
RC_1_0 does not support SSL over uTP and doesn't have this socket that caused the erroneous alerts. What exactly do you see in RC_1_0?

**Comment by sledgehammer999** [comment]
I am talking about the original problem of this PR. Aka udp-rebinding failure.

>yes, I pushed the change to disable ssl_listen by default straight to RC_1_1 (otherwise you wouldn't be able to test this patch)

give me 30-40 minutes to test again, then. (I am away now)

**Comment by sledgehammer999** [comment]
I confirm. Current PR seems to work perfectly.

**Comment by sledgehammer999** [comment]
Can I kindly ask again to backport to RC_1_0? Currently 1.0.9 shows the same problem(failure to udp rebind).
Last known working commit is 602dc02

**Comment by arvidn** [comment]
does this do it? https://github.com/arvidn/libtorrent/pull/575 (against RC_1_0)

**Pull request merged**
