### PR TITLE
attempt to fix issue where the partfile is not deleted

### PR DESCRIPTION
**Pull request by arvidn**
when asking to delete all files

### CODE REVIEW

**Comment by Isabelxxx** [comment]
Just wanted to note the part files must be deleted always after deleting torrent; it doesn't matter if you ask to delete all files or only the torrent.

Just think about it: part file is created to download the torrent (or seeding). If you delete the torrent from the program it will not be used any more, therefore is not needed. 

At least that seems the more logical approach to me. What do you think?

**Comment by arvidn** [comment]
libtorrent doesn't have the concept of "delete .torrent" though, it only has the option "delete all files". a client could delete the partfile still though

**Comment by arvidn** [comment]
@sledgehammer999 do you think you give this patch a try? or make a qbt build and have a user test it?

**Comment by Chocobo1** [comment]
>>Just wanted to note the part files must be deleted always after deleting torrent; it doesn't matter if you ask to delete all files or only the torrent.

>libtorrent doesn't have the concept of "delete .torrent" though, it only has the option "delete all files". a client could delete the partfile still though

I guess he means calling `session::remove_torrent()`.

It will be convenient if libtorrent can delete partfiles when calling that function, or it's not reasonable?

**Comment by arvidn** [comment]
I don't think it would make sense for that function to delete the partfile from disk. session::remove_torrent() just removes it from the session. it doesn't indicate that there will be no further seeding/downloading of the torrent. it doesn't touch the actual .torrent file on disk.

I recognize that the part file implementation right now is quite inflexible though. There probably needs to be some more facilities around renaming it and/or removing it independently.

**Comment by Isabelxxx** [comment]
I agree partially with you arvidn; but maybe that has to be done on the client side (?) and not libtorrent itself.

The most common behavior is download something and deleting the torrent; then doing whatever you want with the downloaded files.
If you really intend to seed/download later then why are you deleting the torrent from the client?

Current implementation will left ALL part files after finishing torrents and that will lead to orphan files with no use in most cases after deleting torrents. The other situation, the one you consider, I think it's the less common therefore it would make more sense to deal with that manually.

For ex. the user making a copy of the part file before deleting finished torrent.

As I say at least at some point (client, libtorrent, ...) this behavior needs to be considered so partfiles are deleted by default.

**Comment by arvidn** [comment]
again, your argument makes sense at the qbittorrent level. libtorrent does not manage storage of .torrent files. it doesn't know about them as files on disk. remove_torrent() on session has no ability to actually delete any .torrent file (it may not even exist on disk).

**Comment by Isabelxxx** [comment]
Then @sledgehammer999 should check it, in fact I found the issue in qbit so that's what I was talking about ;)

**Comment by sledgehammer999** [comment]
@arvidn I am going to provide a build in a few.
But I recommend the following. As you know session::remove_torrent() takes a second parameter called `options`. I suggest adding a new value for "delete partfile but keep the other files". This can be exposed in the GUI as an option then.

>I recognize that the part file implementation right now is quite inflexible though. There probably needs to be some more facilities around renaming it and/or removing it independently.

Keep in mind that we haven't actually switched to new facilities of 1.1.x series. I haven't even took a quick peek at what is available now. So my only question is: Is using a partfile or not a configurable option?

**Comment by arvidn** [comment]
let's put it this way; it's possible to opt-out of using it. Whenever a *file* has priority zero, the storage will route writes to it into the partfile. however, you can set the *piece* priorities without affecting file priorities.

an option for deleting the partfile in remove_torrent() would seem to make sense.

**Comment by sledgehammer999** [comment]
Here is qbt build with this patch. qbt is latest master so use at your own discretion.
Build: http://builds.shiki.hu/temp/qbittorrent_3.4.0alpha_libtorrent_1.1_git_6ff929e5672.7z

**Comment by sledgehammer999** [comment]
>let's put it this way; it's possible to opt-out of using it. Whenever a file has priority zero, the storage will route writes to it into the partfile. however, you can set the piece priorities without affecting file priorities.

I think it would be nice to control that more easily.
Partfile is very useful. But I suspect there will be "weird users" that will want actual half written files.

**Comment by Isabelxxx** [comment]
Any word about the option for deleting the partfile in remove_torrent()?

Now that I got it right, could test it at anytime.

**Comment by arvidn** [comment]
option to delete partfile is on my (short) 1.1 list. but I only have nights and weekends, patches are welcome!

**Comment by Isabelxxx** [comment]
Have looked through the source code; a very simple solution would be:

Add another option in **session_handle.hpp**
`		enum options_t
		{
			// delete the files belonging to the torrent from disk.
			delete_files = 1
			delete_torrent_and_partfile = 2
		};`

New call to delete_partfile instead of "default_storage::delete_files" for option 2 in session_impl.cpp
`		if (options & session::delete_torrent_and_partfile)
		{
....
		}
`

And that new "clone" without the delete file part in **storage.cpp**
`	void default_storage::delete_part_file(storage_error& ec)
	{
		// make sure we don't have the files open
		m_pool.release(this);

#if defined TORRENT_DEBUG_FILE_LEAKS
		print_open_files("release files", m_files.name().c_str());
#endif
 		// if there's a part file open, make sure to destruct it to have it
		// release the underlying part file. Otherwise we may not be able to
		// delete it
		if (m_part_file) m_part_file.reset();
		remove(combine_path(m_save_path, m_part_file_name), error);
		DFLOG(stderr, "[%p] delete partfile %s/%s [%s]\n", static_cast<void*>(this)
			, m_save_path.c_str(), m_part_file_name.c_str(), error.message().c_str());
		if (error != boost::system::errc::no_such_file_or_directory && !error)
		{ ec.file = -1; ec.ec = error; ec.operation = storage_error::remove; }
	}`

**Comment by arvidn** [comment]
would anyone mind giving this patch a try? https://github.com/arvidn/libtorrent/pull/537

**Comment by arvidn** [comment]
also, have anyone had a chance to confirm that this patch fixes the issue where the partfile may not be removed?

**Comment by sledgehammer999** [comment]
@Isabelxxx just so you don't confuse @arvidn more: qBittorrent deletes the relevant *.torrent file itself. Libtorrent doesn't have any idea where that files is nor it should. Libtorrent manages(and deletes) the actual files pointed by the *.torrent file and the partfile. Up until now when we told libtorrent to remove the torrent from the session we had 2 options. a) Remove the torrent as an entry from the session and b) remove the torrent as an entry AND delete the actual files that were downloaded. From #537 we have c) Remove torrent as an entry AND the partfile but leave the completed files. And b) removes partfile now too.

@arvidn I am trying to test your PR now.

**Comment by arvidn** [comment]
thanks. I feel pretty confident about this fix. at least that it won't make anything worse.

**Comment by sledgehammer999** [comment]
>thanks. I feel pretty confident about this fix. at least that it won't make anything worse.

While waiting for compilations to end:
Uhm, is it normal for the .parts file to go outside the root folder of the multi-file torrent? I am not talking about the path I am giving libtorrent. I am talking about the extra folder created by libtorrent for a multi-file torrent.
Is this how utorrent does it? (AFAIK utorrent is the only other client usign partfiles...)

**Comment by arvidn** [comment]
The reason I did it this way was to not have to worry about filename collisions, with files that are part of the torrent itself. Now, granted, the partfile name includes the info-hash, which would be very difficult to name a file in the torrent, but not theoretically impossible given enough effort. This just seemed like a simple way to avoid any such considerations.

**Comment by sledgehammer999** [comment]
I am just saying that if utorrent does it differently users will start bitching about it. Your call however.
PS: I see that you put a dot in front of the name to make the file hidden. On Windows that doesn't work. You need to set the hidden attribute explicitly.

**Comment by arvidn** [comment]
ah, yeah. I should make it hidden too. that makes sense, right?

**Comment by sledgehammer999** [comment]
>that makes sense, right?

Isn't that the reason you put a dot in front of the filename?

**Comment by Isabelxxx** [comment]
@sledgehammer999 
I think you got confused at some point, please read the entire discussion and see the post dates ;) 
 **#537 was posted after** my suggestion, not before. Before 537 there was no option to delete partfile + .torrent and that was what I writing about.

 #537 was done exactly following my suggestion and now as you say it works as it should be (a,b&c), not the opposite.

**Comment by arvidn** [comment]
@sledgehammer999 it makes sense to me :) but I can see it causing usability issues too. Especially around manually deleting content and being surprised there's something hidden left behind.

**Comment by sledgehammer999** [comment]
Well if you decide to not hide it then remember to remove the dot in front of the name otherwise linux/bsd/mac people won't see that file.

**Pull request merged**
