### PR TITLE
Add macOS arm64 support for cibuildwheel

### PR DESCRIPTION
**Pull request by xavier2k6**

### CODE REVIEW

**Comment by xavier2k6** [comment]
@arvidn This is still a WIP......

**Comment by xavier2k6** [comment]
@qstokkink, @arvidn made some changes with updated boost/python versions, please have a look, libsimulator used is outdated hence simulation failures.

**Comment by qstokkink** [comment]
I'm no Mac user and⸺as "just some random person"⸺I definitely have no say in the minimum supported Python version. However, your output suggests that `MACOSX_DEPLOYMENT_TARGET` should be set to `13` for `macos-13` and to `14` for `macos-14`.

**Comment by xavier2k6** [comment]
> I'm no Mac user and⸺as "just some random person"⸺I definitely have no say in the minimum supported Python version. However, your output suggests that `MACOSX_DEPLOYMENT_TARGET` should be set to `13` for `macos-13` and to `14` for `macos-14`.

I only changed mins for any possible deprecations/highlight issues.

**Comment by xavier2k6** [comment]
@arvidn Windows cibuildwheel passed in my latest changes, please review the `windows.yml` failures where I used Boost 1.82.0 whenever boost was being used.

**Comment by arvidn** [comment]
now might be a good time to retry this, on top of latest `RC_2_0`

**Comment by xavier2k6** [comment]
> now might be a good time to retry this, on top of latest `RC_2_0`

Having issues rebasing due to partial commit with libsimulator

**Pull request closed without merging**
