### PR TITLE
fix cmake install directory for absolute paths

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@krop @zeule is this an improvement?

**Comment by zeule** [comment]
> @krop @zeule is this an improvement?

What about other `CMAKE_INSTALL_xxxDIR` variables?

**Comment by arvidn** [comment]
well, I don't really know what I'm doing. I'm just trying to interpret some conclusion from https://github.com/arvidn/libtorrent/issues/5125

**Comment by zeule** [comment]
CMake defines [variables](https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html) for all the common destination dirs. Correcting one of them and leaving others as is might be surprising. We use two of the variables (LIB and INCLUDE) and `CMAKE_INSTALL_PREFIX` to generate compiler flags. Maybe we'd better somehow utilize `GNUInstallDirs_get_absolute_install_dir()` to get the absolute paths?

**Pull request merged**
