### PR TITLE
DHT router name lookups

### PR DESCRIPTION
**Pull request by arvidn**
attempt to postpone DHT until all outstanding dht router name lookups complete

### CODE REVIEW

**Comment by jpetso** [comment]
I think this looks good, would fix my personal use of libtorrent. If the assumption is that manual DHT calls such as `dht_get_item()`/`dht_put_item()`/`dht_announce()` etc. need to wait for a bootstrap alert then I think it should work fine.

One possible catch could be `add_dht_node()`, which is documented together with `add_router_node()` and appears to have the same qualities. After this patch, library users will also be required to wait until the bootstrap alert to add any further nodes. This should probably be documented. (In addition, the fact that users should wait until the bootstrap alert for any actions in the first place would also be nice to have in the API docs.)

**Comment by arvidn** [comment]
should ``add_dht_node()`` also postpone starting the DHT? I was under the impression that it's fine to add a node while bootstrapping (it just won't be used during the bootstrap, but it's likely to stay in the routing table once it's done)

**Comment by jpetso** [comment]
It's not the postponing that would change `add_dht_node()`, it's that `m_dht` will be null (it's still waiting for the address resolution) and therefore `add_dht_node()` doesn't even try to add the node.

**Comment by arvidn** [comment]
how about now?

**Comment by jpetso** [comment]
I like it! r+ after considering the above comment, except you don't actually need it since it's your own project :)

**Comment by jpetso** [comment]
Thanks!

**Pull request merged**
