### PR TITLE
fix port mapping for SSL UDP socket

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
It still tries to portmap port 4433 even after ssl_listen is zero.

>@sledgehammer999 in (3), is it mapping TCP or UDP?

Well, I can't tell. `portmap_alert` doesn't have any useful member for this. I only use the message() function and it tells me:
>successfully mapped port using UPnP. external port: 4433

**Comment by arvidn** [comment]
is it possible the port mapping attempt was initiated _before_ disabling the ssl socket? With this patch, the mapping is supposed to be deleted when the socket is closed (for the SSL UDP socket).

**Comment by arvidn** [comment]
I will update portmap_alert to include which protocol it refers to. however, there are no alerts for when mappings are successfully removed. So, if you start up with ssl_socket enabled, then disable it, I would expect you to see one portmap_alert for the ssl socket still.

**Comment by sledgehammer999** [comment]
No I get this alert when I change listen port. Many second after the GUI has come up. I get the normal success message for the new port that I chose but there is one extra for port 4433.
And if I change port again I get it again.

**Comment by sledgehammer999** [comment]
I saw that you pushed another commit. I'll be able to test tomorrow again.

Something a bit offtopic:
Is this a typo? `utp_ssl` -> `udp_ssl` in [this](https://github.com/arvidn/libtorrent/blob/RC_1_1/include/libtorrent/alert_types.hpp#L1311) line.

**Comment by arvidn** [comment]
udp and utp is intentional. the reasoning is that SSL only runs on top of uTP (since it requires a stream, not datagrams). So the UDP socket that's opened for SSL/uTP traffic won't be used for anything else, whereas the other UDP socket will be used for DHT and UDP trackers as well, so that's a more generic UDP socket.

**Comment by sledgehammer999** [comment]
Both bugs fixed now.
1. It doesn't try anymore to map port 4433 when ssl is closed
2. I no longer get an alert for TCP/0 when changing ports.

However it still fails the initial rebinding for UDP after closing the ssl port (aka #454)

**Comment by sledgehammer999** [comment]
PS: Your last commit has a typo in the commit message. `git commit --amend` is your friend.

**Comment by arvidn** [comment]
I have a feeling #454 depends on specific windows version. what are you on?

**Comment by sledgehammer999** [comment]
Windows 7 sp1 64bit

**Pull request merged**
