### PR TITLE
fix windows file preallocation issue

### PR DESCRIPTION
**Pull request by ajax16384**
GetFileInformationByHandleEx and GetCompressedFileSize will lie about real space allocation so "set_file_valid_data" will never be called for just preallocated file.
Let's always try to call "set_file_valid_data" on file::set_size change

### CODE REVIEW

**Comment by ajax16384** [comment]
https://gist.github.com/ajax16384/c0a9b1e50a307bc8f656622f801badea#file-setfilevaliddata-c-L78 this one gives "virtually" preallocated value (not 0 for new file) so old libtorrent code will never called it's "SetFileValidData"

**Comment by arvidn** [comment]
it seems like this should be back ported to RC_1_1 too, does that make sense?

**Comment by ssiloti** [comment]
Yeah. I realized after hitting merge this should have gone to RC_1_1. Sorry.

**Comment by ajax16384** [comment]
NP: https://github.com/arvidn/libtorrent/pull/2376

**Pull request merged**
