### PR TITLE
add option to build against library isa-l_crypto (intel) no SSL support

### PR DESCRIPTION
**Pull request by joriscarrier**
see #6112

### CODE REVIEW

**Comment by arvidn** [comment]
this seems fine, but my understanding is that you won't see any speed-ups this way. iiuc, ISA-L gains a speed advantage when you can compute many hashes in parallel. There are a few places where that's somewhat easy to do (like in v2 merkle trees) but to do it for piece hashes would be quite complicated.

**Comment by arvidn** [comment]
have you measured any improvements?

**Comment by arvidn** [comment]
the spell checker caught one typo. some new words need to be added to the dictionary and a default for the preprocessor macro, to define it as 0 would need to be added

**Comment by joriscarrier** [comment]
> have you measured any improvements?

No, I didn't measure any improvement, it would be the opposite

**Comment by arvidn** [comment]
> > have you measured any improvements?
> 
> No, I didn't measure any improvement, it would be the opposite

what does "it" refer to?
Do you mean that using ISA-L causes a performance regression? If you haven't measured, we wouldn't know I'd think.

**Pull request closed without merging**
