### PR TITLE
Test merge

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew can you take a look at the top commit to make sure it looks right?
The "test command" `python test.py` won't work in `master` since you split up the tests into multiple files. I changed it to `tox -e` instead. That command doesn't work for me locally (on ubuntu). I think it's because I don't have boost installed. It wasn't very clear from the documentation that `tox -e` is the way to run the tests either.

**Comment by arvidn** [comment]
that didn't work. @AllSeeingEyeTolledEweSew is there an elegant way to fix this?

**Comment by AllSeeingEyeTolledEweSew** [comment]
checking. I think I can just PR against your `test-merge` branch.

**Comment by arvidn** [comment]
@AllSeeingEyeTolledEweSew I don't understand why this is failing for me: https://github.com/arvidn/libtorrent/runs/4437995355?check_suite_focus=true

**Comment by AllSeeingEyeTolledEweSew** [comment]
```
2021-12-07T00:28:07.4157512Z py run-test: commands[1] | /home/runner/work/libtorrent/libtorrent/.tox/py/bin/python -m pip install --upgrade --force-reinstall --ignore-installed --find-links=dist libtorrent
2021-12-07T00:28:07.9319816Z Looking in links: dist
2021-12-07T00:28:08.0132125Z Collecting libtorrent
2021-12-07T00:28:08.1148000Z   Downloading libtorrent-2.0.5-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (8.6 MB)
2021-12-07T00:28:08.4111238Z Installing collected packages: libtorrent
2021-12-07T00:28:08.5834299Z Successfully installed libtorrent-2.0.5
```

Whoops, the `tox` config actually installs libtorrent from pypi now, instead of installing the local artifact.

Use this

```patch
diff --git a/tox.ini b/tox.ini
index 0f2bd2c54..852fccf33 100644
--- a/tox.ini
+++ b/tox.ini
@@ -42,7 +42,7 @@ deps =

 commands =
     {envpython} setup.py bdist_wheel
-    {envpython} -m pip install --upgrade --force-reinstall --ignore-installed --find-links=dist libtorrent
+    {envpython} -m pip install --upgrade --force-reinstall --ignore-installed --find-links=dist --no-index libtorrent
     {envpython} -m pip install -r test-requirements.txt
     {envpython} -X dev -m pytest --log-level=DEBUG --log-cli-level=DEBUG
     {envpython} -m mypy --config-file mypy-tox.ini tests
```

**Pull request merged**
