### PR TITLE
Test merge

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by qstokkink** [comment]
I see there are still some wheel errors:

```
error: Skipping analyzing "libtorrent": module is installed, but missing library stubs or py.typed marker
```

The Python type stubs are not ending up in [the right folders in the wheel (click me for step-by-step MyPy instructions)](https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages). Inside of the wheel, `__init__.pyi` and `py.typed` ended up in the `/libtorrent-2.1.0.data/data/libtorrent` directory instead of the `/libtorrent/` directory.

**Comment by arvidn** [comment]
this is what I see in the log:
```
    creating build/bdist.macosx-10.9-x86_64
    creating build/bdist.macosx-10.9-x86_64/wheel
    creating build/bdist.macosx-10.9-x86_64/wheel/libtorrent
    copying build/lib.macosx-10.9-x86_64-cpython-37/libtorrent/__init__.cpython-37m-darwin.so -> build/bdist.macosx-10.9-x86_64/wheel/libtorrent
    running install_data
    creating build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0.data
    creating build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0.data/data
    creating build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0.data/data/libtorrent
    copying install_data/libtorrent/__init__.pyi -> build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0.data/data/libtorrent
    copying install_data/libtorrent/py.typed -> build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0.data/data/libtorrent
    running install_egg_info
    running egg_info
    writing libtorrent.egg-info/PKG-INFO
    writing dependency_links to libtorrent.egg-info/dependency_links.txt
    writing top-level names to libtorrent.egg-info/top_level.txt
    reading manifest file 'libtorrent.egg-info/SOURCES.txt'
    writing manifest file 'libtorrent.egg-info/SOURCES.txt'
    Copying libtorrent.egg-info to build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0-py3.7.egg-info
    running install_scripts
    creating build/bdist.macosx-10.9-x86_64/wheel/libtorrent-2.1.0.dist-info/WHEEL
    creating '/private/var/folders/v_/hyh3_pjd2rx2qn6110n50l500000gn/T/pip-wheel-95g5j_v6/.tmp-9_42nlc7/libtorrent-2.1.0-cp37-cp37m-macosx_10_14_x86_64.whl' and adding 'build/bdist.macosx-10.9-x86_64/wheel' to it
    adding 'libtorrent/__init__.cpython-37m-darwin.so'
    adding 'libtorrent-2.1.0.data/data/libtorrent/__init__.pyi'
    adding 'libtorrent-2.1.0.data/data/libtorrent/py.typed'
    adding 'libtorrent-2.1.0.dist-info/METADATA'
    adding 'libtorrent-2.1.0.dist-info/WHEEL'
    adding 'libtorrent-2.1.0.dist-info/top_level.txt'
    adding 'libtorrent-2.1.0.dist-info/RECORD'
    removing build/bdist.macosx-10.9-x86_64/wheel
    Building wheel for libtorrent (pyproject.toml): finished with status 'done'
```

Are you suggesting that all files added to `libtorrent-2.1.0.data` should really go into the `libtorrent` directory instead? what about the `dist-info` directory, is that correct?

It's quite mysterious to me what those directories are supposed to look like and what's controlling them.

**Comment by qstokkink** [comment]
Sorry about the late reply, I had some papers to review this weekend.

> Are you suggesting that all files added to libtorrent-2.1.0.data should really go into the libtorrent directory instead? what about the dist-info directory, is that correct?

Yes, and yes. I think the `data_files` argument that is used in `setup.py` is also deprecated now. The  `dist-info` directory should be in the correct location.

**Comment by qstokkink** [comment]
This _should_ be an easy fix ("famous last words"). I think I can make a quick patch for this.

**Pull request merged**
