### PR TITLE
fix boost 1.73.0 beta 1

### PR DESCRIPTION
**Pull request by pavel-pimenov**

### CODE REVIEW

**Comment by arvidn** [comment]
Do you understand how boost version affects this?

**Comment by pavel-pimenov** [comment]
no :-(  
error build VC++ 2019 v 16.5.4

**Comment by arvidn** [comment]
probably some boost header used to include `cstddef` before, and not anymore

**Comment by pavel-pimenov** [comment]
1>add_scalar.cpp
1>Note: including file: C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/disable_warnings_push.hpp
1>Note: including file: C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/ed25519.hpp
1>Note: including file:  C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/export.hpp
1>Note: including file:   C:\vc17\r6xx\boost\boost/config.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/user.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/detail/select_compiler_config.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/compiler/visualc.hpp
1>Note: including file:     C:\vc17\r6xx\boost\boost/config/pragma_message.hpp
1>Note: including file:      C:\vc17\r6xx\boost\boost/config/helper_macros.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/detail/select_stdlib_config.hpp
1>Note: including file:     C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\version
1>Note: including file:      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\yvals_core.h
1>Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vcruntime.h
1>Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\sal.h
1>Note: including file:         C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\concurrencysal.h
1>Note: including file:        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\vadefs.h
1>Note: including file:       C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xkeycheck.h
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/stdlib/dinkumware.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/detail/select_platform_config.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/platform/win32.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/config/detail/suffix.hpp
1>Note: including file:   C:\vc17\r6xx\libtorrent\include\libtorrent/config.hpp
1>Note: including file:    C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/disable_warnings_push.hpp
1>Note: including file:    C:\vc17\r6xx\boost\boost/version.hpp
1>Note: including file:    C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/disable_warnings_pop.hpp
1>Note: including file:    C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/export.hpp
1>Note: including file:   C:\vc17\r6xx\libtorrent\include\libtorrent/aux_/deprecated.hpp
1>Note: including file:  C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stddef.h
1>Note: including file:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\corecrt.h
1>C:\vc17\r6xx\libtorrent\include\libtorrent\aux_\ed25519.hpp(12,101): error C2039: 'ptrdiff_t': is not a member of 'std'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt\stddef.h(19): message : see declaration of 'std'
1>C:\vc17\r6xx\libtorrent\include\libtorrent\aux_\ed25519.hpp(13,108): error C2039: 'ptrdiff_t': is not a member of 'std'

**Pull request merged**
