### PR TITLE
Change sha1_hash __init__ to use a std::string

### PR DESCRIPTION
**Pull request by aresch**
This fixes compatibility with Python 3's bytes object.

### CODE REVIEW

**Comment by arvidn** [comment]
thanks! looks good. would you mind updating ChangLog and merge it into master too?

**Comment by arvidn** [comment]
another thing, do you have a windows box by any chance? if so, would you mind testing that these installers come out in working condition?

https://ci.appveyor.com/project/arvidn/libtorrent/build/1.0.878/job/k7xnol5ya5jaycph/artifacts

**Comment by aresch** [comment]
Nope, no windows box.

I'll work on the other requests.

**Comment by arvidn** [comment]
thanks! In fact, (at least in master) there's a test.py to just make sure the python bindings aren't completely broken (tested in travis and appveyor). It might make sense to include constructing a sha1_hash in there

**Pull request merged**
