### PR TITLE
cmake: install pdb files

### PR DESCRIPTION
**Pull request by jagannatharjun**

### CODE REVIEW

**Comment by arvidn** [comment]
can you explain what this does?

**Comment by jagannatharjun** [comment]
> can you explain what this does?

it installs PDB files on MSVC with library and others.

**Review by arvidn — APPROVED** [review]

**Comment by Chocobo1** [comment]
@jagannatharjun 
I'm getting errors (cmake 3.21.3):
```
CMake Error:
  Error evaluating generator expression:

    $<TARGET_PDB_FILE:torrent-rasterbar>

  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.
```
with the following cmake commands:
```
cmake  -B "build"  -G "Visual Studio 16 2019"  -A "x64"  -DCMAKE_BUILD_TYPE=Release  -DBUILD_SHARED_LIBS=OFF  -Dstatic_runtime=ON .\
```

**Comment by arvidn** [comment]
is this not covered by CI then?

**Comment by Chocobo1** [comment]
>is this not covered by CI then?

I suppose not. I only saw limited cmake + Windows on appveyor CI and it does not build static library.
https://gitlab.kitware.com/cmake/cmake/-/issues/16932

**Pull request merged**
