### PR TITLE
undo the patch to restore incoming TCP connections over SOCKS5

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by aldenml** [comment]
any comment for this revert?

**Comment by arvidn** [comment]
yeah, over at the tribler project they said their download through tunnels has broken, and that they were making libtorrent connect to their tunnel via a SOCKS5 interface. I got the impression that they relied on this feature, of extending ``BIND`` to support incoming TCP connections (more generic than old school FTP connections). After a while it turned out they only use uTP connections, and only rely on the ``UDP ASSOCIATE`` socks5 command. Which is well defined and worked all along (or at least supposed to work).

I prefer to not have all this code here, since I'm not aware of a single socks5 proxy that actually implements this more generic interpretation of ``BIND``.

**Comment by arvidn** [comment]
Here's the reference: https://github.com/Tribler/tribler/issues/3353

**Comment by aldenml** [comment]
thanks for the explanation!

**Pull request merged**
