### PR TITLE
Default python bindings to crypto=openssl

### PR DESCRIPTION
**Pull request by AllSeeingEyeTolledEweSew**
Per discussion in #6188 and #6448.

Draft until there's consensus that this is a good plan.

The `test.py` changes backport a lot of infrastructure I added in `master`. I'll make a separate PR for `master` for a cleaner merge.

### CODE REVIEW

**Comment by arvidn** [comment]
I've been thinking that it would probably make sense to set `crypto=openssl` as the default for the main target as well.

**Comment by AllSeeingEyeTolledEweSew** [comment]
After the investigations I did in #6448, I would think Apple's crypto APIs would be preferable to openssl. I haven't looked into it, but in theory it should be one less dependency to install, for both build and runtime.

**Comment by AllSeeingEyeTolledEweSew** [comment]
@arvidn do you have an opinion on shipping libtorrent with openssl vendored? Would you mind responding in #6448?

**Comment by AllSeeingEyeTolledEweSew** [comment]
As #6448 has your approval, I marked this ready for review

**Pull request merged**
