### PR TITLE
async torrent property queries

### PR DESCRIPTION
**Pull request by arvidn**
add async download queue query, post_download_queue()
add async file_progress query, post_file_progress()
add async peer_info query, post_peer_info()
add async piece availibility query, post_piece_availibility()

### CODE REVIEW

**Comment by glassez** [comment]
> add async download queue query, post_download_queue() add async file_progress query, post_file_progress() add async peer_info query, post_peer_info()

There are at least the following need to be added:
piece_availability
url_seeds
trackers

**Comment by glassez** [comment]
Does it intend to be backported into 1.2.x branch?

**Comment by arvidn** [comment]
> There are at least the following need to be added:
> piece_availability

Right.

> url_seeds
> trackers

Would it be unreasonable to use `torrent_handle::save_resume_data()` for `trackers` and `url_seeds`?

> Does it intend to be backported into 1.2.x branch?

I'm not planning on doing that. I consider it a bit of a stretch to put in RC_2_0.

**Comment by glassez** [comment]
> Would it be unreasonable to use `torrent_handle::save_resume_data()` for `trackers` and `url_seeds`?

Returned `url_seeds` seems to be slightly different than `torrent_handle::url_seeds()`.
Returned `trackers` is tracker URLs only whereas `torrent_handle::trackers()` returns list of filled `announce_entry` structs.

**Comment by glassez** [comment]
> > Does it intend to be backported into 1.2.x branch?
> 
> I'm not planning on doing that.

Unfortunately it makes no sense for me to use it as long as qBittorrent supports libtorrent-1.2.

**Pull request merged**
