### PR TITLE
fix documentation generation script, and run it on travis

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@aresch does this look ok?

**Comment by arvidn** [comment]
@FranciscoPombal I updated the patch to work for building pdfs too

**Comment by FranciscoPombal** [comment]
@arvidn 
`make` now completes successfully. There are still some warnings in the output though, but I am not sure about their severity. Here is the output:
https://gist.github.com/FranciscoPombal/2e185dbc7da14bedf44bba4494c95524

Also, any word on when the website (`libtorrent.org`) might be updated with the latest docs? Are you waiting for the `1.2.0` release before updating the website?

**Comment by FranciscoPombal** [comment]
@arvidn 
Also, as part of this PR, you might want to ajust .gitignore; after generating the docs, `git status` reports the following:

```
libtorrent/docs$ git status
On branch fix-doc-generation-script
Your branch is up to date with 'origin/fix-doc-generation-script'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   read_disk_buffers.png
	modified:   write_disk_buffers.png

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	building.pdf
	client_test.pdf
	contributing.pdf
	dht_extensions.pdf
	dht_rss.pdf
	dht_sec.pdf
	dht_store.pdf
	examples.pdf
	extension_protocol.pdf
	features.pdf
	hacking.pdf
	index.pdf
	manual-ref.pdf
	plain_text_out.txt
	projects.pdf
	python_binding.pdf
	settings.rst
	single-page-ref.pdf
	stats_counters.rst
	streaming.pdf
	troubleshooting.pdf
	tuning.pdf
	tutorial.pdf
	udp_tracker_protocol.pdf
	upgrade_to_1.2-ref.pdf
	utp.pdf

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by arvidn** [comment]
libtorrent.org is updated with the stable version's documentation every time there's a new release. currently, that's 1.1.9 (i.e. `RC_1_1` branch)

**Comment by FranciscoPombal** [comment]
@arvidn 
This is what I see on my end, and it has been like this for some time:
image

**Comment by aresch** [comment]
LGTM

**Comment by arvidn** [comment]
@FranciscoPombal yes, it should

**Pull request merged**
