### PR TITLE
attempt to fix udp socket re-binding issue on windows

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by sledgehammer999** [comment]
This isn't enough. I still get the error upon udp rebinding:
>Only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by LordNyriox** [comment]
@arvidn:  Elsewhere, @sledgehammer999 commented that the last working commit was [https://github.com/arvidn/libtorrent/commit/602dc0275b4a3b5fb67e0aeb0cf2ec373f3945ae].  Therefore, the root of the problem can probably be found in the commit after it, which is [https://github.com/arvidn/libtorrent/commit/45cff5837f7b4af58fd7a699b1638a9d9de9a8ef].  

Thanks,
- Nyriox

**Comment by arvidn** [comment]
@LordNyriox did you confirm that [45cff58] caused the problem? (I don't think sledgehammer's comment meant to suggest that there are _no_ later working version, just that the breakage did not happen before the revision he mentioned)

**Comment by sledgehammer999** [comment]
@arvidn let me refresh you memory and clarify some things.
The udp rebinding issue manifested in 2 stages.
The first stage was encountered by some users here and there during the 1.0.x lifetime. The reports were spurious and at first I dismissed them as "change your port because some other app is using them.". I couldn't replicate the problem.
The 2nd stage came very recently after 1.0.8. This time I can reproduce it 100%. I imagine the underlying cause is the same as for RC_1_1 and the only real solution for stage 1 is for you to not try to rebind the ports (udp/tcp/ssl) if that specific port-protocol combo didn't change. Like you already do with RC_1_1.

For me it works up to commit 602dc02. The next commit gives me the udp rebinding error. The same happens with the HEAD of RC_1_0.

But I suspect 602dc02 still suffers from "stage 1".

**Comment by arvidn** [comment]
I see, so it *is* the patch LordNyriox pointed out that caused the problems then. That's a bit surprising. I don't quite understand how they can be related.

For RC_1_0 I'm not really hoping to fix "stage 1", but just the one that you can easily reproduce.

Can you think of how the enumerating network adapters could affect this for you? Is it the case that it fails to find *any* devices with this patch perhaps?

**Comment by DrKittens** [comment]
> Can you think of how the enumerating network adapters could affect this for you? Is it the case that it fails to find any devices with this patch perhaps?
I'm probably wrong but a thought.
Maybe its not a port bind issue, and instead its libtorrent failing to correctly bind to a working adapter?

**Comment by sledgehammer999** [comment]
Well, I don't know but the alert says it fails for interface `0.0.0.0`. Maybe it contains wrong info.
I'll try to build current HEAD of RC_1_0 with that commit reverted.

**Comment by sledgehammer999** [comment]
Yes, reverting https://github.com/arvidn/libtorrent/commit/45cff5837f7b4af58fd7a699b1638a9d9de9a8ef and building HEAD of RC_1_0 makes it work again.
The sad thing is I don't know much about WINAPI to contribute further.

**Comment by LordNyriox** [comment]
@arvidn, @sledgehammer999:  The problem described by @DrKittens is indeed a possibly related issue.  

Can you guys test in a Windows environment with the `IP Helper` service disabled (with current official 1.0.9), and see if that fixes the issue?  

The `IP Helper` service runs those virtual network interfaces, and is a good idea to disable it on any Windows system IMO.  


Thanks, 
~ Nyriox

**Comment by sledgehammer999** [comment]
>The IP Helper service runs those virtual network interfaces, and is a good idea to disable it on any Windows system IMO. 

It doesn't change it for me.

**Comment by LordNyriox** [comment]
@sledgehammer999:  Interesting.  Try re-enabling `IP Helper` and running 

`netsh int teredo set state disabled` 
`netsh int isatap set state disabled` 
`netsh int 6to4 set state disabled`

I honestly never checked if the 'tunnel adapters' actually disappear once the `IP Helper` service is disabled, since I usually run those commands first anyway… 

Thanks, 
~ Nyriox

**Comment by arvidn** [comment]
is it safe to assume that the EXCLUSIVE_ADDRUSE option does not affect either of the two issues?

**Comment by LordNyriox** [comment]
@sledgehammer999:  Keep in mind that I am not having any DHT issues on my version of qBittorrent (@Gelmir's latest builds use libtorrent 1.0.9), and I am on Windows 7 64-bit.

**Comment by LordNyriox** [comment]
@arvidn:  Correct.  As of right now the issue seems to be network interface related, rather than exclusive-address related.  

You might see if you can attempt to filter out Microsoft's "IPv6 transition technologies", which Windows treats as if they were physical network adapters, from the list of possible network interfaces seen by libtorrent.

**Comment by arvidn** [comment]
one possibly significant difference before and after that patch [45cff58] is that if GetAdapterAddresses could not be found, it would previously fall back on SIO_GET_INTERFACE_LIST which it no longer does. could this be causing the problem? I would be surprised, but maybe some people don't have iphlpapi.dll

**Comment by arvidn** [comment]
it's kind of a long shot, but does this help? https://github.com/arvidn/libtorrent/pull/589

**Comment by DrKittens** [comment]
I have not been able to replicate this bug under the old 1.0 head, the only adapter related settings i have in my setup are disabling ipv6 & removing isatap adapters.
Hence why i suggested it been an adapter fault.

**Comment by arvidn** [comment]
@sledgehammer999 do you think you (or anyone else who experience this problem) could step through the old and new version of enum_net_interfaces() to see what's different between the runs? I will try to run through it on my windows machine, but I can't reproduce the problem so I'm not too optimistic.

Also, I'm curious, does this happen if you specify an IP address to bind to? as far as I can tell, enum_net_interfaces is only used to determine our IPv4 and IPv6 address in the session (in RC_1_0).

another test that might be interesting is to run examples/enum_if before and after this patch, to see if the output differs.

**Comment by sledgehammer999** [comment]
I just tried by setting my specific ethernet adapter. Still fails. I'll try the other suggestions tomorrow.

**Comment by arvidn** [comment]
I wonder if it's timing related. The main purpose of the patch to enum_net_interfaces was to optimize it. It's much more likely to only require a single call now, previously it would always make two calls to enumerating the interfaces (and apparently a call can be quite expensive).

If this call takes less time now, perhaps there's less time between closing and re-binding a socket to the same endpoint now, and perhaps a socket keeps a port allocated for a millisecond or so after being closed.

**Comment by arvidn** [comment]
another possibly interesting thing to test would be to just say "return std::vector<ip_interface>();" at the top of the enum_net_interfaces() function, and see how that affects things. and possibly also adding a Sleep(100) at the top.

**Comment by sledgehammer999** [comment]
As you've guessed it this is a timing issue. I put a Sleep(100) at the top and it works. I didn't test returning an empty vector though.

**Comment by sledgehammer999** [comment]
>I didn't test returning an empty vector though.

I tried it now. It fails.

**Comment by arvidn** [comment]
I replaced this branch with a simpler patch that just inserts a delay when closing the udp socket. @sledgehammer999 would you mind testing if this is equivalent/sufficient to fix the issue?

**Comment by sledgehammer999** [comment]
This works for me. I am waiting a "stage 1" user to confirm too.

**Comment by arvidn** [comment]
great. thanks for testing!

**Comment by DrKittens** [comment]
@Sledgehammer999
Wild and probably wrong drunken thought.
Do you always pack qbt releases with UPX or just 3.3.4?
If UPX performs the decompress via temp file method it **breaks argv[0]** which could lead to the stage1 problem (unless stage1 is replicable in pure libtorrent?)

**Comment by sledgehammer999** [comment]
I don't know how argv[0] is related but only the installer is UPX compressed.

**Comment by DrKittens** [comment]
It is not, i had things mixed up and re-reading my comment makes me want to facepalm >_>

**Pull request merged**
