### PR TITLE
improve rendering of integers in bencoding and improve testing

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@aldenml the wolfssl test seems to fail *really* often in most of my PRs. I tried to make it happen locally , with wolfss, on ubuntu, but couldn't get it to fail. Do you have any theory of what might be going on?

**Comment by aldenml** [comment]
I saw you restarted the job and I can't find a failed one, so no idea :) let me know when you have another one, please.

**Comment by arvidn** [comment]
this one has failed repeatedly since I posted this PR. probaby 6-7 times or so. Here are a few other PRs failing on this test:

https://travis-ci.org/arvidn/libtorrent/builds/628360620?utm_source=github_status&utm_medium=notification
https://travis-ci.org/arvidn/libtorrent/builds/628080336?utm_source=github_status&utm_medium=notification

**Comment by aldenml** [comment]
I see, it seems that test_url_seed is a problematic one (https://travis-ci.org/arvidn/libtorrent/jobs/628360628#L9263), I will take a look at it

**Comment by aldenml** [comment]
btw, I just found https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support

**Pull request merged**
