### PR TITLE
test building the C binding on travis

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by vkpidwlk** [comment]
any update on this PR or the C bindings in general? :smile:

**Comment by arvidn** [comment]
When I started to try to get them built on travis, I realized how out-of-date they were. So I started to fix them up. That turned out to be a lot of work though, because they don't support any proper asynchronous notifications (which alerts are used for). So I put it on ice. Maybe one day I'll try to make them useful, but I find it hard to justify working on them instead of of the core library

**Comment by aldenml** [comment]
I propose close this PR and move it to a possible task like a regular issue, since it could potentially involve quite a few questions related to API design.

**Comment by arvidn** [comment]
yeah, the reason I kept it open was not to loose track of the branch with these changes so far. but since then I've started to clean up merged branches, so it should be ok to close this now

**Pull request closed without merging**
