### PR TITLE
use alternative stop build syntax for invariant_check & asserts

### PR DESCRIPTION
**Pull request by ajax16384**

### CODE REVIEW

**Comment by arvidn** [comment]
I broke master in my RC_1_1 merge. It's been fixed now, would you mind rebasing?

**Comment by ajax16384** [comment]
np

**Comment by arvidn** [comment]
lgtm. thanks!

**Comment by arvidn** [comment]
appveyor seems to be having problems right now..

**Comment by aldenml** [comment]
@arvidn I remember last time you needed to manually cancel all the jobs and wait a little

**Comment by arvidn** [comment]
yeah, let's this turn green first though: https://appveyor.statuspage.io/

**Pull request merged**
