### PR TITLE
set HTTP Host to request-target when using proxy

### PR DESCRIPTION
**Pull request by patch3proxyheaders915360**
To make the Host field carry the request-target it is enough to set
the Host information before changing the connection destination.

Many proxies rely on the Host field-value to route requests
in a violation of RFC7230 section 5.4.

https://tools.ietf.org/html/rfc7230#section-5.4

A request with the Host field set to the proxy hostname and port
in place of the request-target produces error responses and otherwise
confuses such misconfigured middleboxes.

### CODE REVIEW

**Comment by patch3proxyheaders915360** [comment]
Here's a relevant bug discussion started by affected users https://github.com/qbittorrent/qBittorrent/issues/8972

**Comment by arvidn** [comment]
this patch looks correct. but it should be made against `RC_1_2`, right?

**Comment by arvidn** [comment]
it looks like some tests may have to be updated as well

**Comment by patch3proxyheaders915360** [comment]
So what do I do, rebase it against RC_1_2 and file another PR?

**Comment by arvidn** [comment]
you can actually update the PR to be against `RC_1_2`, but most likely you'll have to rebase the branch too

**Comment by patch3proxyheaders915360** [comment]
I found that git-cherry-pick works better than rebase, but I can't change the head repository branch.

I decided to file a new PR. https://github.com/arvidn/libtorrent/pull/3863

**Pull request closed without merging**
