### PR TITLE
Documentation for deprecated members

### PR DESCRIPTION
**Pull request by Falcosc**
https://github.com/arvidn/libtorrent/issues/674

### CODE REVIEW

**Comment by arvidn** [comment]
lgtm

**Comment by Falcosc** [comment]
@arvidn should I add ip packet overhead to metrics or did we remove it on purpose because it's an estimation?

**Comment by arvidn** [comment]
it hasn't been removed, they're called ``sent_ip_overhead_bytes`` and ``recv_ip_overhead_bytes``

**Comment by Falcosc** [comment]
Oh, sorry than I have to modify the documentation. I didn't find them because the old handler does not call them

https://github.com/arvidn/libtorrent/blob/4f7b69be90b438e2657da93fcc22683f7c3e84dd/src/session_impl.cpp#L3008

**Comment by arvidn** [comment]
yeah, I recently fixed this in RC_1_1 but I haven't merged it over since

**Pull request merged**
