### PR TITLE
create session_handle

### PR DESCRIPTION
**Pull request by ssiloti**
The session_handle class exposes the same public interface to session_impl as
the session class. The difference being that session_handle does not own the
underlying session_impl so multiple session_handle instances can be created
and copied about as needed.

The intent is to change the plugin API to pass an instance of session_handle
instead of a pointer to session_impl. This change will be made in a separate
patch.

To maintain ABI compatibility, the type signature of session was not changed.
The relevant functions have been modified to forward to session_handle and
all enums have been left in session.

### CODE REVIEW

**Comment by arvidn** [comment]
is the idea that session_handle is part of the public API, and exported from a DLL?
is it materially different from just passing around a pointer to a session object to the plugins? Is that difficult because session_impl doesn't know about its owner?

**Comment by ssiloti** [comment]
Yes, the idea is to make session_handle part of the public API. The reason I didn't think just passing a pointer to the session object would work is that, based on the comments for the session_proxy class, the underlying session_impl may outlive its session object in which case plugins might try to de-reference a stale pointer.

The session_impl class could be changed to use a weak_ptr but it seemed unnecessary since plugins are already guaranteed not to be called after the session_impl object is destroyed.

**Comment by arvidn** [comment]
can you think of ways to reuse the session object? I'm a little bit worried about basically increase the number of exported symbols by 50% (not quite but I think session and torrent_handle are the main classes). You're right that the session is owned by the client and may be destructed before session_impl, if its held by a session_proxy (which is a bit of a strange name, the only purpose of it is to be able to destruct sessions in parallel). Would it be possible to make session just a holder (basically a shared_ptr) and have the public API only exist in one class, which may outlive the main session object.

I don't have a complete thought here.

**Comment by ssiloti** [comment]
I can certainly do something like that. The only reason I didn't was to preserve ABI compatibility. If you're OK with an ABI break then I'd be happy to refactor this.

**Comment by arvidn** [comment]
yeah, master is already ABI incompatible with 1.0.x. The convention I use is to break ABI with major releases but not with point releases. And do my best to keep API compatibility.

**Comment by arvidn** [comment]
cool. would you mind adding session_handle.hpp to the include/libtorrent/Makefile.am as well? (this makes sure it gets included in "make dist" tarballs), and maybe to CMakeList.txt (I don't regularly test cmake, but I try to at least keep new files up-to-date in there).

**Comment by ssiloti** [comment]
session_handle is already in CMakeLists.txt

**Comment by arvidn** [comment]
This patch needs to be rebased. I believe it also conflicts with pull request 22. Do you have an opinion about merge order?

**Comment by ssiloti** [comment]
You sure this needs to be rebased? I just did a test merge and it merges cleanly to master with all tests passing. As for merge order, I say first-come-first serve, but I may be biased since that means less work for me :)

**Comment by ssiloti** [comment]
Oh I see, seems github is more cautious than git about automatic merging. I've gone ahead an rebased the branch.

**Pull request merged**
