### PR TITLE
back-port preformatted entry

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by arvidn** [comment]
@sledgehammer999 do you think this is ABI compatible?

**Comment by sledgehammer999** [comment]
Sorry, I wish I could answer you. My knowledge is limited in this field. Maybe @glassez knows better.

**Comment by sledgehammer999** [comment]
Sidenote: I confirm that this patch works.

**Comment by glassez** [comment]
I don't know much about it. IIRC it should be backward-compatible since it does not modify the existing names, but only adds a new (I mean one new entry constructor).

**Pull request merged**
