### PR TITLE
improve performance of flush_cache in disk_io_thread

### PR DESCRIPTION
**Pull request by arvidn**
by reducing piece lookups

### CODE REVIEW

**Comment by arvidn** [comment]
@ssiloti do you have any other ideas about https://github.com/arvidn/libtorrent/issues/3246 and does this patch look reasonable?

**Comment by arvidn** [comment]
I suspect this is a legitimate issue: https://travis-ci.org/arvidn/libtorrent/jobs/427861699#L1471

**Comment by arvidn** [comment]
I can't get this to work. Some invariants that I expect don't seem to be maintained in the cache. I would much rather work on the patch where the cache is removed

**Comment by ssiloti** [comment]
I can understand that. Just reviewing this patch made me look forward to the day when all this code is gone.

**Comment by arvidn** [comment]
closing again. if someone else feels strongly that this should be improved, feel free to revive and take over the branch.

**Pull request closed without merging**
