### PR TITLE
Added protection for total_size in set_piece_hashes

### PR DESCRIPTION
**Pull request by aldenml**
@arvidn I added the necessary assert, otherwise all the logic get corrupt, but not sure how to handle it. Waiting for your comment.

### CODE REVIEW

**Comment by arvidn** [comment]
that seems reasonable

**Comment by arvidn** [comment]
the error seems legitimate as far as I can tell, and unrelated to your change.

**Comment by aldenml** [comment]
This seems to uncover a problem in a test: https://github.com/arvidn/libtorrent/blob/master/test/test_torrent.cpp#L254

**Comment by aldenml** [comment]
I decided to reduce the PR to the minimal protection that it's necessary in `set_piece_hashes`.

**Comment by arvidn** [comment]
this looks like a good change. I'll merge it once appveyor completes. I have a feeling this should go into  RC_1_0 as well. the qbt quys were seeing an assert that seems related to this.

However though, I think the first patch was also good (and important). and the test should be fixed

**Comment by aldenml** [comment]
I will review the original idea, and after that, the backport

**Pull request merged**
